### ISSUE TITLE
com.google.android.gms.ads.AdSize.equalson a null object reference

### ISSUE THREAD

**Issue by naklow12** [googleads/googleads-mobile-unity#1004]
These are logs when I'm at editor. It looks okay.
`
Dummy Initialize
Dummy .ctor
Dummy CreateBannerView
Dummy LoadAd
Dummy ShowBannerView
`
But when I release game it turns to this: (LogCat results)

`2019.08.24 18:06:16.913 3882 3882 Error AndroidRuntime: Process: com.DuckingGames.GlassBlocks, PID: 3882
2019.08.24 18:06:16.913 3882 3882 Error AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.google.android.gms.ads.AdSize.equals(java.lang.Object)' on a null object reference
2019.08.24 18:06:16.913 3882 3882 Error AndroidRuntime: 	at com.google.android.gms.internal.ads.zzwu.zza(com.google.android.gms:play-services-ads-lite@@18.1.1:248)
2019.08.24 18:06:16.913 3882 3882 Error AndroidRuntime: 	at com.google.android.gms.internal.ads.zzwu.zza(com.google.android.gms:play-services-ads-lite@@18.1.1:87)
2019.08.24 18:06:16.913 3882 3882 Error AndroidRuntime: 	at com.google.android.gms.ads.BaseAdView.loadAd(com.google.android.gms:play-services-ads-lite@@18.1.1:15)
2019.08.24 18:06:16.913 3882 3882 Error AndroidRuntime: 	at com.google.android.gms.ads.AdView.loadAd(com.google.android.gms:play-services-ads-lite@@18.1.1:18)
2019.08.24 18:06:16.913 3882 3882 Error AndroidRuntime: 	at com.google.unity.ads.Banner$5.run(Banner.java:278)
2019.08.24 18:06:16.913 3882 3882 Error AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:790)
2019.08.24 18:06:16.913 3882 3882 Error AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
2019.08.24 18:06:16.913 3882 3882 Error AndroidRuntime: 	at android.os.Looper.loop(Looper.java:169)
2019.08.24 18:06:16.913 3882 3882 Error AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6521)
2019.08.24 18:06:16.913 3882 3882 Error AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
2019.08.24 18:06:16.913 3882 3882 Error AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
2019.08.24 18:06:16.913 3882 3882 Error AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
`
App crashed when is running.

**Comment by naklow12** [comment]
When I try it with "Gradle (experimental)" minifier it is not crashing like before. But there's another problem it gives this and there's no ad I see:

`2019.08.25 17:18:27.624 32407 32458 Error Unity: java.lang.ClassNotFoundException: Didn't find class "com/google/android/gms/ads/initialization/OnInitializationCompleteListener" on path: DexPathList[[zip file "/data/app/com.DuckingGames.GlassBlocks-TPFeNF0YjDTJZNlb-fNlUw==/base.apk"],nativeLibraryDirectories=[/data/app/com.DuckingGames.GlassBlocks-TPFeNF0YjDTJZNlb-fNlUw==/lib/arm, /data/app/com.DuckingGames.GlassBlocks-TPFeNF0YjDTJZNlb-fNlUw==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
2019.08.25 17:18:27.624 32407 32458 Error Unity: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
2019.08.25 17:18:27.624 32407 32458 Error Unity: 	at c
2019.08.25 17:18:27.641 32407 32458 Error Unity: AndroidJavaException: java.lang.ClassNotFoundException: Didn't find class "com/google/android/gms/ads/initialization/OnInitializationCompleteListener" on path: DexPathList[[zip file "/data/app/com.DuckingGames.GlassBlocks-TPFeNF0YjDTJZNlb-fNlUw==/base.apk"],nativeLibraryDirectories=[/data/app/com.DuckingGames.GlassBlocks-TPFeNF0YjDTJZNlb-fNlUw==/lib/arm, /data/app/com.DuckingGames.GlassBlocks-TPFeNF0YjDTJZNlb-fNlUw==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
2019.08.25 17:18:27.641 32407 32458 Error Unity: java.lang.ClassNotFoundException: Didn't find class "com/google/android/gms/ads/initialization/OnInitializationCompleteListener" on path: DexPathList[[zip file "/data/app/com.DuckingGames.GlassBlocks-TPFeNF0YjDTJZNlb-fNlUw==/base.apk"],nativeLibraryDirectories=[/data/app/com.DuckingGames.GlassBlocks-TPFeNF0YjDTJZNlb-fNlUw==/lib/arm, /data/app/com.DuckingGames.GlassBlocks-TPFeNF0YjDTJZNlb-fNlUw==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
2019.08.25 17:18:27.641 32407 32458 Error Unity: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
2019.08.25 17:18:27.641 32407 32458 Error Unity: 	at c
`

**Comment by naklow12** [comment]
I solved problem myself. Guys if you have first problem never use Smart Size Banners. Change it to Banner. Smart Banners are not working right now. 

If you got second error, just change Minify options to None, don't touch them. I can work with IL2CPP and x64 there's no problem about it. Have a nice day.
