### ISSUE TITLE
Didn't find class "android.support.v4.content.ContextCompat"

### ISSUE THREAD

**Issue by waqasbhattii** [googleads/googleads-mobile-unity#1011]
Hi, 

Please guide me why i am getting the following error, i uploaded my game on Google Play Store and then downloaded it on device with wifi turned on. Its cashing and stopping every time, please let me know what is the issue. I am using latest unity package of Google mobile ads in my game.

java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/content/ContextCompat;
        at com.moat.analytics.mobile.cha.n.ͺ(SourceFile:5303)
        at com.moat.analytics.mobile.cha.n.ʽ(SourceFile:178)
        at com.moat.analytics.mobile.cha.n.ˎ(SourceFile:144)
        at com.moat.analytics.mobile.cha.n.<init>(SourceFile:81)
        at com.moat.analytics.mobile.cha.n.ˏ(SourceFile:63)
        at com.moat.analytics.mobile.cha.f.ˎ(SourceFile:108)
        at com.moat.analytics.mobile.cha.t$2$2.ˏ(SourceFile:135)
        at com.moat.analytics.mobile.cha.t$d$5.run(SourceFile:245)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.ContextCompat" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.cg.impossible.ramp.carstunts.racing-zjIoc40pUD5ZaTUVnd7B-A==/base.apk", zip file "/data/app/com.cg.impossible.ramp.carstunts.racing-zjIoc40pUD5ZaTUVnd7B-A==/split_config.arm64_v8a.apk"],nativeLibraryDirectories=[/data/app/com.cg.impossible.ramp.carstunts.racing-zjIoc40pUD5ZaTUVnd7B-A==/lib/arm64, /data/app/com.cg.impossible.ramp.carstunts.racing-zjIoc40pUD5ZaTUVnd7B-A==/base.apk!/lib/arm64-v8a, /data/app/com.cg.impossible.ramp.carstunts.racing-zjIoc40pUD5ZaTUVnd7B-A==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.moat.analytics.mobile.cha.n.ͺ(SourceFile:5303) 
        at com.moat.analytics.mobile.cha.n.ʽ(SourceFile:178) 
        at com.moat.analytics.mobile.cha.n.ˎ(SourceFile:144) 
        at com.moat.analytics.mobile.cha.n.<init>(SourceFile:81) 
        at com.moat.analytics.mobile.cha.n.ˏ(SourceFile:63) 
        at com.moat.analytics.mobile.cha.f.ˎ(SourceFile:108) 
        at com.moat.analytics.mobile.cha.t$2$2.ˏ(SourceFile:135) 
        at com.moat.analytics.mobile.cha.t$d$5.run(SourceFile:245) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7050) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965) 
    	Suppressed: java.io.IOException: No original dex files found for dex location (arm64) /data/app/com.cg.impossible.ramp.carstunts.racing-zjIoc40pUD5ZaTUVnd7B-A==/split_config.arm64_v8a.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:354)
        at dalvik.system.DexFile.<init>(DexFile.java:101)
        at dalvik.system.DexFile.<init>(DexFile.java:75)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:394)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:354)
        at dalvik.system.DexPathList.<init>(DexPathList.java:164)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:74)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:74)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:40)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:764)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:847)
        at android.app.LoadedApk.getResources(LoadedApk.java:1088)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2563)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6100)
        at android.app.ActivityThread.access$1200(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1785)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        		... 5 more

**Comment by arpaplus** [comment]
Do you use Chartboost mediation or Chartboost ads together with AdMob?

**Comment by stowy** [comment]
You appear to have libraries referring to android support libraries.

You need to ensure that all dependencies are jetified so that they all
refer to androidx support libraries.

This is done using the play services resolve android settings menu (see
attached screenshot). Go to 'Assets' -> 'Play Services Resolver' ->
'Android Resolver' -> 'Settings' and select 'Use Jetifier'.
