### ISSUE TITLE
Android app crashing after showing banner ad

### ISSUE THREAD

**Issue by stefanvelnita** [googleads/googleads-mobile-unity#1037]
Hi, my app is crashing after showing 1 or 2 banner ads:

java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
 at android.view.ViewGroup.addViewInner(ViewGroup.java:4417)
 at android.view.ViewGroup.addView(ViewGroup.java:4258)
 at android.view.ViewGroup.addView(ViewGroup.java:4198)
 at android.view.ViewGroup.addView(ViewGroup.java:4171)
 at com.google.android.gms.internal.ads.zzcln.onSuccess(com.google.android.gms:play-services-ads@@18.1.1:17)
 at com.google.android.gms.internal.ads.zzdch.run(com.google.android.gms:play-services-ads@@18.1.1:13)
 at android.os.Handler.handleCallback(Handler.java:751)
 at android.os.Handler.dispatchMessage(Handler.java:95)
 at com.google.android.gms.internal.ads.zzczj.zzb(com.google.android.gms:play-services-ads-lite@@18.1.1:7)
 at com.google.android.gms.internal.ads.zzatp.zzb(com.google.android.gms:play-services-ads@@18.1.1:8)
 at com.google.android.gms.internal.ads.zzczj.dispatchMessage(com.google.android.gms:play-services-ads-lite@@18.1.1:5)
 at android.os.Looper.loop(Looper.java:154)
 at android.app.ActivityThread.main(ActivityThread.java:6125)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)

**Comment by stowy** [comment]
Hi @stefanvelnita thanks for reporting, this is an issue we have been seeing with the Android SDK. Are you using mediation? If so, can you please advise which mediation networks you are using and what versions?

**Comment by stefanvelnita** [comment]
Hi @stowy !

Yes, I am using mediation. The mediated networks are:

- Unity Ads: com.google.ads.mediation.unity-3.0.0.2
- InMobi: com.google.ads.mediation.inmobi-7.2.7.0

**Comment by castanets** [comment]
SmartBanner is Spawning pool of glitch. not smart. just idiot. in my case, i use ( banner = new BannerView(BannerUnitID, AdSize.Banner, AdPosition.Bottom);). it work good. Tell me if it's fixed please
