### ISSUE TITLE
NullPointerException: Attempt to invoke interface method 'java.lang.String com.google.android.gms.internal.ads.zzddf.getVersion()' on a null object reference

### ISSUE THREAD

**Issue by thiagolr** [googleads/googleads-mobile-unity#1173]
We are getting this crash on the "pre-launch report" from Google Play.

Full log here: https://pastebin.com/7ETKpMQd

Unity Version: 2019.2.21f1
Ads Version: 4.2.1

```
02-15 04:05:21.287: W/Ads(11574): #007 Could not call remote method. @28
02-15 04:05:21.287: W/Ads(11574): java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String com.google.android.gms.internal.ads.zzddf.getVersion()' on a null object reference
02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.internal.ads.zzaoq.getVersion(com.google.android.gms:play-services-ads-lite@@18.3.0:32)
02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.internal.ads.zzcss.zzank(com.google.android.gms:play-services-ads@@18.3.0:10)
02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.internal.ads.zzcsv.call(Unknown Source:2)
02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.internal.ads.zzdhu.zzars(com.google.android.gms:play-services-ads@@18.3.0:5)
02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.internal.ads.zzdha.run(com.google.android.gms:play-services-ads@@18.3.0:8)
02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.internal.ads.zzdhs.run(com.google.android.gms:play-services-ads@@18.3.0:11)
02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.internal.ads.zzazf.execute(com.google.android.gms:play-services-ads@@18.3.0:4)
02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.internal.ads.zzaze.execute(com.google.android.gms:play-services-ads@@18.3.0:4)
02-15 04:05:21.287: W/Ads(11574): 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.internal.ads.zzdfv.zzd(com.google.android.gms:play-services-ads@@18.3.0:5)
02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.internal.ads.zzcss.zzanc(com.google.android.gms:play-services-ads@@18.3.0:6)
02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.internal.ads.zzcua.zzs(com.google.android.gms:play-services-ads@@18.3.0:7)
02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.internal.ads.zzcfo.get(com.google.android.gms:play-services-ads@@18.3.0:9)
02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.internal.ads.zzdxd.get(com.google.android.gms:play-services-ads@@18.3.0:10)
02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.internal.ads.zzcii.get(com.google.android.gms:play-services-ads@@18.3.0:9)
02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.internal.ads.zzcia.get(com.google.android.gms:play-services-ads@@18.3.0:6)
02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.internal.ads.zzdxd.get(com.google.android.gms:play-services-ads@@18.3.0:10)
02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.internal.ads.zzchq.get(com.google.android.gms:play-services-ads@@18.3.0:7)
02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.internal.ads.zzdxd.get(com.google.android.gms:play-services-ads@@18.3.0:10)
02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.internal.ads.zzdxl.get(com.google.android.gms:play-services-ads@@18.3.0:17)
02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.internal.ads.zzbrq.get(com.google.android.gms:play-services-ads@@18.3.0:7)
02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.internal.ads.zzdxd.get(com.google.android.gms:play-services-ads@@18.3.0:10)
02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.internal.ads.zzbhm.zzadc(com.google.android.gms:play-services-ads@@18.3.0:208)
02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.internal.ads.zzcxr.zza(com.google.android.gms:play-services-ads@@18.3.0:3)
02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.internal.ads.zzcyt.zza(com.google.android.gms:play-services-ads@@18.3.0:31)
02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.internal.ads.zzcyz.zza(com.google.android.gms:play-services-ads@@18.3.0:13)
02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.internal.ads.zzasv.zza(com.google.android.gms:play-services-ads-lite@@18.3.0:9)
02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.ads.rewarded.RewardedAd.loadAd(com.google.android.gms:play-services-ads-lite@@18.3.0:6)
02-15 04:05:21.287: W/Ads(11574): 	at com.google.unity.ads.UnityRewardedAd$2.run(UnityRewardedAd.java:63)
02-15 04:05:21.287: W/Ads(11574): 	at android.os.Handler.handleCallback(Handler.java:790)
02-15 04:05:21.287: W/Ads(11574): 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-15 04:05:21.287: W/Ads(11574): 	at android.os.Looper.loop(Looper.java:164)
02-15 04:05:21.287: W/Ads(11574): 	at android.app.ActivityThread.main(ActivityThread.java:6523)
02-15 04:05:21.287: W/Ads(11574): 	at java.lang.reflect.Method.invoke(Native Method)
02-15 04:05:21.287: W/Ads(11574): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
02-15 04:05:21.287: W/Ads(11574): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
```

**Comment by stowy** [comment]
@thiagolr - thanks for reporting, I'm checking with the team about this issue.

**Comment by realluhui** [comment]
i have same issue

**Comment by rpaigavan** [comment]
I faced same issue. Any update on this?
Does anyone have solution?

**Comment by stowy** [comment]
Note this is a warning, not an exception. It means that it was unable to make this call and is logging the trace, but the app did not crash.  You can ignore this log.

**Comment by JBramauer** [comment]
Same here. Happening on an Amazon FireTV. No ads displaying at all. Could this be a connection issue that doesn't get handled correctly in the library?

**Comment by JasonWang6** [comment]
> Note this is a warning, not an exception. It means that it was unable to make this call and is logging the trace, but the app did not crash. You can ignore this log.



> Note this is a warning, not an exception. It means that it was unable to make this call and is logging the trace, but the app did not crash. You can ignore this log.

I found this exception appeared, the app will be forced to quit.

**Comment by muzi-li-2018** [comment]
I have the same issue, and reward ad doesn't showed.

**Comment by PriyankaM31191** [comment]
I am facing same issue in amazon device while I run unity app in it. Google ads sdk version is 19.7.0. Does anybody have solution for this ?

**Comment by superbderrick** [comment]
Hey I met same crash , Any solution ?

**Comment by Difficulty-in-naming** [comment]
+1

**Comment by EugenioLopez1** [comment]
+1

**Comment by zhaolin8** [comment]
+1

**Comment by 4nu812** [comment]
```
> We are getting this crash on the "pre-launch report" from Google Play.
> 
> Full log here: https://pastebin.com/7ETKpMQd
> 
> Unity Version: 2019.2.21f1
> Ads Version: 4.2.1
> 
> ```
> 02-15 04:05:21.287: W/Ads(11574): #007 Could not call remote method. @28
> 02-15 04:05:21.287: W/Ads(11574): java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String com.google.android.gms.internal.ads.zzddf.getVersion()' on a null object reference
> 02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.internal.ads.zzaoq.getVersion(com.google.android.gms:play-services-ads. -lite@@18.3.0:32)
> 02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.internal.ads.zzcss.zzank(com.google.android.gms:play-services-ads@@18.3.0:10)
> 02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.internal.ads.zzcsv.call(Unknown Source:2)
> 02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.internal.ads.zzdhu.zzars(com.google.android.gms:play-services-ads@@18.3.0:5)
> 02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.internal.ads.zzdha.run(com.google.android.gms:play-services-ads@@18.3.0:8)
> 02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.internal.ads.zzdhs.run(com.google.android.gms:play-services-ads@@18.3.0:11)
> 02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.internal.ads.zzazf.execute(com.google.android.gms:play-services-ads@@18.3.0:4)
> 02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.internal.ads.zzaze.execute(com.google.android.gms:play-services-ads@@18.3.0:4)
> 02-15 04:05:21.287: W/Ads(11574): 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
> 02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.internal.ads.zzdfv.zzd(com.google.android.gms:play-services-ads@@18.3.0:5)
> 02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.internal.ads.zzcss.zzanc(com.google.android.gms:play-services-ads@@18.3.0:6)
> 02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.internal.ads.zzcua.zzs(com.google.android.gms:play-services-ads@@18.3.0:7)
> 02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.internal.ads.zzcfo.get(com.google.android.gms:play-services-ads@@18.3.0:9)
> 02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.internal.ads.zzdxd.get(com.google.android.gms:play-services-ads@@18.3.0:10)
> 02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.internal.ads.zzcii.get(com.google.android.gms:play-services-ads@@18.3.0:9)
> 02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.internal.ads.zzcia.get(com.google.android.gms:play-services-ads@@18.3.0:6)
> 02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.internal.ads.zzdxd.get(com.google.android.gms:play-services-ads@@18.3.0:10)
> 02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.internal.ads.zzchq.get(com.google.android.gms:play-services-ads@@18.3.0:7)
> 02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.internal.ads.zzdxd.get(com.google.android.gms:play-services-ads@@18.3.0:10)
> 02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.internal.ads.zzdxl.get(com.google.android.gms:play-services-ads@@18.3.0:17)
> 02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.internal.ads.zzbrq.get(com.google.android.gms:play-services-ads@@18.3.0:7)
> 02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.internal.ads.zzdxd.get(com.google.android.gms:play-services-ads@@18.3.0:10)
> 02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.internal.ads.zzbhm.zzadc(com.google.android.gms:play-services-ads@@18.3.0:208)
> 02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.internal.ads.zzcxr.zza(com.google.android.gms:play-services-ads@@18.3.0:3)
> 02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.internal.ads.zzcyt.zza(com.google.android.gms:play-services-ads@@18.3.0:31)
> 02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.internal.ads.zzcyz.zza(com.google.android.gms:play-services-ads@@18.3.0:13)
> 02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.internal.ads.zzasv.zza(com.google.android.gms:play-services-ads-lite@@18.3.0:9)
> 02-15 04:05:21.287: W/Ads(11574): 	at com.google.android.gms.ads.rewarded.RewardedAd.loadAd(com.google.android.gms:play-services-ads-lite@@18.3.0:6)
> 02-15 04:05:21.287: W/Ads(11574): 	at com.google.unity.ads.UnityRewardedAd$2.run(UnityRewardedAd.java:63)
> 02-15 04:05:21.287: W/Ads(11574): 	at android.os.Handler.handleCallback(Handler.java:790)
> 02-15 04:05:21.287: W/Ads(11574): 	at android.os.Handler.dispatchMessage(Handler.java:99)
> 02-15 04:05:21.287: W/Ads(11574): 	at android.os.Looper.loop(Looper.java:164)
> 02-15 04:05:21.287: W/Ads(11574): 	at android.app.ActivityThread.main(ActivityThread.java:6523)
> 02-15 04:05:21.287: W/Ads(11574): 	at java.lang.reflect.Method.invoke(Native Method)
> 02-15 04:05:21.287: W/Ads(11574): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
> 02-15 04:05:21.287: W/Ads(11574): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
> ```


- [ ] # `````~~<!-- Error al cargar Screenshot_20240320-032827.png -->
- - **@


- [ ]  **~~
```
```
```
