### ISSUE TITLE
NPE after watching Rewarded Ad

### ISSUE THREAD

**Issue by thiagolr** [googleads/googleads-mobile-unity#1867]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2020.3.21f1
  * Google Mobile Ads Unity plugin version: 6.1.2
  * Platform: Android
  * Platform OS version: Any
  * Any specific devices issue occurs on: All
  * Mediation ad networks used, and their versions: Facebook 3.6.0

#### Steps to reproduce:

Watch a rewarded ad, after the ad ends and you close it the game crashes. It reproduces at least 1 out of 10 times.

I was using IronSource before and I didn't have any crashes after watching ads. I switched to AdMob to take advantage of its bidding solution and then a lots crashes started to happen:

![image](https://user-images.githubusercontent.com/107003/143617405-557cb15f-bc51-4fd8-be65-14b2591379c5.png)

Caused by java.lang.Error: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Version '2020.3.21f1 (a38c86f6690f)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'arm64-v8a'
Build fingerprint: 'motorola/lake_n/lake_n:10/QPWS30.61-21-18-7/fac4a:user/release-keys'
Revision: 'pvt'
ABI: 'arm64'
Timestamp: 2021-11-26 14:44:53-0300
pid: 23511, tid: 25255, name: Thread-404  >>> com.impossibleapps.walkinghero <<<
uid: 11229
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
Cause: null pointer dereference
    x0  000000773014ca50  x1  0000000000000000  x2  00000076ffcdd960  x3  0000000000000000
    x4  0000000000000001  x5  0000007801cafebd  x6  00000076ffcdd980  x7  00000076ffcdd920
    x8  0000000000000000  x9  0000000000000000  x10 0000000000000000  x11 0000000000000000
    x12 0000000000000000  x13 0000000000000000  x14 0000000000000000  x15 0000000000000000
    x16 0000007802025940  x17 00000078fe77681c  x18 0000000000000000  x19 0000007730122660
    x20 0000000000000000  x21 0000000000000001  x22 00000076ffce1020  x23 0000000000000000
    x24 0000000000000001  x25 000000773011b930  x26 0000000000000000  x27 0000000000000080
    x28 0000000000000000  x29 0000000000000000
    sp  00000076ffcdd8c0  lr  0000007801616b28  pc  0000007801616b28

backtrace:
      #00 pc 000000000073fb28  /data/app/com.impossibleapps.walkinghero-2fXdPXhEPzISPCfFaNq8mQ==/lib/arm64/libunity.so (BuildId: 2711f7407b5d284df452e5d8e70fa5833bff8771)
      #01 pc 0000000000741528  /data/app/com.impossibleapps.walkinghero-2fXdPXhEPzISPCfFaNq8mQ==/lib/arm64/libunity.so (BuildId: 2711f7407b5d284df452e5d8e70fa5833bff8771)
      #02 pc 00000000007416f0  /data/app/com.impossibleapps.walkinghero-2fXdPXhEPzISPCfFaNq8mQ==/lib/arm64/libunity.so (BuildId: 2711f7407b5d284df452e5d8e70fa5833bff8771)
      #03 pc 00000000003e4f48  /data/app/com.impossibleapps.walkinghero-2fXdPXhEPzISPCfFaNq8mQ==/lib/arm64/libunity.so (BuildId: 2711f7407b5d284df452e5d8e70fa5833bff8771)
      #04 pc 0000000001b75140  /data/app/com.impossibleapps.walkinghero-2fXdPXhEPzISPCfFaNq8mQ=<truncated: 7741 chars>
       at libunity.0x73fb28()
       at libunity.0x741528()
       at libunity.0x7416f0()
       at libunity.0x3e4f48()
       at libil2cpp.0x1b75140()
       at libil2cpp.0x7edbb8()
       at libil2cpp.0x96b380()
       at libunity.0x33d998()
       at libunity.0x34b09c()
       at libunity.0x34d1a8()
       at libunity.0x386e8c()
       at libunity.0x357414()
       at libunity.0x357830()
       at libunity.0x35737c()
       at libunity.0x397464()
       at libunity.0x397390()
       at libunity.0x208bf8()
       at libunity.0x3edcd8()
       at libil2cpp.0x1714a24()
       at libil2cpp.0x1003e3c()
       at libil2cpp.0x21343c4()
       at libil2cpp.0x21a55a0()
       at libil2cpp.0x21343c4()
       at libil2cpp.0x2134190()
       at libil2cpp.0x11670fc()
       at libil2cpp.0x81b290()
       at libil2cpp.0x96b380()
       at libunity.0x33d998()
       at libunity.0x34b09c()
       at libunity.0x354044()
       at libunity.0x353c24()
       at libunity.0x355bc0()

**Comment by xiaozzz** [comment]
same crash, how do you solve it?

```
2022-02-09 10:47:43.719 19204-19524/? E/CRASH:       #00 pc 0000000000629e70  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libunity.so (BuildId: ab9794f07849c2339bb6c27ea448dae664dc83b2)
2022-02-09 10:47:43.719 19204-19524/? E/CRASH:       #01 pc 000000000062b858  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libunity.so (BuildId: ab9794f07849c2339bb6c27ea448dae664dc83b2)
2022-02-09 10:47:43.719 19204-19524/? E/CRASH:       #02 pc 000000000062ba20  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libunity.so (BuildId: ab9794f07849c2339bb6c27ea448dae664dc83b2)
2022-02-09 10:47:43.719 19204-19524/? E/CRASH:       #03 pc 0000000000376798  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libunity.so (BuildId: ab9794f07849c2339bb6c27ea448dae664dc83b2)
2022-02-09 10:47:43.719 19204-19524/? E/CRASH:       #07 pc 00000000002d6c9c  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libunity.so (BuildId: ab9794f07849c2339bb6c27ea448dae664dc83b2)
2022-02-09 10:47:43.719 19204-19524/? E/CRASH:       #08 pc 00000000002e53b0  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libunity.so (BuildId: ab9794f07849c2339bb6c27ea448dae664dc83b2)
2022-02-09 10:47:43.719 19204-19524/? E/CRASH:       #09 pc 00000000002e6f3c  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libunity.so (BuildId: ab9794f07849c2339bb6c27ea448dae664dc83b2)
2022-02-09 10:47:43.719 19204-19524/? E/CRASH:       #10 pc 0000000000322368  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libunity.so (BuildId: ab9794f07849c2339bb6c27ea448dae664dc83b2)
2022-02-09 10:47:43.719 19204-19524/? E/CRASH:       #11 pc 00000000002f1140  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libunity.so (BuildId: ab9794f07849c2339bb6c27ea448dae664dc83b2)
2022-02-09 10:47:43.719 19204-19524/? E/CRASH:       #12 pc 00000000002f1528  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libunity.so (BuildId: ab9794f07849c2339bb6c27ea448dae664dc83b2)
2022-02-09 10:47:43.719 19204-19524/? E/CRASH:       #13 pc 00000000002f10a8  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libunity.so (BuildId: ab9794f07849c2339bb6c27ea448dae664dc83b2)
2022-02-09 10:47:43.719 19204-19524/? E/CRASH:       #14 pc 000000000033289c  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libunity.so (BuildId: ab9794f07849c2339bb6c27ea448dae664dc83b2)
2022-02-09 10:47:43.719 19204-19524/? E/CRASH:       #15 pc 00000000003327c8  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libunity.so (BuildId: ab9794f07849c2339bb6c27ea448dae664dc83b2)
2022-02-09 10:47:43.719 19204-19524/? E/CRASH:       #16 pc 00000000001bd600  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libunity.so (BuildId: ab9794f07849c2339bb6c27ea448dae664dc83b2)
2022-02-09 10:47:43.719 19204-19524/? E/CRASH:       #17 pc 000000000037db10  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libunity.so (BuildId: ab9794f07849c2339bb6c27ea448dae664dc83b2)
2022-02-09 10:47:43.838 19204-19419/? E/AndroidRuntime: FATAL EXCEPTION: UnityMain
    Process: com.kumapaw.matchgo, PID: 19204
    java.lang.Error: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
    Version '2020.3.12f1c1 (5887f62ce680)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'arm64-v8a'
    Build fingerprint: 'samsung/f52xqzc/f52x:11/RP1A.200720.012/E5260ZCU1AUE4:user/release-keys'
    Revision: '6'
    ABI: 'arm64'
    Timestamp: 2022-02-09 10:47:43+0800
    pid: 19204, tid: 19524, name: Thread-22  >>> com.kumapaw.matchgo <<<
    uid: 10406
    signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
    Cause: null pointer dereference
        x0  00000072703b2fe0  x1  0000000000000000  x2  00000071e01597f0  x3  0000000000000000
        x4  0000000000000001  x5  00000072f1be9dd9  x6  00000071e0159810  x7  00000071e01597b0
        x8  0000000000000000  x9  0000000000000000  x10 0000000000000000  x11 0000000000000000
        x12 0000000000000000  x13 0000000000000000  x14 0000000000000000  x15 0000000000000000
        x16 00000072f1f1a950  x17 000000766d27c93c  x18 0000000000000000  x19 00000072115e52f0
        x20 0000000000000000  x21 0000000000000001  x22 00000071e015b000  x23 0000000000000000
        x24 0000000000000001  x25 0000007211235220  x26 0000000000000000  x27 0000000000000080
        x28 0000000000000000  x29 0000000000000000
        sp  00000071e0159750  lr  00000072f157fe70  pc  00000072f157fe70
    
    backtrace:
          #00 pc 0000000000629e70  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libunity.so (BuildId: ab9794f07849c2339bb6c27ea448dae664dc83b2)
          #01 pc 000000000062b858  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libunity.so (BuildId: ab9794f07849c2339bb6c27ea448dae664dc83b2)
          #02 pc 000000000062ba20  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libunity.so (BuildId: ab9794f07849c2339bb6c27ea448dae664dc83b2)
          #03 pc 0000000000376798  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libunity.so (BuildId: ab9794f07849c2339bb6c27ea448dae664dc83b2)
          #04 pc 00000000012e53a4  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libil2cpp.so (BuildId: 4835c0eec68b50fbe8158a5a2f22638530297895)
          #05 pc 0000000000497808  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libil2cpp.so (BuildId: 4835c0eec68b50fbe8158a5a2f22638530297895)
          #06 pc 000000000054f720  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libil2cpp.so (BuildId: 4835c0eec68b50fbe8158a5a2f22638530297895)
          #07 pc 00000000002d6c9c  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libunity.so (BuildId: ab9794f07849c2339bb6c27ea448dae664dc83b2)
          #08 pc 00000000002e53b0  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libunity.so (BuildId: ab9794f07849c2339bb6c27ea448dae664dc83b2)
          #09 pc 00000000002e6f3c  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libunity.so (BuildId: ab9794f07849c2339bb6c27ea448dae664dc83b2)
          #10 pc 0000000000322368  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libunity.so (BuildId: ab9794f07849c2339bb6c27ea448dae664dc83b2)
          #11 pc 00000000002f1140  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libunity.so (BuildId: ab9794f07849c2339bb6c27ea448dae664dc83b2)
          #12 pc 00000000002f1528  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libunity.so (BuildId: ab9794f07849c2339bb6c27ea448dae664dc83b2)
          #13 pc 00000000002f10a8  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libunity.so (BuildId: ab9794f07849c2339bb6c27ea448dae664dc83b2)
2022-02-09 10:47:43.838 19204-19419/? E/AndroidRuntime:       #14 pc 000000000033289c  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libunity.so (BuildId: ab9794f07849c2339bb6c27ea448dae664dc83b2)
          #15 pc 00000000003327c8  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libunity.so (BuildId: ab9794f07849c2339bb6c27ea448dae664dc83b2)
          #16 pc 00000000001bd600  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libunity.so (BuildId: ab9794f07849c2339bb6c27ea448dae664dc83b2)
          #17 pc 000000000037db10  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libunity.so (BuildId: ab9794f07849c2339bb6c27ea448dae664dc83b2)
          #18 pc 00000000010ccb14  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libil2cpp.so (BuildId: 4835c0eec68b50fbe8158a5a2f22638530297895)
          #19 pc 00000000011c815c  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libil2cpp.so (BuildId: 4835c0eec68b50fbe8158a5a2f22638530297895)
          #20 pc 0000000000832898  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libil2cpp.so (BuildId: 4835c0eec68b50fbe8158a5a2f22638530297895)
          #21 pc 0000000000a86830  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libil2cpp.so (BuildId: 4835c0eec68b50fbe8158a5a2f22638530297895)
          #22 pc 0000000000b3e874  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libil2cpp.so (BuildId: 4835c0eec68b50fbe8158a5a2f22638530297895)
          #23 pc 0000000000a1fa40  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libil2cpp.so (BuildId: 4835c0eec68b50fbe8158a5a2f22638530297895)
          #24 pc 0000000000a30460  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libil2cpp.so (BuildId: 4835c0eec68b50fbe8158a5a2f22638530297895)
          #25 pc 0000000000bdbc74  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libil2cpp.so (BuildId: 4835c0eec68b50fbe8158a5a2f22638530297895)
          #26 pc 00000000012cee78  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libil2cpp.so (BuildId: 4835c0eec68b50fbe8158a5a2f22638530297895)
          #27 pc 0000000000c54450  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libil2cpp.so (BuildId: 4835c0eec68b50fbe8158a5a2f22638530297895)
          #28 pc 000000000108ce64  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libil2cpp.so (BuildId: 4835c0eec68b50fbe8158a5a2f22638530297895)
          #29 pc 0000000000832898  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libil2cpp.so (BuildId: 4835c0eec68b50fbe8158a5a2f22638530297895)
          #30 pc 0000000000a86830  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libil2cpp.so (BuildId: 4835c0eec68b50fbe8158a5a2f22638530297895)
          #31 pc 0000000000b3e874  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libil2cpp.so (BuildId: 4835c0eec68b50fbe8158a5a2f22638530297895)
          #32 pc 0000000000a1fa40  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libil2cpp.so (BuildId: 4835c0eec68b50fbe8158a5a2f22638530297895)
          #33 pc 0000000000c3bc28  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libil2cpp.so (BuildId: 4835c0eec68b50fbe8158a5a2f22638530297895)
          #34 pc 00000000004be828  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libil2cpp.so (BuildId: 4835c0eec68b50fbe8158a5a2f22638530297895)
2022-02-09 10:47:43.838 19204-19419/? E/AndroidRuntime:       #35 pc 000000000058e2cc  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libil2cpp.so (BuildId: 4835c0eec68b50fbe8158a5a2f22638530297895)
          #36 pc 0000000000557804  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libil2cpp.so (BuildId: 4835c0eec68b50fbe8158a5a2f22638530297895)
          #37 pc 0000000000523968  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libil2cpp.so (BuildId: 4835c0eec68b50fbe8158a5a2f22638530297895)
          #38 pc 00000000005222f4  /data/app/~~ZOBBHGTmYPhNjNuBmYVU5w==/com.kumapaw.matchgo-Vy5UFoxFMyYnTWsUHDWM_Q==/lib/arm64/libil2cpp.so (BuildId: 4835c0eec68b50fbe8158a5a2f22638530297895)
          #39 pc 00000000000b6144  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+64) (BuildId: cb4d51b018edf7df6f88050036c081d2)
          #40 pc 0000000000050d90  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: cb4d51b018edf7df6f88050036c081d2)
    
        at libunity.0x629e70(Native Method)
        at libunity.0x62b858(Native Method)
        at libunity.0x62ba20(Native Method)
        at libunity.0x376798(Native Method)
        at libil2cpp.0x12e53a4(Native Method)
        at libil2cpp.0x497808(Native Method)
        at libil2cpp.0x54f720(Native Method)
        at libunity.0x2d6c9c(Native Method)
        at libunity.0x2e53b0(Native Method)
        at libunity.0x2e6f3c(Native Method)
        at libunity.0x322368(Native Method)
        at libunity.0x2f1140(Native Method)
        at libunity.0x2f1528(Native Method)
        at libunity.0x2f10a8(Native Method)
        at libunity.0x33289c(Native Method)
        at libunity.0x3327c8(Native Method)
        at libunity.0x1bd600(Native Method)
        at libunity.0x37db10(Native Method)
        at libil2cpp.0x10ccb14(Native Method)
        at libil2cpp.0x11c815c(Native Method)
        at libil2cpp.0x832898(Native Method)
        at libil2cpp.0xa86830(Native Method)
        at libil2cpp.0xb3e874(Native Method)
        at libil2cpp.0xa1fa40(Native Method)
        at libil2cpp.0xa30460(Native Method)
        at libil2cpp.0xbdbc74(Native Method)
        at libil2cpp.0x12cee78(Native Method)
        at libil2cpp.0xc54450(Native Method)
        at libil2cpp.0x108ce64(Native Method)
        at libil2cpp.0x832898(Native Method)
        at libil2cpp.0xa86830(Native Method)
        at libil2cpp.0xb3e874(Native Method)
```

**Comment by Nyankoo** [comment]
@thiagolr Did you solve this issue?
