### ISSUE TITLE
Does not work with Android 12

### ISSUE THREAD

**Issue by sbmgamescom** [googleads/googleads-mobile-unity#1869]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2020.3.23f1
  * Google Mobile Ads Unity plugin version: 6.1.2
  * Platform: Android
  * Platform OS version: Android 12
  * Any specific devices issue occurs on: Google Pixel 4(Android 12)
  * Mediation ad networks used, and their versions: _____

#### Steps to reproduce:

An empty test project containing only the AdMob library crashes immediately after opening on a Google Pixel 4 (Android 12).
The project is built using the API level 31.

**Comment by NVentimiglia** [comment]
Hi @sbmgamescom, when you say the project does not work, what happens ? Are there any exception messages or error logs I can use to better understand this problem ?

**Comment by sbmgamescom** [comment]
2021-12-01 06:06:05.642 1614-4500/? I/ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.DefaultCompany.test_word/com.unity3d.player.UnityPlayerActivity bnds=[841,300][1043,624]} from uid 10156
2021-12-01 06:06:05.656 1614-1743/? I/ActivityManager: Start proc 19597:com.DefaultCompany.test_word/u0a1166 for pre-top-activity {com.DefaultCompany.test_word/com.unity3d.player.UnityPlayerActivity}
2021-12-01 06:06:05.701 19597-19597/? V/GraphicsEnvironment: ANGLE Developer option for 'com.DefaultCompany.test_word' set to: 'default'
2021-12-01 06:06:05.738 19597-19615/? E/AndroidRuntime: FATAL EXCEPTION: pool-3-thread-1
    Process: com.DefaultCompany.test_word, PID: 19597
    java.lang.IllegalArgumentException: com.DefaultCompany.test_word: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
        at androidx.work.impl.utils.ForceStopRunnable.getPendingIntent(ForceStopRunnable.java:174)
        at androidx.work.impl.utils.ForceStopRunnable.isForceStopped(ForceStopRunnable.java:108)
        at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:86)
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:75)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
2021-12-01 06:06:05.743 1614-3669/? W/ActivityTaskManager:   Force finishing activity com.DefaultCompany.test_word/com.unity3d.player.UnityPlayerActivity
2021-12-01 06:06:05.767 1614-3686/? I/ActivityManager: Process com.DefaultCompany.test_word (pid 19597) has died: prcp TOP 
2021-12-01 06:06:06.149 1614-3705/? W/InputManager-JNI: Input channel object '67d98c2 Splash Screen com.DefaultCompany.test_word (client)' was disposed without first being removed with the input manager!
2021-12-01 06:06:06.244 1614-1724/? W/ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{b2cbf36 u0 com.DefaultCompany.test_word/com.unity3d.player.UnityPlayerActivity t-1 f}}

**Comment by sbmgamescom** [comment]
![image](https://user-images.githubusercontent.com/46422509/144147944-4a55a8b3-68d8-469a-afa6-4d590135009e.png)

**Comment by NVentimiglia** [comment]
@sbmgamescom 

There is a work around for this issue described in the [release notes here](https://developers.google.com/admob/android/rel-notes). Please try out these steps, and let me know if you need any more assistance.
