### ISSUE TITLE
Error building Player: CommandInvokationFailure: Error unpacking file appcompat-v7-23.1.1.aar 

### ISSUE THREAD

**Issue by redfist** [googleads/googleads-mobile-unity#187]
Error building Player: CommandInvokationFailure: Error unpacking file appcompat-v7-23.1.1.aar
C:/Program Files/Java/jdk1.8.0_74\bin\jar.exe xf "D:\PROJEKTI\Ћирилица\Temp\StagingArea\aar\appcompat-v7-23.1.1.aar"

stderr[
java.io.FileNotFoundException: D:\PROJEKTI\????????\Temp\StagingArea\aar\appcompat-v7-23.1.1.aar (The filename, directory name, or volume label syntax is incorrect)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.tools.jar.Main.run(Main.java:307)
	at sun.tools.jar.Main.main(Main.java:1288)
]
stdout[

]

**Comment by rampara** [comment]
The latest version of the plugin (v3.1.0) resolves most issues Google Play services dependency resolution. Please re-open this issue if it persists for you on the latest version of the plugin.
