### ISSUE TITLE
Game crash during start up with error "java.lang.IllegalArgumentException: Unable to find native library VulkanLayerValidationTests"

### ISSUE THREAD

**Issue by XigmaSuji** [googleads/googleads-mobile-unity#1923]
* Unity version: 2020.3.17f1
  * Google Mobile Ads Unity plugin version: 6.1.2
  * Platform:  Android
  * Platform OS version: android 12
  * Any specific devices issue occurs on: tested on S8+ and one+
  

### [REQUIRED] Step 2: Describe the problem
App crashes with the following error on app 

2022-02-07 13:06:05.054 12673-12673/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xigmaGames.thebonfire2, PID: 12673
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xigmaGames.thebonfire2/android.app.NativeActivity}: java.lang.IllegalArgumentException: Unable to find native library VulkanLayerValidationTests using classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.xigmaGames.thebonfire2-FYWJvKvgw4r0YXnCOo5R3Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.xigmaGames.thebonfire2-FYWJvKvgw4r0YXnCOo5R3Q==/lib/arm64, /data/app/com.xigmaGames.thebonfire2-FYWJvKvgw4r0YXnCOo5R3Q==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3037)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3172)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1906)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6863)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalArgumentException: Unable to find native library VulkanLayerValidationTests using classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.xigmaGames.thebonfire2-FYWJvKvgw4r0YXnCOo5R3Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.xigmaGames.thebonfire2-FYWJvKvgw4r0YXnCOo5R3Q==/lib/arm64, /data/app/com.xigmaGames.thebonfire2-FYWJvKvgw4r0YXnCOo5R3Q==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]]
        at android.app.NativeActivity.onCreate(NativeActivity.java:161)
        at android.app.Activity.performCreate(Activity.java:7149)
        at android.app.Activity.performCreate(Activity.java:7140)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1288)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3017)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3172) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1906) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6863) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
2022-02-07 13:06:12.991 12834-12834/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xigmaGames.thebonfire2, PID: 12834
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xigmaGames.thebonfire2/android.app.NativeActivity}: java.lang.IllegalArgumentException: Unable to find native library VulkanLayerValidationTests using classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.xigmaGames.thebonfire2-FYWJvKvgw4r0YXnCOo5R3Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.xigmaGames.thebonfire2-FYWJvKvgw4r0YXnCOo5R3Q==/lib/arm64, /data/app/com.xigmaGames.thebonfire2-FYWJvKvgw4r0YXnCOo5R3Q==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3037)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3172)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1906)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6863)
        at java.lang.reflect.Method.invoke(Native Method)
2022-02-07 13:06:12.992 493-493/? E/SELinux: avc:  denied  { find } for service=opdiagnose pid=12834 uid=10255 scontext=u:r:untrusted_app:s0:c255,c256,c512,c768 tcontext=u:object_r:opdiagnose_service:s0 tclass=service_manager permissive=0
2022-02-07 13:06:12.992 493-493/? E/SELinux: avc:  denied  { find } for service=opdiagnose pid=12834 uid=10255 scontext=u:r:untrusted_app:s0:c255,c256,c512,c768 tcontext=u:object_r:opdiagnose_service:s0 tclass=service_manager permissive=0

#### Steps to reproduce:
We wanted to support the admob for android 12 thus we updated the admob to the latest version and updated our unity to 2020 to support the newer grade 6.1.1 the project already has updated IAP and firebase. After taking a successful ask build the game crashes with the following error.

What am I missing ?

**Comment by michalzembron** [comment]
I've got the same problem, but on freshly made project where there was no other versions of GMA previously installed

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now.

If you are still experiencing the problem, please file a new issue with the same description, what happens and system / network tracing / Charles logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution.
