### ISSUE TITLE
Crash, InstantiationError: rewarded.RewardedAd (GoogleMobileAds-native.unitypackage)

### ISSUE THREAD

**Issue by mohammadmahdi123** [googleads/googleads-mobile-unity#1965]
I get this error when requesting a rewarded video then crashing.
It is initialized successfully.
```
Unity: 2019.4
Platform: Android
GoogleMobileAds-native.unitypackage: Latest
Google Mobile Games: 0.10.12, 0.10.14

```

```
2022/03/11 21:44:42.128 19921 19921 Error AndroidRuntime java.lang.InstantiationError: com.google.android.gms.ads.rewarded.RewardedAd
2022/03/11 21:44:42.128 19921 19921 Error AndroidRuntime 	at com.google.unity.ads.UnityRewardedAd$1.run(UnityRewardedAd.java:53)
2022/03/11 21:44:42.128 19921 19921 Error AndroidRuntime 	at android.os.Handler.handleCallback(Handler.java:808)
2022/03/11 21:44:42.128 19921 19921 Error AndroidRuntime 	at android.os.Handler.dispatchMessage(Handler.java:101)
2022/03/11 21:44:42.128 19921 19921 Error AndroidRuntime 	at android.os.Looper.loop(Looper.java:166)
2022/03/11 21:44:42.128 19921 19921 Error AndroidRuntime 	at android.app.ActivityThread.main(ActivityThread.java:7529)
2022/03/11 21:44:42.128 19921 19921 Error AndroidRuntime 	at java.lang.reflect.Method.invoke(Native Method)
2022/03/11 21:44:42.128 19921 19921 Error AndroidRuntime 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
2022/03/11 21:44:42.128 19921 19921 Error AndroidRuntime 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```
MainTemplate.gradle
```
dependencies {
    implementation 'ir.tapsell.plus:tapsell-plus-sdk-unity:2.1.6'
    implementation fileTree(dir: 'libs', include: ['*.jar'])
// Android Resolver Dependencies Start
    implementation 'com.google.ads.mediation:chartboost:8.3.0.0' // Assets/GoogleMobileAds/Editor/ChartboostMediationDependencies.xml:8
    implementation 'com.google.ads.mediation:vungle:6.10.3.0' // Assets/GoogleMobileAds/Editor/VungleMediationDependencies.xml:8
    implementation 'com.google.android.gms:play-services-ads:18.3.0' // Assets/PlayServicesResolver/Editor/DeemaunityDependencies.xml:7
    implementation 'com.google.android.gms:play-services-ads:19.5.0' // Assets/GoogleMobileAds/Editor/GoogleMobileAdsDependencies.xml:7
    implementation 'com.google.android.gms:play-services-base:17.6.0' // Assets/Firebase/Editor/AppDependencies.xml:17
    implementation 'com.google.code.gson:gson:2.8.5' // Assets/GoogleMobileAds/Editor/GoogleMobileAdsDependencies.xml:13
    implementation 'com.google.firebase:firebase-analytics:19.0.0' // Assets/Firebase/Editor/MessagingDependencies.xml:15
    implementation 'com.google.firebase:firebase-analytics-unity:8.0.0' // Assets/Firebase/Editor/AnalyticsDependencies.xml:18
    implementation 'com.google.firebase:firebase-app-unity:8.0.0' // Assets/Firebase/Editor/AppDependencies.xml:22
    implementation 'com.google.firebase:firebase-common:20.0.0' // Assets/Firebase/Editor/AppDependencies.xml:13
    implementation 'com.google.firebase:firebase-messaging:22.0.0' // Assets/Firebase/Editor/MessagingDependencies.xml:13
    implementation 'com.google.firebase:firebase-messaging-unity:8.0.0' // Assets/Firebase/Editor/MessagingDependencies.xml:20
    implementation 'com.google.games:gpgs-plugin-support:0.10.12' // Assets/GooglePlayGames/Editor/GooglePlayGamesPluginDependencies.xml:11
    implementation 'com.squareup.okhttp3:okhttp:3.12.0' // Assets/PlayServicesResolver/Editor/DeemaunityDependencies.xml:9
    implementation 'com.squareup.okio:okio:2.4.1' // Assets/PlayServicesResolver/Editor/DeemaunityDependencies.xml:11
// Android Resolver Dependencies End
**DEPS**}
```

**Comment by NVentimiglia** [comment]
can you try posting your `build.gradle` file?
