### ISSUE TITLE
Failed to integrate mediation adapters in Unity 5

### ISSUE THREAD

**Issue by aniluk** [googleads/googleads-mobile-unity#206]
I am trying to integrate the mediation adapters in a unity android sample project. I have imported all SDK's as per the integration guide.

I have integrated the Google Mobile Ads SDK into Unity according to the developer guide and it could run successfully. But when I was integrating the mediation networks the application it fails with following exception

Fail to instantiate adapter GADMAdapterVungleRewardBasedVideoAd

android.os.RemoteException

	at com.google.android.gms.internal.zzew.zzai(Unknown Source)

	at com.google.android.gms.internal.zzew.zzah(Unknown Source)

	at com.google.android.gms.internal.zzew.zzaf(Unknown Source)

	at com.google.android.gms.internal.zzex$zza.onTransact(Unknown Source)

	at android.os.Binder.transact(Binder.java:380)

	at maps.an.b$a$a.a(:com.google.android.gms.alldynamite:94)

	at maps.ay.c.b(:com.google.android.gms.alldynamite:194)

	at maps.az.f.a(:com.google.android.gms.alldynamite:53)

	at maps.be.a$1.run(:com.google.android.gms.alldynamite:19)

	at maps.be.e$2.call(:com.google.android.gms.alldynamite:52)

	at maps.be.e$3.run(:com.google.android.gms.alldynamite:75)

	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)

	at java.util.concurrent.FutureTask.run(FutureTask.java:237)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)

	at java.lang.Thread.run(Thread.java:818)

Fail to instantiate adapter GADMAdapterAppLovinRewardBasedVideoAd

android.os.RemoteException

	at com.google.android.gms.internal.zzew.zzai(Unknown Source)

	at com.google.android.gms.internal.zzew.zzah(Unknown Source)

	at com.google.android.gms.internal.zzew.zzaf(Unknown Source)

	at com.google.android.gms.internal.zzex$zza.onTransact(Unknown Source)

	at android.os.Binder.transact(Binder.java:380)

	at maps.an.b$a$a.a(:com.google.android.gms.alldynamite:94)

	at maps.ay.c.b(:com.google.android.gms.alldynamite:194)

	at maps.az.f.a(:com.google.android.gms.alldynamite:53)

	at maps.be.a$1.run(:com.google.android.gms.alldynamite:19)

	at maps.be.e$2.call(:com.google.android.gms.alldynamite:52)

	at maps.be.e$3.run(:com.google.android.gms.alldynamite:75)

	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)

	at java.util.concurrent.FutureTask.run(FutureTask.java:237)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)

	at java.lang.Thread.run(Thread.java:818)

Fail to instantiate adapter GADMAdapterChartboost

android.os.RemoteException

	at com.google.android.gms.internal.zzew.zzai(Unknown Source)

	at com.google.android.gms.internal.zzew.zzah(Unknown Source)

	at com.google.android.gms.internal.zzew.zzaf(Unknown Source)

	at com.google.android.gms.internal.zzex$zza.onTransact(Unknown Source)

	at android.os.Binder.transact(Binder.java:380)

	at maps.an.b$a$a.a(:com.google.android.gms.alldynamite:94)

	at maps.ay.c.b(:com.google.android.gms.alldynamite:194)

	at maps.az.f.a(:com.google.android.gms.alldynamite:53)

	at maps.be.a$1.run(:com.google.android.gms.alldynamite:19)

	at maps.be.e$2.call(:com.google.android.gms.alldynamite:52)

	at maps.be.e$3.run(:com.google.android.gms.alldynamite:75)

	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)

	at java.util.concurrent.FutureTask.run(FutureTask.java:237)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)

	at java.lang.Thread.run(Thread.java:818)

Fail to instantiate adapter GADMAdapterUnity

android.os.RemoteException

	at com.google.android.gms.internal.zzew.zzai(Unknown Source)

	at com.google.android.gms.internal.zzew.zzah(Unknown Source)

	at com.google.android.gms.internal.zzew.zzaf(Unknown Source)

	at com.google.android.gms.internal.zzex$zza.onTransact(Unknown Source)

	at android.os.Binder.transact(Binder.java:380)

	at maps.an.b$a$a.a(:com.google.android.gms.alldynamite:94)

	at maps.ay.c.b(:com.google.android.gms.alldynamite:194)

	at maps.az.f.a(:com.google.android.gms.alldynamite:53)

	at maps.be.a$1.run(:com.google.android.gms.alldynamite:19)

	at maps.be.e$2.call(:com.google.android.gms.alldynamite:52)

	at maps.be.e$3.run(:com.google.android.gms.alldynamite:75)

	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)

	at java.util.concurrent.FutureTask.run(FutureTask.java:237)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)

	at java.lang.Thread.run(Thread.java:818)

Fail to instantiate adapter GADMAdapterAdColony

android.os.RemoteException

	at com.google.android.gms.internal.zzew.zzai(Unknown Source)

	at com.google.android.gms.internal.zzew.zzah(Unknown Source)

	at com.google.android.gms.internal.zzew.zzaf(Unknown Source)

	at com.google.android.gms.internal.zzex$zza.onTransact(Unknown Source)

	at android.os.Binder.transact(Binder.java:380)

	at maps.an.b$a$a.a(:com.google.android.gms.alldynamite:94)

	at maps.ay.c.b(:com.google.android.gms.alldynamite:194)

	at maps.az.f.a(:com.google.android.gms.alldynamite:53)

	at maps.be.a$1.run(:com.google.android.gms.alldynamite:19)

	at maps.be.e$2.call(:com.google.android.gms.alldynamite:52)

	at maps.be.e$3.run(:com.google.android.gms.alldynamite:75)

	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)

	at java.util.concurrent.FutureTask.run(FutureTask.java:237)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)

	at java.lang.Thread.run(Thread.java:818)

Do I need to call the instantiation call for each ad network explicitly with their appkey and secretkey ?

I am using Unity 5.2.2f1 and have integrated Google Mobile Ads SDK 3.0.3.

**Comment by rampara** [comment]
Failure to instantiate adapters usually means the adapters are not included in your project. Also, the adapter names from your logcat output correspond to iOS adapters. Are you using iOS ad units in an Android application?

**Comment by aniluk** [comment]
rampara,
It was the thing, by mistake I was using iOS ad unit ids in Android application. Thanks for the help.
