### ISSUE TITLE
Admob 7.0.1 with Mediation have App Crash

### ISSUE THREAD

**Issue by LobosBB** [googleads/googleads-mobile-unity#2062]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.3.2f1
  * Google Mobile Ads Unity plugin version: 7.0.1
  * Platform: Android
  * Platform OS version: Android 12
  * Any specific devices issue occurs on: 
  * Mediation ad networks used, and their versions: Facebook Mediation 3.6.1

#### Steps to reproduce:

App is crashed when using mediation (Facebook and UnityAds also)

Log Cat

2022-05-27 18:00:23.820 19645-19711/? E/Unity: AndroidJavaException: java.lang.ClassNotFoundException: com.google.android.gms.ads.mediation.admob.AdMobExtras
    java.lang.ClassNotFoundException: com.google.android.gms.ads.mediation.admob.AdMobExtras
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
        at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
        at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
     Caused by: java.lang.ClassNotFoundException: com.google.android.gms.ads.mediation.admob.AdMobExtras
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:454) 
        at com.unity3d.player.UnityPlayer.nativeRender(Native Method) 
        at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0) 
        at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loopOnce(Looper.java:226) 
        at android.os.Looper.loop(Looper.java:313) 
        at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20) 
      at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <00000000000000000000000000000000>:0 
      at UnityEngine.AndroidJNISafe.FindClass (System.String name) [0x00000] in <00000000000000000000000000000000>

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by dhamelin** [comment]
Latest AdMob SDK doesn't seem to be compatible with com.google.android.gms:play-services-ads:**21.0.0** (or any play-services-xxx:21.0.0, not sure where deprecated AdMobExtras was removed from)

I fixed it by forcing  v20.6.0: com.google.android.gms:play-services-ads:[20.6.0]

**Comment by NVentimiglia** [comment]
@dhamelin we will release an update with Android V21 support shortly.

**Comment by LobosBB** [comment]
I solved this by changing this line into GoogleMobileAdsDependencies.xml

<androidPackage spec="com.google.android.gms:play-services-ads:20.6.0">
to this line
<androidPackage spec="com.google.android.gms:play-services-ads:[20.6.0]">

**Comment by LobosBB** [comment]
I solved this problem by changing this line into GoogleMobileAdsDependencies.xml

`<androidPackage spec="com.google.android.gms:play-services-ads:20.6.0">`

to this line

`<androidPackage spec="com.google.android.gms:play-services-ads:[20.6.0]">`

**Comment by scprashi** [comment]
> @dhamelin we will release an update with Android V21 support shortly.

Hi, do you any timelines for this update? so that we can plan our app release accordingly.
We are eagerly waiting to update to 21.0.0 version to use new ANR optimisation flags added as part of the latest release.Thanks for looking in to this.

**Comment by damienAdxperience** [comment]
I have this problem only when I put the facebook adapter on. It changes all my dependency.

I did this:

`<androidPackage spec="com.google.android.gms:play-services-ads:[20.6.0]">`

But it doesn't matter, I still have the error

`2022-05-27 18:00:23.820 19645-19711/? E/Unity: AndroidJavaException: java.lang.ClassNotFoundException: com.google.android.gms.ads.mediation.admob.AdMobExtras`

So the other mediation works, any ideas for Facebook?

**Comment by scprashi** [comment]
> @dhamelin we will release an update with Android V21 support shortly.

@NVentimiglia thanks for quick update and we are able to integrate the new plugin without any issue.Much appreciated.
