### ISSUE TITLE
Android Stuck (Arn) when resum game from background

### ISSUE THREAD

**Issue by Zasuozz** [googleads/googleads-mobile-unity#2138]
REQUIRED
    Unity version: 2021.3.5
    Google Mobile Ads Unity plugin version: 7.1.0 
    Platform:  Android
    Platform OS version: android 11 
    Device: Redmi 9 -Ram 4G
    Mediation ad networks used, and their versions: admob only
-Steps to reproduce the bug
+Play game, hide game to background , open other game tap hide and reopen old game ,when show Interstitial ad or Open Ad ,game stuck(ARN) with log 
+,#004 The webview is destroyed. Ignoring action
.When push the back button in device see Log
W/cr_AwContents: Application attempted to call on a destroyed WebView
    java.lang.Throwable
        at org.chromium.android_webview.AwContents.l(chromium-TrichromeWebViewGoogle.aab-stable-506007133:1729)
        at com.android.webview.chromium.WebViewChromium.canGoBack(chromium-TrichromeWebViewGoogle.aab-stable-506007133:2491)
        at android.webkit.WebView.canGoBack(WebView.java:943)
        at com.google.android.gms.ads.internal.webview.y.canGoBack(:com.google.android.gms.policy_ads_fdr_dynamite@221908400@221908400057.447330857.447330857:0)
        at com.google.android.gms.ads.internal.overlay.k.m(:com.google.android.gms.policy_ads_fdr_dynamite@221908400@221908400057.447330857.447330857:1)
        at com.google.android.gms.ads.internal.overlay.client.a.bO(:com.google.android.gms.policy_ads_fdr_dynamite@221908400@221908400057.447330857.447330857:9)
        at adz.onTransact(:com.google.android.gms.policy_ads_fdr_dynamite@221908400@221908400057.447330857.447330857:4)
        at android.os.Binder.transact(Binder.java:1043)
        at com.google.android.gms.internal.ads.zzaqv.zzbk(com.google.android.gms:play-services-ads-base@@21.0.0:2)
        at com.google.android.gms.internal.ads.zzbxs.zzE(com.google.android.gms:play-services-ads-lite@@21.0.0:2)
        at com.google.android.gms.ads.AdActivity.onBackPressed(com.google.android.gms:play-services-ads-lite@@21.0.0:1)
        at android.app.Activity.onKeyUp(Activity.java:3869)
        at android.view.KeyEvent.dispatch(KeyEvent.java:2888)
        at android.app.Activity.dispatchKeyEvent(Activity.java:4175)
        at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:410)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:6270)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6133)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5622)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5679)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5645)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5797)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5653)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5854)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5626)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5679)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5645)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5653)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5626)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5679)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5645)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5830)
        at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:5994)
        at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3184)
        at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2726)
        at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2717)
        at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3161)
        at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:143)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:7864)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)

**Comment by NVentimiglia** [comment]
@Zasuozz 

The latest release includes fixes for the Android ANR issue. This fix however requires [Optimize initialization and ad loading to be enabled] (https://developers.google.com/admob/android/optimize-initialization).

Please follow the instructions here, at let me know if this comes up again.

**Comment by shefich** [comment]
@NVentimiglia I have too many "android.os.MessageQueue.nativePollOnce" ANRs. 
Initialization and ads loading optimised. 
Bool GoogleMobileAds.Api.MobileAds.RaiseAdEventsOnUnityMainThread = true;
What can be the cause? How can I fix these ANRs?
