### ISSUE TITLE
Build Failed In 3D Unity Project

### ISSUE THREAD

**Issue by MuhammadWaqasOfficial** [googleads/googleads-mobile-unity#2293]
Step 1: Describe your environment

  * Unity version: 2022.1.3f1
  * Google Mobile Ads Unity plugin version: 7.2.0
  * Platform: Android, Unity Editor
Step 2: Describe the problem
Unity Build Failed For Android when empty unity project type is "3D" with following errors.(No build error in case of Empty 2D project.)

Error 1
Building Library\Bee\artifacts\Android\ManagedStripped failed with output:
C:\Program Files\Unity\Hub\Editor\2022.1.13f1\Editor\Data\il2cpp\build\deploy\UnityLinker.exe --search-directory=D:/Workspace/AdsManager/Library/Bee/PlayerScriptAssemblies --search-directory=C:/Program Files/Unity/Hub/Editor/2022.1.13f1/Editor/Data/PlaybackEngines/AndroidPlayer/Variations/il2cpp/Managed --search-directory=D:/Workspace/AdsManager/Assets/GoogleMobileAds --search-directory=D:/Workspace/AdsManager/Library/PackageCache/com.unity.nuget.newtonsoft-json@3.0.2/Runtime/AOT --search-directory=C:/Program Files/Unity/Hub/Editor/2022.1.13f1/Editor/Data/MonoBleedingEdge/lib/mono/unityaot-linux --search-directory=C:/Program Files/Unity/Hub/Editor/2022.1.13f1/Editor/Data/MonoBleedingEdge/lib/mono/unityaot-linux/Facades --out=Library/Bee/artifacts/Android/ManagedStripped --include-link-xml=D:/Workspace/AdsManager/Temp/StagingArea/Data/Managed\MethodsToPreserve.xml --include-link-xml=D:/Workspace/AdsManager/Temp/StagingArea/Data/Managed\TypesInScenes.xml --include-link-xml=D:/Workspace/AdsManager/Temp/StagingArea/Data/Managed\SerializedTypes.xml --include-link-xml=D:\Workspace\AdsManager\Assets\GoogleMobileAds\link.xml --include-link-xml=C:/Program Files/Unity/Hub/Editor/2022.1.13f1/Editor/Data/PlaybackEngines/AndroidPlayer/Tools/AndroidNativeLink.xml --include-directory=D:/Workspace/AdsManager/Library/Bee/PlayerScriptAssemblies --include-directory=C:/Program Files/Unity/Hub/Editor/2022.1.13f1/Editor/Data/PlaybackEngines/AndroidPlayer/Variations/il2cpp/Managed --include-directory=D:/Workspace/AdsManager/Assets/GoogleMobileAds --include-directory=D:/Workspace/AdsManager/Library/PackageCache/com.unity.nuget.newtonsoft-json@3.0.2/Runtime/AOT --include-directory=C:/Program Files/Unity/Hub/Editor/2022.1.13f1/Editor/Data/MonoBleedingEdge/lib/mono/unityaot-linux --include-directory=C:/Program Files/Unity/Hub/Editor/2022.1.13f1/Editor/Data/MonoBleedingEdge/lib/mono/unityaot-linux/Facades --dotnetprofile=unityaot-linux --dotnetruntime=Il2Cpp --platform=Android --use-editor-options --enable-engine-module-stripping --engine-modules-asset-file=C:/Program Files/Unity/Hub/Editor/2022.1.13f1/Editor/Data/PlaybackEngines/AndroidPlayer/modules.asset --editor-data-file=D:/Workspace/AdsManager/Temp/StagingArea/Data/Managed/EditorToUnityLinkerData.json --include-unity-root-assembly=D:/Workspace/AdsManager/Library/Bee/PlayerScriptAssemblies/Assembly-CSharp.dll --include-unity-root-assembly=D:/Workspace/AdsManager/Library/Bee/PlayerScriptAssemblies/UnityEngine.UI.dll --print-command-line
**Fatal error in Unity CIL Linker
Mono.Linker.LinkerFatalErrorException: ILLink: error IL1005: GoogleMobileAds.Api.MobileAds.GetClientFactory(): Error processing method 'GoogleMobileAds.Api.MobileAds.GetClientFactory()' in assembly 'GoogleMobileAds.dll'**
 ---> System.InvalidOperationException: No action for the assembly GoogleMobileAds.Unity, Version=7.2.0.0, Culture=neutral, PublicKeyToken=null defined
   at Mono.Linker.AnnotationStore.GetAction(AssemblyDefinition assembly)
   at Mono.Linker.Steps.MarkStep.MarkCustomAttributes(ICustomAttributeProvider provider, DependencyInfo& reason, IMemberDefinition sourceLocationMember)
   at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference, DependencyInfo reason, IMemberDefinition sourceLocationMember)
   at Mono.Linker.Steps.MarkStep.MarkTypeVisibleToReflection(TypeReference reference, DependencyInfo reason, IMemberDefinition sourceLocationMember)
   at Mono.Linker.Dataflow.ReflectionMethodBodyScanner.<>c__DisplayClass20_4.<HandleCall>b__7()
   at Mono.Linker.Dataflow.ReflectionMethodBodyScanner.HandleCall(MethodBody callingMethodBody, MethodReference calledMethod, Instruction operation, ValueNodeList methodParams, ValueNode& methodReturnValue)
   at Mono.Linker.Dataflow.MethodBodyScanner.HandleCall(MethodBody callingMethodBody, Instruction operation, Stack`1 currentStack)
   at Mono.Linker.Dataflow.MethodBodyScanner.Scan(MethodBody methodBody)
   at Mono.Linker.Dataflow.ReflectionMethodBodyScanner.ScanAndProcessReturnValue(MethodBody methodBody)
   at Unity.Linker.Steps.UnityMarkStep.MarkReflectionLikeDependencies(MethodBody body, Boolean requiresReflectionMethodBodyScanner)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Unity.Linker.Steps.UnityMarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method, DependencyInfo& reason)
   at Unity.Linker.Steps.UnityMarkStep.ProcessMethod(MethodDefinition method, DependencyInfo& reason)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at Unity.Linker.Steps.UnityMarkStep.Process(LinkContext context)
   at Unity.Linker.UnityPipeline.ProcessStep(LinkContext context, IStep step)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at Unity.Linker.UnityDriver.UnityRun(Boolean noProfilerAllowed, ILogger customLogger)
   at Unity.Linker.UnityDriver.RunDriverWithoutErrorHandling(ILogger customLogger, Boolean noProfilerAllowed)
   at Unity.Linker.UnityDriver.RunDriver()
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

Error 2
BuildFailedException: Incremental Player build failed!
UnityEditor.Modules.BeeBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args) (at <7d481861b3d34328a9633ade22dcedd6>:0)
UnityEditor.Modules.DefaultBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, UnityEditor.BuildProperties& outProperties) (at <7d481861b3d34328a9633ade22dcedd6>:0)
UnityEditor.Android.AndroidBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, UnityEditor.BuildProperties& outProperties) (at <0eed393540a24b62a5632d87fed7540d>:0)
UnityEditor.PostprocessBuildPlayer.Postprocess (UnityEditor.BuildTargetGroup targetGroup, UnityEditor.BuildTarget target, System.Int32 subtarget, System.String installPath, System.String companyName, System.String productName, System.Int32 width, System.Int32 height, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <7d481861b3d34328a9633ade22dcedd6>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

Error 3
Build completed with a result of 'Failed' in 43 seconds (43340 ms)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

Error 4
UnityEditor.BuildPlayerWindow+BuildMethodException: 3 errors
  at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (UnityEditor.BuildPlayerOptions options) [0x002da] in <7d481861b3d34328a9633ade22dcedd6>:0 
  at UnityEditor.BuildPlayerWindow.CallBuildMethods (System.Boolean askForBuildLocation, UnityEditor.BuildOptions defaultBuildOptions) [0x00080] in <7d481861b3d34328a9633ade22dcedd6>:0 
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

**Comment by MuhammadWaqasOfficial** [comment]
Steps i Followed.
- Made Empty Project Of Type 2D. Import the GMA 7.2.0. Build With Success.
- Made Empty Project Of Type 3D. Import the GMA 7.2.0. Build Failed. with above mentioned error.
Adding Screenshots as well.
![AdsManager2D](https://user-images.githubusercontent.com/32755091/190638608-f6c377ee-2b20-4f16-ba3c-21ddd30e3908.png)
![AdsManager3D](https://user-images.githubusercontent.com/32755091/190638620-2917f413-0d40-45dc-8c82-a83b5873e9d0.png)

**Comment by NVentimiglia** [comment]
@MuhammadWaqasOfficial

Can you provide an upload / link to the broken project?

**Comment by MuhammadWaqasOfficial** [comment]
Not right now ( weekend holidays ). Will share on monday.
Else you can make empty 2d,3d projects in mentioned unity version which is 2022.1.3f1. nothing special you will have to do.

**Comment by MuhammadWaqasOfficial** [comment]
Projects one drive link.
https://1drv.ms/u/s!AgRgbwsA-KefiatlDDK5CtzMUD4RuA?e=7Hps4Q

There are three projects in zip file
1- AdsManager2D - Build Success
2- AdsManager3DWithOutMyAdsManager Script - Build Failed With Different Error
3- 2- AdsManager3DWithMyAdsManager Script - Build Failed With Different Error than project 2.

**Comment by NVentimiglia** [comment]
Hi @MuhammadWaqasOfficial 

I was able to load and run AdsManager3DWithAdsManagerScript without issue. Please make sure you target a mobile platform (I did Android), and Force resolve android dependencies in the Assets > External Dependency Manager.

<img width="394" alt="image" src="https://user-images.githubusercontent.com/125889/191080134-8bd209c4-aa13-4c6e-aa90-7fc0408eb5a1.png">

**Comment by MuhammadWaqasOfficial** [comment]
My target platform was android and resolved the dependency manager. (Obviously)

I just downgrade my unity version in 2021LTS. Build is fine.

**Comment by gothicserpent** [comment]
@NVentimiglia sorry to mention you, but just wanted to bring this to your attention. The same thing happened to me.

Once I downgraded from `Unity 2022.1.19f1` to `Unity 2021.3.11f1` it worked as mentioned by the original poster.

I hope someone resolves this for the `Unity 2022` builds with google mobile ads. Please keep working on this to ensure it's not there in our next versions!
