### ISSUE TITLE
Build to IOS  is failing

### ISSUE THREAD

**Issue by badrdouah** [googleads/googleads-mobile-unity#2341]
* Unity version: 2022.1.20f1
  * Google Mobile Ads Unity plugin version: 7.30
  * Platform: IOS

I can't build to IOS, everything seams to be working on the editor but when i try to build to IOS i get these 4 errors, any help is really appreciated.

<img width="1070" alt="Screen Shot 2022-10-19 at 12 43 41 PM" src="https://user-images.githubusercontent.com/23709121/196681757-f7aa716b-8f2e-499d-bbfa-dcdfb94c1570.png">

error1 :
`Building Library/Bee/artifacts/iOS/ManagedStripped failed with output:
/Applications/Unity/Hub/Editor/2022.1.20f1/Unity.app/Contents/il2cpp/build/deploy/UnityLinker --search-directory=/Users/badrdouah/Documents/GitHub/Frogger-Frog/Library/Bee/PlayerScriptAssemblies --search-directory=/Applications/Unity/Hub/Editor/2022.1.20f1/PlaybackEngines/iOSSupport/Variations/il2cpp/Managed --search-directory=/Users/badrdouah/Documents/GitHub/Frogger-Frog/Assets/NucleCloud/Plugins --search-directory=/Users/badrdouah/Documents/GitHub/Frogger-Frog/Assets/GoogleMobileAds --search-directory=/Applications/Unity/Hub/Editor/2022.1.20f1/Unity.app/Contents/MonoBleedingEdge/lib/mono/unityaot-macos --search-directory=/Applications/Unity/Hub/Editor/2022.1.20f1/Unity.app/Contents/MonoBleedingEdge/lib/mono/unityaot-macos/Facades --out=Library/Bee/artifacts/iOS/ManagedStripped --include-link-xml=/Users/badrdouah/Documents/GitHub/Frogger-Frog/Temp/StagingArea/Data/Managed/MethodsToPreserve.xml --include-link-xml=/Users/badrdouah/Documents/GitHub/Frogger-Frog/Temp/StagingArea/Data/Managed/TypesInScenes.xml --include-link-xml=/Users/badrdouah/Documents/GitHub/Frogger-Frog/Temp/StagingArea/Data/Managed/SerializedTypes.xml --include-link-xml=/Users/badrdouah/Documents/GitHub/Frogger-Frog/Assets/GoogleMobileAds/link.xml --include-link-xml=/Applications/Unity/Hub/Editor/2022.1.20f1/PlaybackEngines/iOSSupport/il2cpp/ios_il2cpp_link.xml --include-directory=/Users/badrdouah/Documents/GitHub/Frogger-Frog/Library/Bee/PlayerScriptAssemblies --include-directory=/Applications/Unity/Hub/Editor/2022.1.20f1/PlaybackEngines/iOSSupport/Variations/il2cpp/Managed --include-directory=/Users/badrdouah/Documents/GitHub/Frogger-Frog/Assets/NucleCloud/Plugins --include-directory=/Users/badrdouah/Documents/GitHub/Frogger-Frog/Assets/GoogleMobileAds --include-directory=/Applications/Unity/Hub/Editor/2022.1.20f1/Unity.app/Contents/MonoBleedingEdge/lib/mono/unityaot-macos --include-directory=/Applications/Unity/Hub/Editor/2022.1.20f1/Unity.app/Contents/MonoBleedingEdge/lib/mono/unityaot-macos/Facades --dotnetprofile=unityaot-macos --dotnetruntime=Il2Cpp --architecture=x64 --platform=iOS --use-editor-options --engine-modules-asset-file=/Applications/Unity/Hub/Editor/2022.1.20f1/PlaybackEngines/iOSSupport/modules.asset --editor-data-file=/Users/badrdouah/Documents/GitHub/Frogger-Frog/Temp/StagingArea/Data/Managed/EditorToUnityLinkerData.json --include-unity-root-assembly=/Users/badrdouah/Documents/GitHub/Frogger-Frog/Library/Bee/PlayerScriptAssemblies/Assembly-CSharp.dll --include-unity-root-assembly=/Users/badrdouah/Documents/GitHub/Frogger-Frog/Library/Bee/PlayerScriptAssemblies/UnityEngine.UI.dll --print-command-line
Fatal error in Unity CIL Linker
Mono.Linker.LinkerFatalErrorException: ILLink: error IL1005: GoogleMobileAds.Api.MobileAds.GetClientFactory(): Error processing method 'GoogleMobileAds.Api.MobileAds.GetClientFactory()' in assembly 'GoogleMobileAds.dll'
 ---> System.InvalidOperationException: No action for the assembly GoogleMobileAds.Unity, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null defined
   at Mono.Linker.AnnotationStore.GetAction(AssemblyDefinition assembly) in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker/Annotations.cs:line 112
   at Mono.Linker.Steps.MarkStep.MarkCustomAttributes(ICustomAttributeProvider provider, DependencyInfo& reason, IMemberDefinition sourceLocationMember) in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker.Steps/MarkStep.cs:line 574
   at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference, DependencyInfo reason, IMemberDefinition sourceLocationMember) in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker.Steps/MarkStep.cs:line 1446
   at Mono.Linker.Steps.MarkStep.MarkTypeVisibleToReflection(TypeReference reference, DependencyInfo reason, IMemberDefinition sourceLocationMember) in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker.Steps/MarkStep.cs:line 1371
   at Mono.Linker.Dataflow.ReflectionMethodBodyScanner.<>c__DisplayClass20_4.<HandleCall>b__7() in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs:line 810
   at Mono.Linker.Dataflow.ReflectionMethodBodyScanner.HandleCall(MethodBody callingMethodBody, MethodReference calledMethod, Instruction operation, ValueNodeList methodParams, ValueNode& methodReturnValue) in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs:line 810
   at Mono.Linker.Dataflow.MethodBodyScanner.HandleCall(MethodBody callingMethodBody, Instruction operation, Stack`1 currentStack) in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker.Dataflow/MethodBodyScanner.cs:line 859
   at Mono.Linker.Dataflow.MethodBodyScanner.Scan(MethodBody methodBody) in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker.Dataflow/MethodBodyScanner.cs:line 530
   at Mono.Linker.Dataflow.ReflectionMethodBodyScanner.ScanAndProcessReturnValue(MethodBody methodBody) in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs:line 69
   at Unity.Linker.Steps.UnityMarkStep.MarkReflectionLikeDependencies(MethodBody body, Boolean requiresReflectionMethodBodyScanner) in /Users/bokken/build/output/unity/il2cpp/UnityLinker/Linker.Steps/UnityMarkStep.cs:line 351
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body) in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker.Steps/MarkStep.cs:line 2807
   at Unity.Linker.Steps.UnityMarkStep.MarkMethodBody(MethodBody body) in /Users/bokken/build/output/unity/il2cpp/UnityLinker/Linker.Steps/UnityMarkStep.cs:line 356
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method, DependencyInfo& reason) in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker.Steps/MarkStep.cs:line 2430
   at Unity.Linker.Steps.UnityMarkStep.ProcessMethod(MethodDefinition method, DependencyInfo& reason) in /Users/bokken/build/output/unity/il2cpp/UnityLinker/Linker.Steps/UnityMarkStep.cs:line 222
   at Mono.Linker.Steps.MarkStep.ProcessQueue() in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker.Steps/MarkStep.cs:line 391
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue() in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker.Steps/MarkStep.cs:line 393
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue() in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker.Steps/MarkStep.cs:line 376
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context) in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker.Steps/MarkStep.cs:line 187
   at Unity.Linker.Steps.UnityMarkStep.Process(LinkContext context) in /Users/bokken/build/output/unity/il2cpp/UnityLinker/Linker.Steps/UnityMarkStep.cs:line 255
   at Unity.Linker.UnityPipeline.ProcessStep(LinkContext context, IStep step) in /Users/bokken/build/output/unity/il2cpp/UnityLinker/Linker/UnityPipeline.cs:line 23
   at Mono.Linker.Pipeline.Process(LinkContext context) in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker/Pipeline.cs:line 128
   at Unity.Linker.UnityDriver.UnityRun(Boolean noProfilerAllowed, ILogger customLogger) in /Users/bokken/build/output/unity/il2cpp/UnityLinker/Linker/UnityDriver.cs:line 124
   at Unity.Linker.UnityDriver.RunDriverWithoutErrorHandling(ILogger customLogger, Boolean noProfilerAllowed) in /Users/bokken/build/output/unity/il2cpp/UnityLinker/Linker/UnityDriver.cs:line 80
   at Unity.Linker.UnityDriver.RunDriver() in /Users/bokken/build/output/unity/il2cpp/UnityLinker/Linker/UnityDriver.cs:line 61
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun () (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPlayerWindow.cs:188)`

Error 2
`BuildFailedException: Incremental Player build failed!
UnityEditor.Modules.BeeBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args) (at /Users/bokken/buildslave/unity/build/Editor/Mono/Modules/BeeBuildPostprocessor.cs:634)
UnityEditor.iOS.iOSBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args) (at /Users/bokken/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/iOSBuildPostprocessor.cs:508)
Rethrow as BuildFailedException: Exception of type 'UnityEditor.Build.BuildFailedException' was thrown.
UnityEditor.iOS.iOSBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args) (at /Users/bokken/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/iOSBuildPostprocessor.cs:515)
UnityEditor.Modules.DefaultBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, UnityEditor.BuildProperties& outProperties) (at /Users/bokken/buildslave/unity/build/Editor/Mono/Modules/DefaultBuildPostprocessor.cs:28)
UnityEditor.PostprocessBuildPlayer.Postprocess (UnityEditor.BuildTargetGroup targetGroup, UnityEditor.BuildTarget target, System.Int32 subtarget, System.String installPath, System.String companyName, System.String productName, System.Int32 width, System.Int32 height, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/PostprocessBuildPlayer.cs:370)
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun() (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPlayerWindow.cs:188)`

Error3
`Build completed with a result of 'Failed' in 4 seconds (4109 ms)
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun () (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPlayerWindow.cs:188)`

Error4
`UnityEditor.BuildPlayerWindow+BuildMethodException: 3 errors
  at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (UnityEditor.BuildPlayerOptions options) [0x002ce] in /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPlayerWindowBuildMethods.cs:193 
  at UnityEditor.BuildPlayerWindow.CallBuildMethods (System.Boolean askForBuildLocation, UnityEditor.BuildOptions defaultBuildOptions) [0x00080] in /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPlayerWindowBuildMethods.cs:94 
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun () (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPlayerWindow.cs:188)
`

**Comment by NVentimiglia** [comment]
Hi @badrdouah 

ManagedStripped failed could be many things, some of which are not related to AdMob. Can you reproduce the problem with a minimal sample application? If so link an upload with your environment configuration and I will take a look.

**Comment by badrdouah** [comment]
> Hi @badrdouah
> 
> ManagedStripped failed could be many things, some of which are not related to AdMob. Can you reproduce the problem with a minimal sample application? If so link an upload with your environment configuration and I will take a look.

I ended up using another Unity version which does not have this issue, 
thanx for your reply,
