### ISSUE TITLE
"Couldn't create RTB adapter" exception when integrating Meta Audience Network with bidding

### ISSUE THREAD

**Issue by spikyworm5** [googleads/googleads-mobile-unity#2456]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.3.15f1
  * Google Mobile Ads Unity plugin version: 7.2.0, 7.3.1
  * Platform: Android
  * Platform OS version: Android 12
  * Any specific devices issue occurs on: Xiaomi Redmi Note 9S
  * Mediation ad networks used, and their versions: Meta Audience Network 3.9.0

### [REQUIRED] Step 2: Describe the problem

After integrating the "Meta Audience Network" package (following this [link](https://developers.google.com/admob/unity/mediation/meta)) I get the following error in the log and the ad inspector indicates that the SDK failed to initialize (SDK issue):
```
2022/12/15 14:43:20.379 18930 19273 Error Ads Couldn't create RTB adapter : 
2022/12/15 14:43:20.379 18930 19273 Error Ads android.os.RemoteException
2022/12/15 14:43:20.379 18930 19273 Error Ads 	at com.google.android.gms.internal.ads.zzbvn.zzc(com.google.android.gms:play-services-ads-lite@@21.4.0:4)
2022/12/15 14:43:20.379 18930 19273 Error Ads 	at com.google.android.gms.internal.ads.zzbvp.zzbK(com.google.android.gms:play-services-ads-lite@@21.4.0:8)
2022/12/15 14:43:20.379 18930 19273 Error Ads 	at com.google.android.gms.internal.ads.zzase.onTransact(com.google.android.gms:play-services-ads-base@@21.4.0:3)
2022/12/15 14:43:20.379 18930 19273 Error Ads 	at android.os.Binder.transact(Binder.java:1064)
2022/12/15 14:43:20.379 18930 19273 Error Ads 	at afj.bd(:com.google.android.gms.policy_ads_fdr_dynamite@224400003@224400003057.484457631.484457631:2)
2022/12/15 14:43:20.379 18930 19273 Error Ads 	at com.google.android.gms.ads.internal.mediation.client.b.c(:com.google.android.gms.policy_ads_fdr_dynamite@224400003@224400003057.484457631.484457631:1)
2022/12/15 14:43:20.379 18930 19273 Error Ads 	at com.google.android.gms.ads.nonagon.adapter.e.b(:com.google.android.gms.policy_ads_fdr_dynamite@224400003@224400003057.484457631.484457631:1)
2022/12/15 14:43:20.379 18930 19273 Error Ads 	at com.google.android.gms.ads.nonagon.signals.ei.a(:com.google.android.gms.policy_ads_fdr_dynamite@224400003@224400003057.484457631.484457631:3)
2022/12/15 14:43:20.379 18930 19273 Error Ads 	at brk.a(:com.google.android.gms.policy_ads_fdr_dynamite@224400003@224400003057.484457631.484457631:2)
2022/12/15 14:43:20.379 18930 19273 Error Ads 	at bqt.run(:com.google.android.gms.policy_ads_fdr_dynamite@224400003@224400003057.484457631.484457631:3)
2022/12/15 14:43:20.379 18930 19273 Error Ads 	at brm.run(:com.google.android.gms.policy_ads_fdr_dynamite@224400003@224400003057.484457631.484457631:0)
2022/12/15 14:43:20.379 18930 19273 Error Ads 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
2022/12/15 14:43:20.379 18930 19273 Error Ads 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
2022/12/15 14:43:20.379 18930 19273 Error Ads 	at java.lang.Thread.run(Thread.java:1012)
```

This is what I see in ad inspector:
![Screenshot_2022-12-15-14-59-03-708-edit_com purefunlab bagman](https://user-images.githubusercontent.com/69602124/207865283-83f5dd87-ed4a-439b-bce5-3aa54757e5a4.jpg)

#### Steps to reproduce:

Install the latest AdMob SDK 7.3.1 with the latest Meta Audience Network 3.9.0 and try to load an ad, either interstitial or reward. AdMob ads are loaded fine but Facebook/Meta ads are not shown and ad inspector shows that the SDK failed to load as shown above.

**Comment by spikyworm5** [comment]
Sorry. I somehow got to install the [audience SDK](https://developers.facebook.com/docs/audience-network/setting-up/platform-steup/unity/add-sdk/) instead of the mediation SDK from [here](https://dl.google.com/googleadmobadssdk/mediation/unity/meta/MetaAudienceNetworkUnityAdapter-3.9.0.zip)... Trying again. Will update with the result.

**Comment by spikyworm5** [comment]
Issue resolve. My bad. Closing the ticket.
