### ISSUE TITLE
ClassNotFoundException by export Android Studio Project 

### ISSUE THREAD

**Issue by hananana** [googleads/googleads-mobile-unity#249]
Hi. I'm in troble in serious.
i just create empty unity project. and setup admob as a developer guide.
then, File>Build Setting>(check Google Android Project)>Export.
but my pretty AndroidStudio said this error.

```
4:22:07.866 11820-11844/? I/Unity: AndroidJavaException: java.lang.ClassNotFoundException: com.google.unity.ads.UnityBannerAdListener
                                          java.lang.ClassNotFoundException: com.google.unity.ads.UnityBannerAdListener
                                              at java.lang.Class.classForName(Native Method)
                                              at java.lang.Class.forName(Class.java:251)
                                              at java.lang.Class.forName(Class.java:216)
                                              at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
                                              at com.unity3d.player.UnityPlayer.a(Unknown Source)
                                              at com.unity3d.player.UnityPlayer$b.run(Unknown Source)
                                           Caused by: java.lang.NoClassDefFoundError: com/google/unity/ads/UnityBannerAdListener
                                              at java.lang.Class.classForName(Native Method) 
                                              at java.lang.Class.forName(Class.java:251) 
                                              at java.lang.Class.forName(Class.java:216) 
                                              at com.unity3d.player.UnityPlayer.nativeRender(Native Method) 
                                              at com.unity3d.player.UnityPlayer.a(Unknown Source) 
                                              at com.unity3d.player.UnityPlayer$b.run(Unknown Source) 
                                           Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.unity.ads.UnityBannerAdListener" on path: DexPathList[[zip file "/data/app/com.AdTest-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.AdTest-2, /vendor/lib, /system/lib]]
                                              at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
```

Please help me.

**Comment by rampara** [comment]
The `com.google.unity.ads.UnityBannerAdListener` class should be found within the `unity-plugin-library.jar` file. Is your Android Studio project set up correctly to include this file? Are you able to build and run successfully if you let Unity build an APK instead of exporting to an Android Studio project?

**Comment by hananana** [comment]
THX reply.
my project has `unity-plugin-library.jar` definitely.
this library's path is `/project-root/GoogleMobileAdsPlugin/libs/unity-plugin-library.jar`.
and descript about this library in project.properties.

In UnityBuildAndRun. It's chaos.
All of inactive GameObject is active. 
Nothing happen if I tap buttons.
Maybe initialization of scene stop. Because of Admob's BannerView.

**Comment by rampara** [comment]
Are you running into issues when trying to run the [sample application](https://github.com/googleads/googleads-mobile-unity/tree/master/samples/HelloWorld) from this repository?

**Comment by rampara** [comment]
Closing this issue to due it's age and non-response. Please re-open if this issue persists for you.
