### ISSUE TITLE
Build IOS failed Google Mobile Ads Unity 7.4.1 Fatal error in Unity CIL Linker

### ISSUE THREAD

**Issue by jacattrongnlh** [googleads/googleads-mobile-unity#2585]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2022.1.20
  * Google Mobile Ads Unity plugin version: 7.4.1
  * Platform: IOS
  * Platform OS version: IOS 15
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: _____

### [REQUIRED] Step 2: Describe the problem

In Unity, Building Xcode project failed, the console logs the folllowing error:
```
Building Library/Bee/artifacts/iOS/ManagedStripped failed with output:
/Applications/Unity/Hub/Editor/2022.1.20f1/Unity.app/Contents/il2cpp/build/deploy/UnityLinker @Library/Bee/artifacts/rsp/948155647842844753.rsp
Fatal error in Unity CIL Linker
Mono.Linker.LinkerFatalErrorException: ILLink: error IL1005: GoogleMobileAds.Api.MobileAds.GetClientFactory(): Error processing method 'GoogleMobileAds.Api.MobileAds.GetClientFactory()' in assembly 'GoogleMobileAds.dll'
 ---> System.InvalidOperationException: No action for the assembly GoogleMobileAds.Unity, Version=7.4.1.0, Culture=neutral, PublicKeyToken=null defined
   at Mono.Linker.AnnotationStore.GetAction(AssemblyDefinition assembly) in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker/Annotations.cs:line 112
   at Mono.Linker.Steps.MarkStep.MarkCustomAttributes(ICustomAttributeProvider provider, DependencyInfo& reason, IMemberDefinition sourceLocationMember) in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker.Steps/MarkStep.cs:line 574
   at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference, DependencyInfo reason, IMemberDefinition sourceLocationMember) in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker.Steps/MarkStep.cs:line 1446
   at Mono.Linker.Steps.MarkStep.MarkTypeVisibleToReflection(TypeReference reference, DependencyInfo reason, IMemberDefinition sourceLocationMember) in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker.Steps/MarkStep.cs:line 1371
   at Mono.Linker.Dataflow.ReflectionMethodBodyScanner.<>c__DisplayClass20_4.<HandleCall>b__7() in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs:line 810
   at Mono.Linker.Dataflow.ReflectionMethodBodyScanner.HandleCall(MethodBody callingMethodBody, MethodReference calledMethod, Instruction operation, ValueNodeList methodParams, ValueNode& methodReturnValue) in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs:line 810
   at Mono.Linker.Dataflow.MethodBodyScanner.HandleCall(MethodBody callingMethodBody, Instruction operation, Stack`1 currentStack) in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker.Dataflow/MethodBodyScanner.cs:line 859
   at Mono.Linker.Dataflow.MethodBodyScanner.Scan(MethodBody methodBody) in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker.Dataflow/MethodBodyScanner.cs:line 530
   at Mono.Linker.Dataflow.ReflectionMethodBodyScanner.ScanAndProcessReturnValue(MethodBody methodBody) in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs:line 69
   at Unity.Linker.Steps.UnityMarkStep.MarkReflectionLikeDependencies(MethodBody body, Boolean requiresReflectionMethodBodyScanner) in /Users/bokken/build/output/unity/il2cpp/UnityLinker/Linker.Steps/UnityMarkStep.cs:line 351
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body) in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker.Steps/MarkStep.cs:line 2807
   at Unity.Linker.Steps.UnityMarkStep.MarkMethodBody(MethodBody body) in /Users/bokken/build/output/unity/il2cpp/UnityLinker/Linker.Steps/UnityMarkStep.cs:line 356
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method, DependencyInfo& reason) in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker.Steps/MarkStep.cs:line 2430
   at Unity.Linker.Steps.UnityMarkStep.ProcessMethod(MethodDefinition method, DependencyInfo& reason) in /Users/bokken/build/output/unity/il2cpp/UnityLinker/Linker.Steps/UnityMarkStep.cs:line 222
   at Mono.Linker.Steps.MarkStep.ProcessQueue() in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker.Steps/MarkStep.cs:line 391
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue() in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker.Steps/MarkStep.cs:line 393
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue() in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker.Steps/MarkStep.cs:line 376
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context) in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker.Steps/MarkStep.cs:line 187
   at Unity.Linker.Steps.UnityMarkStep.Process(LinkContext context) in /Users/bokken/build/output/unity/il2cpp/UnityLinker/Linker.Steps/UnityMarkStep.cs:line 255
   at Unity.Linker.UnityPipeline.ProcessStep(LinkContext context, IStep step) in /Users/bokken/build/output/unity/il2cpp/UnityLinker/Linker/UnityPipeline.cs:line 23
   at Mono.Linker.Pipeline.Process(LinkContext context) in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker/Pipeline.cs:line 128
   at Unity.Linker.UnityDriver.UnityRun(Boolean noProfilerAllowed, ILogger customLogger) in /Users/bokken/build/output/unity/il2cpp/UnityLinker/Linker/UnityDriver.cs:line 124
   at Unity.Linker.UnityDriver.RunDriverWithoutErrorHandling(ILogger customLogger, Boolean noProfilerAllowed) in /Users/bokken/build/output/unity/il2cpp/UnityLinker/Linker/UnityDriver.cs:line 80
   at Unity.Linker.UnityDriver.RunDriver() in /Users/bokken/build/output/unity/il2cpp/UnityLinker/Linker/UnityDriver.cs:line 61
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&) (at /Users/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:189)
```

I have used Google Mobile Ads Unity 7.3.1, built Xcode project successfully, but I ran into [this error](https://github.com/googleads/googleads-mobile-unity/issues/2531), so I updated to Google Mobile Ads Unity 7.4.1.

**Comment by jacattrongnlh** [comment]
I tried using Google Mobile Ads Unity 7.3.0, still run into the same error. Then I update Unity to Unity 2022.2.11 and it built XCode project successfully, XCode build to device with no error. Haven't tried updating to Google Ad Unity 7.4.1 yet.

**Comment by NVentimiglia** [comment]
@jacattrongnlh 

Thanks for the heads up. We see this issue and will take corrective measures. Glad you found a work around. Please feel free to reply again if you run into additional issues.
