### ISSUE TITLE
Play Services Resolver is not importing AAR files for analytics automatically neither by using "Resolve Client Jars"

### ISSUE THREAD

**Issue by Riddhesh** [googleads/googleads-mobile-unity#271]
I am using v3.0.5 currently, when i import AdMob v3.0.5 And Analytics v4, Play Services Resolver imports many .aar files but following two are not imported automatically

play-services-analytics-9.4.0.aar
play-services-analytics-impl-9.4.0.aar

I have to put them manually in my project.

(Happens the same with AdMob v3.0.6. I manually have to put these two .aar files in my project)

After this it works fine in my device. Ad & GA both looks working good. But when i publish the game, every 300th session crashes with following error

java.lang.Error: FATAL EXCEPTION [main]
Unity version     : 5.3.3f1
Device model      : HTC HTC Desire 828 dual sim
Device fingerprint: htc/a51bml_dwgl_00720/htc_a51bml_dwgl:5.1/LMY47D/711615.4:user/release-keys
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/util/SimpleArrayMap;
    at com.google.android.gms.ads.internal.zzq.<init>(Unknown Source)
    at com.google.android.gms.ads.internal.zzq.<init>(Unknown Source)
    at com.google.android.gms.ads.internal.zzb.<init>(Unknown Source)
    at com.google.android.gms.ads.internal.zzc.<init>(Unknown Source)
    at com.google.android.gms.ads.internal.zzk.<init>(Unknown Source)
    at com.google.android.gms.ads.internal.client.zze.zzb(Unknown Source)
    at com.google.android.gms.ads.internal.client.zzaa.zzM(Unknown Source)
    at com.google.android.gms.ads.internal.client.zzaa.zza(Unknown Source)
    at com.google.android.gms.ads.InterstitialAd.loadAd(Unknown Source)
    at com.google.unity.ads.Interstitial$2.run(Interstitial.java:108)
    at android.os.Handler.handleCallback(Handler.java:815)
    at android.os.Handler.dispatchMessage(Handler.java:104)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:6102)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.util.SimpleArrayMap" on path: DexPathList[[zip file "/data/app/com.world3dgames.riversand.excavator-1/base.apk"],nativeLibraryDirectories=[/data/app/com.world3dgames.riversand.excavator-1/lib/arm, /vendor/lib, /system/lib]]
    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
    ... 18 more
    Suppressed: java.lang.ClassNotFoundException: android.support.v4.util.SimpleArrayMap
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        ... 19 more
Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

Crash Report :

![prtscr capture_117](https://cloud.githubusercontent.com/assets/11594504/18540012/46f538b2-7b39-11e6-885a-6ff12f9bec6a.jpg)

I tried to find the issue related to this but none of them worked for me. I see almost 30-40 crash every day. I tested the build in almost 4 devices but i could not see any crash here. May be some specific devices are crashing..

If i put android-support-v4.jar inside Assets\Plugin\Android folder, it throws exception while making a build said "Command Invocation Failure"

I have used following libraries in my Android SDK, may be i am missing any package??

![prtscr capture](https://cloud.githubusercontent.com/assets/11594504/18539945/b48079d8-7b38-11e6-813b-ed6a8b842f31.jpg)

![prtscr capture_2](https://cloud.githubusercontent.com/assets/11594504/18539950/c1203926-7b38-11e6-8350-14f9d9996a6a.jpg)

**Comment by rampara** [comment]
Which dependencies are you declaring for resolution via the JarResolver library? The stack trace you posted seems to indicate the v4 support library is missing. Is this library included in your Unity project?

**Comment by rampara** [comment]
Closing due to age of issue. Please reopen if this issue persists for you.
