### ISSUE TITLE
Caused by java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by a314266177** [googleads/googleads-mobile-unity#2803]
Caused by java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start(Thread.java:883)
       at kk.<init>(:com.google.android.gms.policy_ads_fdr_dynamite@231710101@231710100057.526733554.526733554:11)
       at kb.<init>(:com.google.android.gms.policy_ads_fdr_dynamite@231710101@231710100057.526733554.526733554:35)
       at lm.<init>(:com.google.android.gms.policy_ads_fdr_dynamite@231710101@231710100057.526733554.526733554:2)
       at com.google.android.gms.ads.internal.video.v.<init>(:com.google.android.gms.policy_ads_fdr_dynamite@231710101@231710100057.526733554.526733554:11)
       at com.google.android.gms.ads.internal.video.gmsg.exoplayer.e.<init>(:com.google.android.gms.policy_ads_fdr_dynamite@231710101@231710100057.526733554.526733554:3)
       at com.google.android.gms.ads.internal.video.gmsg.r.a(:com.google.android.gms.policy_ads_fdr_dynamite@231710101@231710100057.526733554.526733554:27)
       at com.google.android.gms.ads.internal.webview.q.t(:com.google.android.gms.policy_ads_fdr_dynamite@231710101@231710100057.526733554.526733554:4)
       at com.google.android.gms.ads.internal.webview.q.e(:com.google.android.gms.policy_ads_fdr_dynamite@231710101@231710100057.526733554.526733554:8)
       at com.google.android.gms.ads.internal.webview.ah.run(:com.google.android.gms.policy_ads_fdr_dynamite@231710101@231710100057.526733554.526733554:4)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at atm.a(:com.google.android.gms.policy_ads_fdr_dynamite@231710101@231710100057.526733554.526733554)
       at com.google.android.gms.ads.internal.util.f.a(:com.google.android.gms.policy_ads_fdr_dynamite@231710101@231710100057.526733554.526733554:1)
       at atm.dispatchMessage(:com.google.android.gms.policy_ads_fdr_dynamite@231710101@231710100057.526733554.526733554)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7386)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:982)
<img width="1186" alt="image" src="https://github.com/googleads/googleads-mobile-unity/assets/18459275/aaef47c6-aa6c-46fc-96a8-215e492afda7">
Several projects that received admob ads had this problem, and I hope it can be fixed

**Comment by NVentimiglia** [comment]
@a314266177 

This is an SDK issue, can you submit this issue to the [help forum](https://groups.google.com/g/google-admob-ads-sdk). Please include:

- The debug stack trace as text
- Any other logging
- your app id and ad unit ids for the apps
- Any other implementation details such as sdk version used
