### ISSUE TITLE
Unity plugin too many ANR's for ex.: com.unity3d.services.ads.adunit.VideoPlayerHandler.destroy

### ISSUE THREAD

**Issue by shefich** [googleads/googleads-mobile-unity#2819]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2020.3.48, 47, 46... 2021.3.27,26,...
  * Google Mobile Ads Unity plugin version: 8.3.0, 8.2.0, ...
  * Platform: Android
  * Platform OS version: Android 13, 12, 11...
  * Any specific devices issue occurs on: All devices
  * Mediation ad networks used, and their versions: AppLovin, IronSource, Unity

#### Steps to reproduce:

As I see in the logs the issue occurs after showing rewarded or interstitial ads.
This is stacktrace with at least some readable code (com.unity3d.services.ads.adunit.VideoPlayerHandler.destroy), but there are too many ANRs which only have the same time stamps and all of them happen after showing/closing interstitial/rewarded ads, also they happens on all Android OSs staring with Android 5. 

#### Relevant Code:
Stacktrace here:
```
main (native):tid=1 systid=16750 
#00 pc 0xa04c4 libc.so (__ioctl + 4)
#01 pc 0x5ae4c libc.so (ioctl + 156)
#02 pc 0x45ae4 libbinder.so (android::IPCThreadState::talkWithDriver(bool) + 292)
#03 pc 0x46d00 libbinder.so (android::IPCThreadState::waitForResponse(android::Parcel*, int*) + 128)
#04 pc 0x46a08 libbinder.so (android::IPCThreadState::transact(int, unsigned int, android::Parcel const&, android::Parcel*, unsigned int) + 216)
#05 pc 0x3e950 libbinder.so (android::BpBinder::transact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int) + 192)
#06 pc 0x5d498 libmedia.so (android::BpMediaPlayer::disconnect() + 280)
#07 pc 0x4b9cc libmedia.so (android::MediaPlayer::disconnect() + 276)
#08 pc 0x72c08 libmedia_jni.so (android_media_MediaPlayer_release(_JNIEnv*, _jobject*) + 152)
       at android.media.MediaPlayer._release(Native method)
       at android.media.MediaPlayer.release(MediaPlayer.java:2433)
       at android.widget.VideoView.stopPlayback(VideoView.java:365)
       at com.unity3d.services.ads.adunit.VideoPlayerHandler.destroy(VideoPlayerHandler.java:38)
       at com.unity3d.services.ads.adunit.AdUnitActivity.setViews(AdUnitActivity.java:382)
       at com.unity3d.services.ads.api.AdUnit$1.run(AdUnit.java:171)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8663)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

**Comment by NVentimiglia** [comment]
Hi @shefich 

Can you raise this issue with the SDK team on the [google forum](https://groups.google.com/g/google-admob-ads-sdk). They are better suited at understanding and fixing these issues from deep within the SDK.
