### ISSUE TITLE
Crash on Xiaomi Caused by java.lang.NullPointerException

### ISSUE THREAD

**Issue by MuhammadWaqasOfficial** [googleads/googleads-mobile-unity#2823]
* Unity version: Not Related
  * Google Mobile Ads Unity plugin version: 8.2.0
  * Platform: Android
  * Any specific devices issue occurs on: Xiaomi

Step 2: Describe the problem
on firebase crashlytics dashboard i am seeing this crash. not sure its related to admob or not. But it is few lines related to com.google.android.gms.ads. Please discard if not related to admob.

# Crashlytics - Stack trace

Fatal Exception: java.lang.Error: FATAL EXCEPTION [AdWorker(Default) # 16]
Unity version     : 2021.3.23f1
Device model      : Xiaomi M2103K19I
Device fingerprint: Redmi/camellia_in/camellia:12/SP1A.210812.016/V13.0.7.0.SKSINXM:user/release-keys
Build Type        : Release
Scripting Backend : IL2CPP
ABI               : arm64-v8a
Strip Engine Code : true

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int android.os.Bundle.size()' on a null object reference
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2432)
       at android.os.Parcel.createException(Parcel.java:2410)
       at android.os.Parcel.readException(Parcel.java:2393)
       at android.os.Parcel.readException(Parcel.java:2335)
       at android.view.IWindowManager$Stub$Proxy.getSupportedDisplayHashAlgorithms(IWindowManager.java:6126)
       at android.view.displayhash.DisplayHashManager.getSupportedHashAlgorithms(DisplayHashManager.java:71)
       at com.google.android.gms.ads.eventattestation.internal.l.<init>(:com.google.android.gms.policy_ads_fdr_dynamite@231710101@231710100057.526733554.526733554:2)
       at com.google.android.gms.ads.nonagon.ad.j.e(:com.google.android.gms.policy_ads_fdr_dynamite@231710101@231710100057.526733554.526733554:11)
       at com.google.android.gms.ads.nonagon.ad.g.run(:com.google.android.gms.policy_ads_fdr_dynamite@231710101@231710100057.526733554.526733554)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)

Complete Stack Trace is attached.
[crash.txt](https://github.com/googleads/googleads-mobile-unity/files/12051270/crash.txt)

**Comment by NVentimiglia** [comment]
Thanks @MuhammadWaqasOfficial 

I will forward this bug report to the Android team, and they will take a look.

**Comment by warut** [comment]
Any quick fix?  I got many apps crash with same stack trace e.g. investing, file manager(yeah built in app), es file manager, soundwire .  Redmi 9 lancelot, miui 13.0.2.  No update for Miui 14.  Do i really need to downgrade to miui 12?
