### ISSUE TITLE
[v8.5.0] java.lang.NoSuchMethodError: ConsentInformation.PrivacyOptionsRequirementStatus

### ISSUE THREAD

**Issue by Nyankoo** [googleads/googleads-mobile-unity#2866]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.3.28f1
  * Google Mobile Ads Unity plugin version: 8.5.0
  * Platform: Android

#### Steps to reproduce:

When calling `ConsentInformation.PrivacyOptionsRequirementStatus`, the exception below is thrown.

#### Relevant Code:

```
AndroidJavaException: java.lang.NoSuchMethodError: no non-static method with name='getPrivacyOptionsRequirementStatus' signature='()I' in class Ljava.lang.Object;
java.lang.NoSuchMethodError: no non-static method with name='getPrivacyOptionsRequirementStatus' signature='()I' in class Ljava.lang.Object;
at com.unity3d.player.ReflectionHelper.getMethodID(Unknown Source:162)
at com.unity3d.player.ReflectionHelper.nativeProxyInvoke(Native Method)
at com.unity3d.player.ReflectionHelper.a(Unknown Source:0)
at com.unity3d.player.ReflectionHelper$1.invoke(Unknown Source:29)
at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
at $Proxy17.onConsentInfoUpdateSuccess(Unknown Source)
at com.google.android.gms.internal.consent_sdk.zzt.run(Unknown Source:2)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7397)
at java.lang.reflect.Method.invoke(Native Me
```

**Comment by NVentimiglia** [comment]
Hi @Nyankoo 

I was not able to replicate this problem. It is possible this is due to a dependency version missmatch. Can you verify that you are using `com.google.android.ump.user-messaging-platform-2.1.0`

**Comment by Nyankoo** [comment]
@NVentimiglia Yes, my gradle file in Unity has the following:
`implementation 'com.google.android.ump:user-messaging-platform:2.1.0'`

**Comment by NVentimiglia** [comment]
@Nyankoo 

I have replicated the issue and we are looking into getting a fix out ASAP.

**Comment by hypocriticism1** [comment]
I solved similar error

'java.lang.NoSuchMethodError: ConsentInformation.GetConsentInformation'

by adding below code to proguard:
```
-keep class com.google.android.ump.** {
   public *
}
```

**Comment by usamanawaz789** [comment]
Any Update on this?
