### ISSUE TITLE
Unity Application Crash at startup java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: 

### ISSUE THREAD

**Issue by reezoobose** [googleads/googleads-mobile-unity#2912]
* Unity version: 2022.3.7f1
  * Google Mobile Ads Unity plugin version: 8.5.2
  * Platform:  Android, Unity Editor
  * Platform OS version: Min Android 5.1 
  * Any specific device issue occurs on: NO
  * Mediation ad networks used, and their versions: Google, Unity

 Problem Description: The application crashes at the start.
 

Unity Crash after updating the Google ADMOB plugin to the current version.

```
FATAL EXCEPTION: main
                                                                                                    Process: com.weplay.motogp, PID: 7370
                                                                                                    java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: java.lang.ClassNotFoundException: androidx.lifecycle.ProcessLifecycleInitializer
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:8225)
                                                                                                    	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7728)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7482)
                                                                                                    	at android.app.ActivityThread.access$1600(ActivityThread.java:310)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2281)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8663)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
                                                                                                    Caused by: androidx.startup.StartupException: java.lang.ClassNotFoundException: androidx.lifecycle.ProcessLifecycleInitializer
                                                                                                    	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:204)
                                                                                                    	at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:42)
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2516)
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2486)
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:8220)
                                                                                                    	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7728) 
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7482) 
                                                                                                    	at android.app.ActivityThread.access$1600(ActivityThread.java:310) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2281) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226) 
                                                                                                    	at android.os.Looper.loop(Looper.java:313) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8663) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135) 
                                                                                                    Caused by: java.lang.ClassNotFoundException: androidx.lifecycle.ProcessLifecycleInitializer
                                                                                                    	at java.lang.Class.classForName(Native Method)
                                                                                                    	at java.lang.Class.forName(Class.java:454)
                                                                                                    	at java.lang.Class.forName(Class.java:379)
                                                                                                    	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:190)
                                                                                                    	at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:42) 
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2516) 
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2486) 
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:8220) 
                                                                                                    	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7728) 
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7482) 
                                                                                                    	at android.app.ActivityThread.access$1600(ActivityThread.java:310) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2281) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226) 
                                                                                                    	at android.os.Looper.loop(Looper.java:313) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8663) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135) 
                                                                                                    Caused by: java.lang.ClassNotFoundException: androidx.lifecycle.ProcessLifecycleInitializer
                                                                                                    	at java.lang.Class.classForName(Native Method) 
                                                                                                    	at java.lang.Class.forName(Class.java:454) 
                                                                                                    	at java.lang.Class.forName(Class.java:379) 
                                                                                                    	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:190) 
                                                                                                    	at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:42) 
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2516) 
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2486) 
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:8220) 
                                                                                                    	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7728) 
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7482) 
                                                                                                    	at android.app.ActivityThread.access$1600(ActivityThread.java:310) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2281) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226) 
                                                                                                    	at android.os.Looper.loop(Looper.java:313) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8663) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135) 
```

**Comment by NVentimiglia** [comment]
Please modify your `GoogleMobileAdsDependencies.xml` to include the needed android dependencies.

```
<androidPackage spec="androidx.lifecycle:lifecycle-common-java8:2.4.1">
      <repositories>
        <repository>https://maven.google.com/</repository>
      </repositories>
    </androidPackage>
    <androidPackage spec="androidx.lifecycle:lifecycle-process:2.4.1">
      <repositories>
        <repository>https://maven.google.com/</repository>
      </repositories>
    </androidPackage>
```

**Comment by reezoobose** [comment]
Same Problem :

`FATAL EXCEPTION: main
                                                                                                    Process: com.weplay.motogp, PID: 23147
                                                                                                    java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: java.lang.ClassNotFoundException: androidx.lifecycle.ProcessLifecycleInitializer
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:8225)
                                                                                                    	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7728)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7482)
                                                                                                    	at android.app.ActivityThread.access$1600(ActivityThread.java:310)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2281)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8663)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
                                                                                                    Caused by: androidx.startup.StartupException: java.lang.ClassNotFoundException: androidx.lifecycle.ProcessLifecycleInitializer
                                                                                                    	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:204)
                                                                                                    	at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:42)
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2516)
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2486)
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:8220)
                                                                                                    	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7728) 
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7482) 
                                                                                                    	at android.app.ActivityThread.access$1600(ActivityThread.java:310) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2281) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226) 
                                                                                                    	at android.os.Looper.loop(Looper.java:313) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8663) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135) 
                                                                                                    Caused by: java.lang.ClassNotFoundException: androidx.lifecycle.ProcessLifecycleInitializer
                                                                                                    	at java.lang.Class.classForName(Native Method)
                                                                                                    	at java.lang.Class.forName(Class.java:454)
                                                                                                    	at java.lang.Class.forName(Class.java:379)
                                                                                                    	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:190)
                                                                                                    	at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:42) 
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2516) 
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2486) 
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:8220) 
                                                                                                    	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7728) 
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7482) 
                                                                                                    	at android.app.ActivityThread.access$1600(ActivityThread.java:310) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2281) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226) 
                                                                                                    	at android.os.Looper.loop(Looper.java:313) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8663) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135) 
                                                                                                    Caused by: java.lang.ClassNotFoundException: androidx.lifecycle.ProcessLifecycleInitializer
                                                                                                    	at java.lang.Class.classForName(Native Method) 
                                                                                                    	at java.lang.Class.forName(Class.java:454) 
                                                                                                    	at java.lang.Class.forName(Class.java:379) 
                                                                                                    	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:190) 
                                                                                                    	at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:42) 
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2516) 
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2486) 
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:8220) 
                                                                                                    	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7728) 
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7482) 
                                                                                                    	at android.app.ActivityThread.access$1600(ActivityThread.java:310) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2281) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226) 
                                                                                                    	at android.os.Looper.loop(Looper.java:313) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8663) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135) `
                                                                                                    	
This issue is due to "androidx.startup.startup-runtime-1.0.0"

I have added those lines in **"Proguard"**

_-keep class androidx.lifecycle.** { *; }
-keep class androidx.startup.AppInitializer
-keep class * extends androidx.startup.Initializer_


This is how _GoogleMobileAdsDependencies.xml_ is updated check the attachment.
[GoogleMobileAdsDependencies.xml.zip](https://github.com/googleads/googleads-mobile-unity/files/12575623/GoogleMobileAdsDependencies.xml.zip)

**Comment by NVentimiglia** [comment]
@reezoobose 

I was unable to replicate this issue. Here are my steps:

1.  Started with the hello world sample.
2. Installed 8.5.2
3. Added the GoogleMobileAdsDependencies.xml snippet.
4. Android DependencyManager Force Resolve
5. Built for Android (Gradle export)
6. Verified that the lifecycle dependencies were present
7. Ran the application, loading an AppOpen ad.

**Comment by reezoobose** [comment]
Thanks resolved.
