### ISSUE TITLE
Chartboost interstitial ads have many crashes: DownloadService.startService.

### ISSUE THREAD

**Issue by shefich** [googleads/googleads-mobile-unity#3119]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.3.34
  * Google Mobile Ads Unity plugin version: 8.7.0
  * Platform: Android
  * Platform OS version: Android 8, 11 13
  * Mediation ad networks used, and their versions: Chartboost Unity Mediation Plugin 4.5.0

### [REQUIRED] Step 2: Describe the problem
Try to show Chartboost interstitial with the help of Admob plugin and you can see such crashes:

**Fatal Exception: java.lang.Error: FATAL EXCEPTION [main]
Unity version     : 2021.3.34f1
Device model      : samsung SM-A225M
Device fingerprint: samsung/a22ub/a22:13/TP1A.220624.014/A225MUBS6CWH1:user/release-keys
Build Type        : Release
Scripting Backend : IL2CPP
ABI               : arm64-v8a
Strip Engine Code : true**

**Caused by android.app.BackgroundServiceStartNotAllowedException: Not allowed to start service Intent { act=com.google.android.exoplayer.downloadService.action.SET_STOP_REASON cmp=com.xxx.xxx/com.chartboost.sdk.internal.video.repository.exoplayer.VideoRepositoryDownloadService (has extras) }: app is in background uid UidRecord{ed82dbb u0a174 LAST bg:+1m17s738ms idle change:cached|procstate procs:0 seq(8206755,8198522)}
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1981)
       at android.app.ContextImpl.startService(ContextImpl.java:1927)
       at android.content.ContextWrapper.startService(ContextWrapper.java:834)
       at com.google.android.exoplayer2.offline.DownloadService.startService(DownloadService.java:888)
       at com.google.android.exoplayer2.offline.DownloadService.sendSetStopReason(DownloadService.java:539)
       at com.chartboost.sdk.impl.x4.a(SourceFile:264)
       at com.chartboost.sdk.impl.x4.a(SourceFile:243)
       at com.chartboost.sdk.impl.fc.c(SourceFile:12)
       at com.chartboost.sdk.impl.fc.a(SourceFile:50)
       at com.chartboost.sdk.impl.ec$a.a(SourceFile:1)
       at com.chartboost.sdk.impl.fc.a(SourceFile:62)
       at com.chartboost.sdk.impl.x4$a.a(SourceFile:3)
       at com.chartboost.sdk.impl.x4$a.invoke(SourceFile:1)
       at com.chartboost.sdk.impl.x4.a(SourceFile:230)
       at com.chartboost.sdk.impl.x4.b(SourceFile:8)
       at com.chartboost.sdk.impl.x4.onDownloadChanged(SourceFile:10)
       at com.google.android.exoplayer2.offline.DownloadManager.onDownloadUpdate(DownloadManager.java:650)
       at com.google.android.exoplayer2.offline.DownloadManager.handleMainMessage(DownloadManager.java:615)
       at com.google.android.exoplayer2.offline.DownloadManager.$r8$lambda$VH8vRSTYO69o4pUCxUdzDQ0ZEQ0()
       at com.google.android.exoplayer2.offline.DownloadManager$$ExternalSyntheticLambda0.handleMessage(:2)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8757)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)**
       
How to fix them?

**Comment by NVentimiglia** [comment]
@shefich 

Can you submit a minimal sample and complete log-trace to the [support team](https://developers.google.com/admob/unity/support). The sample/log will be needed to prove that this issue is from Admob and not AppLovin. Right now I do not see any Admob in the stack trace.

Thanks,
Nick

**Comment by shefich** [comment]
@NVentimiglia can't share minimal repro as I deleted this library as it has errors. I don't have Chartboost SDK in my project, only Mediation plugin for Admob. Based on my logs the crash happen after app goes backround while showing interstitial (firebase_screen_class: CBImpressionActivity).
But here are steps:
- download unity 2021.3.34
- add Google Mobile Ads Unity Plugin v8.7.0
- add Chartboost Unity Mediation Plugin 4.5.0
- write code to load interstitial ad
- build on device and try to show interstitial
- crash happen

Here are 2 stacktraces for this type of error:
[stacktrace1.txt](https://github.com/googleads/googleads-mobile-unity/files/14090141/stacktrace1.txt)
[stacktrace2.txt](https://github.com/googleads/googleads-mobile-unity/files/14090142/stacktrace2.txt)

**Comment by kivancbalci** [comment]
I am having the same crash on native android app with these sdks:

//admob mediation
implementation 'com.google.android.gms:play-services-ads:22.6.0'
implementation  'com.google.ads.mediation:chartboost:9.6.0.0'

The crash happened to 77 of users on OS versions 12, 13,14 on all brands of smartphones

**Comment by NVentimiglia** [comment]
Thank you, I have raised awareness b/326623197

**Comment by NaveedAhmed12** [comment]
i use unity 2020.3.27f1 with admob 8.1.0 and mediation also i want to update both but i am confused because of crashes can any one help me telling me which version is both compatibale and less crashes

**Comment by NVentimiglia** [comment]
Closing, I was not able to replicate this on `3.11.1` on plugin `9.1`

Reopen if you have future issues.
