### ISSUE TITLE
com.applovin.impl.sdk.k.a crash java.lang.IllegalThreadStateException

### ISSUE THREAD

**Issue by shefich** [googleads/googleads-mobile-unity#3120]
* Unity version: 2021.3.34
  * Google Mobile Ads Unity plugin version: 8.7.0
  * Platform: Android
  * Mediation ad networks used, and their versions: AppLovin Unity Mediation Plugin 6.9.1

### [REQUIRED] Step 2: Describe the problem

Try to show AppLovin interstitial with the help of Admob plugin and you can see such crashes:

**Fatal Exception: java.lang.Error: FATAL EXCEPTION [main]
Unity version     : 2021.3.34f1
Device model      : Casper VIA_A1_Plus_64
Device fingerprint: Casper/VIA_A1_Plus/BBL7551TC:6.0/MRA58K/1479897908:user/release-keys
Build Type        : Release
Scripting Backend : IL2CPP
ABI               : arm64-v8a
Strip Engine Code : true**

**Caused by java.lang.IllegalThreadStateException: Thread already started
       at java.lang.Thread.checkNotStarted(Thread.java:849)
       at java.lang.Thread.start(Thread.java:1059)
       at com.applovin.impl.sdk.k.a(SourceFile:100)
       at com.applovin.impl.adview.activity.b.a.w(SourceFile:877)
       at com.applovin.impl.adview.activity.b.f.B(SourceFile:848)
       at com.applovin.impl.adview.activity.b.f.c(SourceFile:575)
       at com.applovin.impl.adview.activity.b.f$a.c(SourceFile:1220)
       at com.applovin.impl.adview.x.a(SourceFile:80)
       at com.applovin.impl.adview.x.shouldOverrideUrlLoading(SourceFile:45)
       at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(chromium-SystemWebViewGoogle.aab-stable-463807403:15)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:328)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:5723)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:766)**
       
How to fix them?

**Comment by NVentimiglia** [comment]
@shefich 

Can you submit a minimal sample and complete log-trace to the [support team](https://developers.google.com/admob/unity/support). The sample/log will be needed to prove that this issue is from Admob and not AppLovin. Right now I do not see any Admob in the stack trace.

Thanks,
Nick

**Comment by shefich** [comment]
@NVentimiglia can't share minimal repro as I deleted this library as it has errors. I don't have AppLovin SDK in my project, only Mediation plugin for Admob. Based on my logs the crash happen after app goes backround while showing interstitial (firebase_screen_class: AppLovinFullscreenThemedActivity).
But here are steps:

- download unity 2021.3.34
- add Google Mobile Ads Unity Plugin v8.7.0
- add AppLovin Unity Mediation Plugin 6.9.1
- write code to load interstitial ad
- build on device and try to show interstitial
- crash happen

Here are stacktraces for this type of error:
[stacktrace_appl.txt](https://github.com/googleads/googleads-mobile-unity/files/14090171/stacktrace_appl.txt)

**Comment by NVentimiglia** [comment]
Thanks I will take a look.

**Comment by NVentimiglia** [comment]
This bug was reported to engineering and they are looking into it, closing the issue here.
