### ISSUE TITLE
Interstitials not working with 9.2.0

### ISSUE THREAD

**Issue by RomainBitard** [googleads/googleads-mobile-unity#3491]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2022.3.17f1
  * Google Mobile Ads Unity plugin version: 9.2.0
  * Plugin installation method: .unitypackage import
  * Platform: Android
  * Platform OS version: Target api level 34

### [REQUIRED] Step 2: Describe the problem
When trying to load and display an interstitial I get this error 
```
2024/08/02 20:15:47.785 22745 31788 Error LoadTask Unexpected exception loading stream
2024/08/02 20:15:47.785 22745 31788 Error LoadTask   java.lang.NullPointerException: uriString
2024/08/02 20:15:47.785 22745 31788 Error LoadTask       at android.net.Uri$StringUri.<init>(Uri.java:504)
2024/08/02 20:15:47.785 22745 31788 Error LoadTask       at android.net.Uri$StringUri.<init>(Unknown Source:0)
2024/08/02 20:15:47.785 22745 31788 Error LoadTask       at android.net.Uri.parse(Uri.java:466)
2024/08/02 20:15:47.785 22745 31788 Error LoadTask       at com.google.android.gms.ads.internal.video.google3exoplayer.e.b(:com.google.android.gms.policy_ads_fdr_dynamite@241806205@241806202034.633974825.633974825:354)
2024/08/02 20:15:47.785 22745 31788 Error LoadTask       at m.iu.b(:com.google.android.gms.policy_ads_fdr_dynamite@241806205@241806202034.633974825.633974825:8)
2024/08/02 20:15:47.785 22745 31788 Error LoadTask       at m.yi.run(:com.google.android.gms.policy_ads_fdr_dynamite@241806205@241806202034.633974825.633974825:67)
2024/08/02 20:15:47.785 22745 31788 Error LoadTask       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
2024/08/02 20:15:47.785 22745 31788 Error LoadTask       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
2024/08/02 20:15:47.785 22745 31788 Error LoadTask       at java.lang.Thread.run(Thread.java:1012)
2024/08/02 20:15:47.787 22745 22745 Warn Ads Precache exception
2024/08/02 20:15:47.787 22745 22745 Warn Ads m.yl: Unexpected NullPointerException: uriString
2024/08/02 20:15:47.787 22745 22745 Warn Ads 	at m.yi.run(:com.google.android.gms.policy_ads_fdr_dynamite@241806205@241806202034.633974825.633974825:678)
2024/08/02 20:15:47.787 22745 22745 Warn Ads 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
2024/08/02 20:15:47.787 22745 22745 Warn Ads 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
2024/08/02 20:15:47.787 22745 22745 Warn Ads 	at java.lang.Thread.run(Thread.java:1012)
2024/08/02 20:15:47.787 22745 22745 Warn Ads Caused by: java.lang.NullPointerException: uriString
2024/08/02 20:15:47.787 22745 22745 Warn Ads 	at android.net.Uri$StringUri.<init>(Uri.java:504)
2024/08/02 20:15:47.787 22745 22745 Warn Ads 	at android.net.Uri$StringUri.<init>(Unknown Source:0)
2024/08/02 20:15:47.787 22745 22745 Warn Ads 	at android.net.Uri.parse(Uri.java:466)
2024/08/02 20:15:47.787 22745 22745 Warn Ads 	at com.google.android.gms.ads.internal.video.google3exoplayer.e.b(:com.google.android.gms.policy_ads_fdr_dynamite@241806205@241806202034.633974825.633974825:354)
2024/08/02 20:15:47.787 22745 22745 Warn Ads 	at m.iu.b(:com.google.android.gms.policy_ads_fdr_dynamite@241806205@241806202034.633974825.633974825:8)
2024/08/02 20:15:47.787 22745 22745 Warn Ads 	at m.yi.run(:com.google.android.gms.policy_ads_fdr_dynamite@241806205@241806202034.633974825.633974825:67)
2024/08/02 20:15:47.787 22745 22745 Warn Ads 	... 3 more
2024/08/02 20:15:47.789 22745 31787 Error ExoPlayerImplInternal Playback error
2024/08/02 20:15:47.789 22745 31787 Error ExoPlayerImplInternal   m.jq: Source error
2024/08/02 20:15:47.789 22745 31787 Error ExoPlayerImplInternal       at m.ln.s(:com.google.android.gms.policy_ads_fdr_dynamite@241806205@241806202034.633974825.633974825:17)
2024/08/02 20:15:47.789 22745 31787 Error ExoPlayerImplInternal       at m.ln.handleMessage(:com.google.android.gms.policy_ads_fdr_dynamite@241806205@241806202034.633974825.633974825:183)
2024/08/02 20:15:47.789 22745 31787 Error ExoPlayerImplInternal       at android.os.Handler.dispatchMessage(Handler.java:102)
2024/08/02 20:15:47.789 22745 31787 Error ExoPlayerImplInternal       at android.os.Looper.loopOnce(Looper.java:211)
2024/08/02 20:15:47.789 22745 31787 Error ExoPlayerImplInternal       at android.os.Looper.loop(Looper.java:300)
2024/08/02 20:15:47.789 22745 31787 Error ExoPlayerImplInternal       at android.os.HandlerThread.run(HandlerThread.java:67)
2024/08/02 20:15:47.789 22745 31787 Error ExoPlayerImplInternal   Caused by: m.yl: Unexpected NullPointerException: uriString
2024/08/02 20:15:47.789 22745 31787 Error ExoPlayerImplInternal       at m.yi.run(:com.google.android.gms.policy_ads_fdr_dynamite@241806205@241806202034.633974825.633974825:678)
2024/08/02 20:15:47.789 22745 31787 Error ExoPlayerImplInternal       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
2024/08/02 20:15:47.789 22745 31787 Error ExoPlayerImplInternal       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
2024/08/02 20:15:47.789 22745 31787 Error ExoPlayerImplInternal       at java.lang.Thread.run(Thread.java:1012)
2024/08/02 20:15:47.789 22745 31787 Error ExoPlayerImplInternal   Caused by: java.lang.NullPointerException: uriString
2024/08/02 20:15:47.789 22745 31787 Error ExoPlayerImplInternal       at android.net.Uri$StringUri.<init>(Uri.java:504)
2024/08/02 20:15:47.789 22745 31787 Error ExoPlayerImplInternal       at android.net.Uri$StringUri.<init>(Unknown Source:0)
2024/08/02 20:15:47.789 22745 31787 Error ExoPlayerImplInternal       at android.net.Uri.parse(Uri.java:466)
2024/08/02 20:15:47.789 22745 31787 Error ExoPlayerImplInternal       at com.google.android.gms.ads.internal.video.google3exoplayer.e.b(:com.google.android.gms.policy_ads_fdr_dynamite@241806205@241806202034.633974825.633974825:354)
2024/08/02 20:15:47.789 22745 31787 Error ExoPlayerImplInternal       at m.iu.b(:com.google.android.gms.policy_ads_fdr_dynamite@241806205@241806202034.633974825.633974825:8)
2024/08/02 20:15:47.789 22745 31787 Error ExoPlayerImplInternal       at m.yi.run(:com.google.android.gms.policy_ads_fdr_dynamite@241806205@241806202034.633974825.633974825:67)
2024/08/02 20:15:47.789 22745 31787 Error ExoPlayerImplInternal       ... 3 more
2024/08/02 20:15:47.791 22745 22745 Warn Ads Precache error
2024/08/02 20:15:47.791 22745 22745 Warn Ads m.jq: Source error
2024/08/02 20:15:47.791 22745 22745 Warn Ads 	at m.ln.s(:com.google.android.gms.policy_ads_fdr_dynamite@241806205@241806202034.633974825.633974825:17)
2024/08/02 20:15:47.791 22745 22745 Warn Ads 	at m.ln.handleMessage(:com.google.android.gms.policy_ads_fdr_dynamite@241806205@241806202034.633974825.633974825:183)
2024/08/02 20:15:47.791 22745 22745 Warn Ads 	at android.os.Handler.dispatchMessage(Handler.java:102)
2024/08/02 20:15:47.791 22745 22745 Warn Ads 	at android.os.Looper.loopOnce(Looper.java:211)
2024/08/02 20:15:47.791 22745 22745 Warn Ads 	at android.os.Looper.loop(Looper.java:300)
2024/08/02 20:15:47.791 22745 22745 Warn Ads 	at android.os.HandlerThread.run(HandlerThread.java:67)
2024/08/02 20:15:47.791 22745 22745 Warn Ads Caused by: m.yl: Unexpected NullPointerException: uriString
2024/08/02 20:15:47.791 22745 22745 Warn Ads 	at m.yi.run(:com.google.android.gms.policy_ads_fdr_dynamite@241806205@241806202034.633974825.633974825:678)
2024/08/02 20:15:47.791 22745 22745 Warn Ads 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
2024/08/02 20:15:47.791 22745 22745 Warn Ads 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
2024/08/02 20:15:47.791 22745 22745 Warn Ads 	at java.lang.Thread.run(Thread.java:1012)
2024/08/02 20:15:47.791 22745 22745 Warn Ads Caused by: java.lang.NullPointerException: uriString
2024/08/02 20:15:47.791 22745 22745 Warn Ads 	at android.net.Uri$StringUri.<init>(Uri.java:504)
2024/08/02 20:15:47.791 22745 22745 Warn Ads 	at android.net.Uri$StringUri.<init>(Unknown Source:0)
2024/08/02 20:15:47.791 22745 22745 Warn Ads 	at android.net.Uri.parse(Uri.java:466)
2024/08/02 20:15:47.791 22745 22745 Warn Ads 	at com.google.android.gms.ads.internal.video.google3exoplayer.e.b(:com.google.android.gms.policy_ads_fdr_dynamite@241806205@241806202034.633974825.633974825:354)
2024/08/02 20:15:47.791 22745 22745 Warn Ads 	at m.iu.b(:com.google.android.gms.policy_ads_fdr_dynamite@241806205@241806202034.633974825.633974825:8)
2024/08/02 20:15:47.791 22745 22745 Warn Ads 	at m.yi.run(:com.google.android.gms.policy_ads_fdr_dynamite@241806205@241806202034.633974825.633974825:67)
2024/08/02 20:15:47.791 22745 22745 Warn Ads 	... 3 more

```
#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

Please share a downloadable sample project that reproduces the bug, if
available. This greatly helps us to diagnose and fix the issue faster.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by RomainBitard** [comment]
Migrating admob is such a pain I deleted everything and started from scratch and it worked
