### ISSUE TITLE
Unable to merge Android manifests when building in unity 5.6.1

### ISSUE THREAD

**Issue by hwilliams82** [googleads/googleads-mobile-unity#481]
The lowest Minsdkversion supported inside unity 5.6.1 is v16. Changing the value in the Google ads plugin does not fix the problem, nor does changing either androidmanifest.xml's targetsdkversion.

**Comment by rampara** [comment]
Using the latest version of this plugin and the HelloWolrd sample app from this repo, I'm not running into a manifest merge issue. Can you post the details of the manifest merge error you're running into?

**Comment by hwilliams82** [comment]
Here is the error that I get (I hope it helps, thanks in advance):
CommandInvokationFailure: Unable to merge android manifests. See the Console for more details. 
C:/Program Files (x86)/Java/jdk1.7.0_55\bin\java.exe -Xmx1024M -Dcom.android.sdkmanager.toolsdir="C:\Android\sdk\tools" -Dfile.encoding=UTF8 -jar "C:\Program Files\Unity\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -

stderr[
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/android/manifmerger/Merger : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:270)
	at SDKMain.main(SDKMain.java:128)
]
stdout[

]
exit code: 1
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.RunCommandInternal (System.String javaExe, System.String sdkToolsDir, System.String[] sdkToolCommand, Int32 memoryMB, System.String workingdir, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.RunCommandSafe (System.String javaExe, System.String sdkToolsDir, System.String[] sdkToolCommand, Int32 memoryMB, System.String workingdir, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.HostView:OnGUI()

**Comment by rampara** [comment]
@hwilliams82 can you ensure you are using jdk 1.8.

**Comment by rampara** [comment]
Closing issue due to non-response.
