### ISSUE TITLE
My game crashes in Android after upgrading to 3.7.1

### ISSUE THREAD

**Issue by edscodeblenders** [googleads/googleads-mobile-unity#515]
Hi there!

Just upgraded the plug-in to version 3.7.1, and now my game crashes on startup. Checked the logs from LogCat in Android Studio, and I see that this is related to Admob. First, we see the following warning:
09-27 13:12:10.000 3499-3972/? W/Ads: Invoke Firebase method getInstance error.
                                      java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.measurement.AppMeasurement" on path: DexPathList[[zip file "/data/app/com.codeblenders.games.puzzle.hexa.make64-1/base.apk"],nativeLibraryDirectories=[/data/app/com.codeblenders.games.puzzle.hexa.make64-1/lib/arm, /data/app/com.codeblenders.games.puzzle.hexa.make64-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
                                          at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                          at com.google.android.gms.ads.internal.scionintegration.b.a(:com.google.android.gms.DynamiteModulesA@11517440:167)
                                          at com.google.android.gms.ads.internal.scionintegration.b.a(:com.google.android.gms.DynamiteModulesA@11517440:152)
                                          at com.google.android.gms.ads.internal.scionintegration.b.g(:com.google.android.gms.DynamiteModulesA@11517440:43)
                                          at com.google.android.gms.ads.internal.request.c.a(:com.google.android.gms.DynamiteModulesA@11517440:47)
                                          at com.google.android.gms.ads.internal.util.b.run(:com.google.android.gms.DynamiteModulesA@11517440:4)
                                          at com.google.android.gms.ads.internal.util.af.call(:com.google.android.gms.DynamiteModulesA@11517440:3)
                                          at com.google.android.gms.ads.internal.util.ag.run(:com.google.android.gms.DynamiteModulesA@11517440:3)
                                          at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                          at java.lang.Thread.run(Thread.java:762)
09-27 13:12:10.000 3499-3972/? W/Ads: The Google Mobile Ads SDK will not integrate with Firebase. Admob/Firbase integration requires the latest Firebase SDK jar, but Firebase SDK is either missing or out of date

And immediately after we get this FATAL error:
09-27 13:12:10.037 3499-3967/? I/WebViewFactory: Loading com.android.chrome version 61.0.3163.98 (code 316309852)
09-27 13:12:10.040 3499-3499/? D/AndroidRuntime: Shutting down VM
09-27 13:12:10.041 3499-3499/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.codeblenders.games.puzzle.hexa.make64, PID: 3499
                                                 java.lang.Error: FATAL EXCEPTION [main]
                                                 Unity version     : 2017.1.0p4
                                                 Device model      : samsung SM-G925F
                                                 Device fingerprint: samsung/zeroltexx/zerolte:7.0/NRD90M/G925FXXU5EQH7:user/release-keys
                                                 
                                                 Caused by: java.lang.IllegalStateException: A fatal developer error has occurred. Check the logs for further information.
                                                     at com.google.android.gms.common.internal.zze.zzs(Unknown Source)
                                                     at com.google.android.gms.common.internal.zzi.zzajp(Unknown Source)
                                                     at com.google.android.gms.common.internal.zzh.handleMessage(Unknown Source)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:154)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6682)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

We're using the latest version of this plug-in (3.7.1) and Google Play Games version 0.9.41. These are the files in my Plugins\Android folder:
AndroidManifest.xml
AndroidManifest.xml.meta
common-1.0.0.jar
common-1.0.0.jar.meta
GoogleMobileAdsPlugin
GoogleMobileAdsPlugin.meta
libs
libs.meta
play-games-plugin-support.aar
play-games-plugin-support.aar.meta
play-services-ads-11.4.0.aar
play-services-ads-11.4.0.aar.meta
play-services-ads-lite-11.4.0.aar
play-services-ads-lite-11.4.0.aar.meta
play-services-auth-11.4.0.aar
play-services-auth-11.4.0.aar.meta
play-services-auth-base-11.4.0.aar
play-services-auth-base-11.4.0.aar.meta
play-services-base-11.4.0.aar
play-services-base-11.4.0.aar.meta
play-services-basement-11.4.0.aar
play-services-basement-11.4.0.aar.meta
play-services-drive-11.4.0.aar
play-services-drive-11.4.0.aar.meta
play-services-games-11.4.0.aar
play-services-games-11.4.0.aar.meta
play-services-gass-11.4.0.aar
play-services-gass-11.4.0.aar.meta
play-services-gcm-11.4.0.aar
play-services-gcm-11.4.0.aar.meta
play-services-iid-11.4.0.aar
play-services-iid-11.4.0.aar.meta
play-services-nearby-11.4.0.aar
play-services-nearby-11.4.0.aar.meta
play-services-tasks-11.4.0.aar
play-services-tasks-11.4.0.aar.meta
runtime-1.0.0.aar
runtime-1.0.0.aar.meta
ShortcutBadger-1.1.5.aar
ShortcutBadger-1.1.5.aar.meta
support-annotations-26.1.0.jar
support-annotations-26.1.0.jar.meta
support-compat-26.1.0.aar
support-compat-26.1.0.aar.meta
support-core-ui-26.1.0.aar
support-core-ui-26.1.0.aar.meta
support-core-utils-26.1.0.aar
support-core-utils-26.1.0.aar.meta
support-fragment-26.1.0.aar
support-fragment-26.1.0.aar.meta
support-media-compat-26.1.0.aar
support-media-compat-26.1.0.aar.meta
support-v4-26.1.0.aar
support-v4-26.1.0.aar.meta
utnotifications.aar
utnotifications.aar.meta
UTNotificationsRes
UTNotificationsRes.meta

As you can see "play-services-ads-11.4.0.aar" is there... Do you have any idea of what could be happening here?

Thanks.

**Comment by edscodeblenders** [comment]
Any comment regarding this? This is a show stopper for us...

**Comment by rampara** [comment]
@edscodeblenders you can ignore the warning, it's just log spam that will be cleaned up in a future release of the GMA Android SDK. As for the crash, do you see anything else in logcat that may indicate the cause of the crash? Are you able to reproduce the crash on the HelloWorld sample app from this repo?

**Comment by edscodeblenders** [comment]
Hi @rampara, thanks for the feedback, we thought the issue was related to admob because of the logs, but we found it related to the upgrade on Google Play Game Services... You can close this issue.
