### ISSUE TITLE
GooglePlayServices + Admob Unity plugin - Unable to convert classes into dex format.

### ISSUE THREAD

**Issue by martin3361** [googleads/googleads-mobile-unity#537]
In my project, I've integrated the Google Play services in order to do Android build and access social services.
This is what I used:
https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/current-build/GooglePlayGamesPlugin-0.9.41.unitypackage

Then all is configured and google play services are integrated and work.
Then I import this version of AdMob Unity plugin:
https://github.com/googleads/googleads-mobile-unity/releases/download/3.7.0/GoogleMobileAds.unitypackage

I explicitly used AdMob Unity plugin 3.7.0 because I noticed it uses the same google play services resolver versions - 1.2.48.0

When this happens, the build fails with error:
`CommandInvokationFailure: Unable to convert classes into dex format.`

and this is the stack trace:

```
stderr[
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzut;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzuu;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzuv;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzuw;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzux;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzuy;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzuz;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzva;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzvb;

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.RuntimeException: Translation has been interrupted
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:613)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at SDKMain.main(SDKMain.java:130)
Caused by: java.lang.InterruptedException: Too many errors
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:605)
	... 9 more
]
stdout[
processing archive /Users/Shared/Unity/bomberz.io/Temp/StagingArea/android-libraries/GoogleMobileAdsPlugin/libs/./unity-plugin-library.jar...
processing com/google/unity/BuildConfig.class...
processing com/google/unity/ads/AdNetworkExtras.class...
processing com/google/unity/ads/Banner.class...
processing com/google/unity/ads/Banner$1.class...
processing com/google/unity/ads/Banner$2.class...
processing com/google/unity/ads/Banner$3.class...
processing com/google/unity/ads/Banner$4.class...
processing com/google/unity/ads/Banner$5.class...
processing com/google/unity/ads/Banner$6.class...
processing com/google/unity/ads/Banner$7.class...
processing com/google/unity/ads/CustomNativeAd.class...
processing com/google/unity/ads/CustomNativeAd$1.class...
processing com/google/unity/ads/CustomNativeAd$2.class...
processing com/google/unity/ads/Interstitial.class...
processing com/google/unity/ads/Interstitial$1.class...
processing com/google/unity/ads/Interstitial$1$1.class...
processing com/google/unity/ads/Interstitial$2.class...
processing com/google/unity/ads/Interstitial$3.class...
processing com/google/unity/ads/NativeAdLoader.class...
processing com/google/unity/ads/NativeAdLoader$1.class...
processing com/google/unity/ads/NativeAdLoader$2.class...
processing com/google/unity/ads/NativeAdLoader$3.class...
processing com/google/unity/ads/NativeAdLoader$3$1.class...
processing com/google/unity/ads/NativeAdLoader$3$2.class...
processing com/google/unity/ads/NativeAdLoader$3$3.class...
processing com/google/unity/ads/NativeAdLoader$4.class...
processing com/google/unity/ads/NativeExpressAd.class...
processing com/google/unity/ads/NativeExpressAd$1.class...
processing com/google/unity/ads/NativeExpressAd$2.class...
processing com/google/unity/ads/NativeExpressAd$3.class...
processing com/google/unity/ads/NativeExpressAd$4.class...
processing com/google/unity/ads/NativeExpressAd$5.class...
processing com/google/unity/ads/NativeExpressAd$6.class...
processing com/google/unity/ads/NativeExpressAd$7.class...
processing com/google/unity/ads/NativeExpressAd$8.class...
processing com/google/unity/ads/PluginUtils.class...
processing com/google/unity/ads/RewardBasedVideo.class...
processing com/google/unity/ads/RewardBasedVideo$1.class...
processing com/google/unity/ads/RewardBasedVideo$1$1.class...
processing com/google/unity/ads/RewardBasedVideo$2.class...
processing com/google/unity/ads/RewardBasedVideo$3.class...
processing com/google/unity/ads/UnityAdListener.class...
processing com/google/unity/ads/UnityAdLoaderListener.class...
processing com/google/unity/ads/UnityRewardBasedVideoAdListener.class...
ignored resource /Users/Shared/Unity/bomberz.io/Temp/StagingArea/android-libraries/play-games-plugin-support/libs/./armeabi-v7a/libgpg.so
processing archive /Users/Shared/Unity/bomberz.io/Temp/StagingArea/android-libraries/play-games-plugin-support/libs/./classes.jar...
processing com/google/games/bridge/BuildConfig.class...
processing com/google/games/bridge/NativeBridgeActivity.class...
processing com/google/games/bridge/TokenFragment.class...
processing com/google/games/bridge/TokenFragment$1.class...
processing com/google/games/bridge/TokenFragment$2.class...
processing com/google/games/bridge/TokenFragment$3.class...
processing com/google/games/bridge/TokenFragment$TokenRequest.class...
processing com/google/games/bridge/TokenPendingResult.class...
processing com/google/games/bridge/TokenResult.class...
ignored resource /Users/Shared/Unity/bomberz.io/Temp/StagingArea/android-libraries/play-games-plugin-support/libs/./x86/libgpg.so
processing archive /Users/Shared/Unity/bomberz.io/Temp/StagingArea/android-libraries/play-services-ads-11.2.2/libs/./classes.jar...
ignored resource META-INF/
ignored resource META-INF/MANIFEST.MF
ignored resource com/
ignored resource com/google/
ignored resource com/google/android/
ignored resource com/google/android/gms/
ignored resource com/google/android/gms/ads/
ignored resource com/google/android/gms/ads/internal/
processing com/google/android/gms/ads/internal/ClientApi.class...
ignored resource com/google/android/gms/ads/internal/js/
processing com/google/android/gms/ads/internal/js/JavascriptEngineFactory.class...
processing com/google/android/gms/ads/internal/js/JavascriptEngineFactory$JSEngineSettableFuture.class...
processing com/google/android/gms/ads/internal/js/zza.class...
processing com/google/android/gms/ads/internal/js/zzaa.class...
processing com/google/android/gms/ads/internal/js/zzab.class...
processing com/google/android/gms/ads/internal/js/zzac.class...
processing com/google/android/gms/ads/internal/js/zzad.class...
processing com/google/android/gms/ads/internal/js/zzae.class...
processing com/google/android/gms/ads/internal/js/zzaf.class...
processing com/google/android/gms/ads/internal/js/zzag.class...
processing com/google/android/gms/ads/internal/js/zzah.class...
processing com/google/android/gms/ads/internal/js/zzai.class...
processing com/google/android/gms/ads/internal/js/zzaj.class...
processing com/google/android/gms/ads/internal/js/zzak.class...
processing com/google/android/gms/ads/internal/js/zzb.class...
processing com/google/android/gms/ads/internal/js/zzc.class...
processing com/google/android/gms/ads/internal/js/zzd.class...
processing com/google/android/gms/ads/internal/js/zze.class...
processing com/google/android/gms/ads/internal/js/zzf.class...
processing com/google/android/gms/ads/internal/js/zzg.class...
processing com/google/android/gms/ads/internal/js/zzh.class...
processing com/google/android/gms/ads/internal/js/zzi.class...
processing com/google/android/gms/ads/internal/js/zzj.class...
processing com/google/android/gms/ads/internal/js/zzk.class...
processing com/google/android/gms/ads/internal/js/zzl.class...
processing com/google/android/gms/ads/internal/js/zzm.class...
processing com/google/android/gms/ads/internal/js/zzn.class...
processing com/google/android/gms/ads/internal/js/zzo.class...
processing com/google/android/gms/ads/internal/js/zzp.class...
processing com/google/android/gms/ads/internal/js/zzq.class...
processing com/google/android/gms/ads/internal/js/zzr.class...
processing com/google/android/gms/ads/internal/js/zzs.class...
processing com/google/android/gms/ads/internal/js/zzt.class...
processing com/google/android/gms/ads/internal/js/zzu.class...
processing com/google/android/gms/ads/internal/js/zzv.class...
processing com/google/android/gms/ads/internal/js/zzw.class...
processing com/google/android/gms/ads/internal/js/zzx.class...
processing com/google/android/gms/ads/internal/js/zzy.class...
processing com/google/android/gms/ads/internal/js/zzz.class...
ignored resource com/google/android/gms/ads/internal/overlay/
processing com/google/android/gms/ads/internal/overlay/AdOverlayInfoParcel.class...
processing com/google/android/gms/ads/internal/overlay/zza.class...
processing com/google/android/gms/ads/internal/overlay/zzaa.class...
processing com/google/android/gms/ads/internal/overlay/zzab.class...
processing com/google/android/gms/ads/internal/overlay/zzac.class...
processing com/google/android/gms/ads/internal/overlay/zzad.class...
processing com/google/android/gms/ads/internal/overlay/zzae.class...
processing com/google/android/gms/ads/internal/overlay/zzaf.class...
processing com/google/android/gms/ads/internal/overlay/zzag.class...
processing com/google/android/gms/ads/internal/overlay/zzaj.class...
processing com/google/android/gms/ads/internal/overlay/zzak.class...
processing com/google/android/gms/ads/internal/overlay/zzal.class...
processing com/google/android/gms/ads/internal/overlay/zzam.class...
processing com/google/android/gms/ads/internal/overlay/zzan.class...
processing com/google/android/gms/ads/internal/overlay/zzao.class...
processing com/google/android/gms/ads/internal/overlay/zzap.class...
processing com/google/android/gms/ads/internal/overlay/zzaq.class...
processing com/google/android/gms/ads/internal/overlay/zzar.class...
processing com/google/android/gms/ads/internal/overlay/zzas.class...
processing com/google/android/gms/ads/internal/overlay/zzat.class...
processing com/google/android/gms/ads/internal/overlay/zzau.class...
processing com/google/android/gms/ads/internal/overlay/zzb.class...
processing com/google/android/gms/ads/internal/overlay/zzc.class...
processing com/google/android/gms/ads/internal/overlay/zzd.class...
processing com/google/android/gms/ads/internal/overlay/zze.class...
processing com/google/android/gms/ads/internal/overlay/zzf.class...
processing com/google/android/gms/ads/internal/overlay/zzg.class...
processing com/google/android/gms/ads/internal/overlay/zzh.class...
processing com/google/android/gms/ads/internal/overlay/zzi.class...
processing com/google/android/gms/ads/internal/overlay/zzj.class...
processing com/google/android/gms/ads/internal/overlay/zzk.class...
processing com/google/android/gms/ads/internal/overlay/zzl.class...
processing com/google/android/gms/ads/internal/overlay/zzm.class...
processing com/google/android/gms/ads/internal/overlay/zzn.class...
processing com/google/android/gms/ads/internal/overlay/zzo.class...
processing com/google/android/gms/ads/internal/overlay/zzp.class...
processing com/google/android/gms/ads/internal/overlay/zzq.class...
processing com/google/android/gms/ads/internal/overlay/zzr.class...
processing com/google/android/gms/ads/internal/overlay/zzs.class...
processing com/google/android/gms/ads/internal/overlay/zzt.class...
processing com/google/android/gms/ads/internal/overlay/zzu.class...
processing com/google/android/gms/ads/internal/overlay/zzv.class...
processing com/google/android/gms/ads/internal/overlay/zzw.class...
processing com/google/android/gms/ads/internal/overlay/zzx.class...
processing com/google/android/gms/ads/internal/overlay/zzy.class...
processing com/google/android/gms/ads/internal/overlay/zzz.class...
processing com/google/android/gms/ads/internal/zza.class...
processing com/google/android/gms/ads/internal/zzaa.class...
processing com/google/android/gms/ads/internal/zzab.class...
processing com/google/android/gms/ads/internal/zzac.class...
processing com/google/android/gms/ads/internal/zzad.class...
processing com/google/android/gms/ads/internal/zzae.class...
processing com/google/android/gms/ads/internal/zzaf.class...
processing com/google/android/gms/ads/internal/zzag.class...
processing com/google/android/gms/ads/internal/zzah.class...
processing com/google/android/gms/ads/internal/zzai.class...
processing com/google/android/gms/ads/internal/zzaj.class...
processing com/google/android/gms/ads/internal/zzak.class...
processing com/google/android/gms/ads/internal/zzal.class...
processing com/google/android/gms/ads/internal/zzam.class...
processing com/google/android/gms/ads/internal/zzan.class...
processing com/google/android/gms/ads/internal/zzao.class...
processing com/google/android/gms/ads/internal/zzap.class...
processing com/google/android/gms/ads/internal/zzaq.class...
processing com/google/android/gms/ads/internal/zzar.class...
processing com/google/android/gms/ads/internal/zzas.class...
processing com/google/android/gms/ads/internal/zzat.class...
processing com/google/android/gms/ads/internal/zzau.class...
processing com/google/android/gms/ads/internal/zzav.class...
processing com/google/android/gms/ads/internal/zzaw.class...
processing com/google/android/gms/ads/internal/zzax.class...
processing com/google/android/gms/ads/internal/zzay.class...
processing com/google/android/gms/ads/internal/zzaz.class...
processing com/google/android/gms/ads/internal/zzb.class...
processing com/google/android/gms/ads/internal/zzba.class...
processing com/google/android/gms/ads/internal/zzbb.class...
processing com/google/android/gms/ads/internal/zzbc.class...
processing com/google/android/gms/ads/internal/zzbd.class...
processing com/google/android/gms/ads/internal/zzbe.class...
processing com/google/android/gms/ads/internal/zzbf.class...
processing com/google/android/gms/ads/internal/zzbg.class...
processing com/google/android/gms/ads/internal/zzbh.class...
processing com/google/android/gms/ads/internal/zzbi.class...
processing com/google/android/gms/ads/internal/zzbj.class...
processing com/google/android/gms/ads/internal/zzbk.class...
processing com/google/android/gms/ads/internal/zzbl.class...
processing com/google/android/gms/ads/internal/zzbm.class...
processing com/google/android/gms/ads/internal/zzbn.class...
processing com/google/android/gms/ads/internal/zzbo.class...
processing com/google/android/gms/ads/internal/zzbp.class...
processing com/google/android/gms/ads/internal/zzbq.class...
processing com/google/android/gms/ads/internal/zzbr.class...
processing com/google/android/gms/ads/internal/zzbs.class...
processing com/google/android/gms/ads/internal/zzbt.class...
processing com/google/android/gms/ads/internal/zzbu.class...
processing com/google/android/gms/ads/internal/zzbv.class...
processing com/google/android/gms/ads/internal/zzbw.class...
processing com/google/android/gms/ads/internal/zzbx.class...
processing com/google/android/gms/ads/internal/zzc.class...
processing com/google/android/gms/ads/internal/zzd.class...
processing com/google/android/gms/ads/internal/zze.class...
processing com/google/android/gms/ads/internal/zzf.class...
processing com/google/android/gms/ads/internal/zzg.class...
processing com/google/android/gms/ads/internal/zzh.class...
processing com/google/android/gms/ads/internal/zzi.class...
processing com/google/android/gms/ads/internal/zzj.class...
processing com/google/android/gms/ads/internal/zzk.class...
processing com/google/android/gms/ads/internal/zzl.class...
processing com/google/android/gms/ads/internal/zzm.class...
processing com/google/android/gms/ads/internal/zzn.class...
processing com/google/android/gms/ads/internal/zzo.class...
processing com/google/android/gms/ads/internal/zzp.class...
processing com/google/android/gms/ads/internal/zzq.class...
processing com/google/android/gms/ads/internal/zzr.class...
processing com/goog<message truncated>
```

**Comment by rampara** [comment]
@martin3361 I would recommend you use the latest version of the GMA Unity plugin that includes an updated version of Play Services Resolver. You don't have to manually ensure the same version of Play Services Resolver is used across plugins. The library includes functionality to handle conflicting versions.

**Comment by rampara** [comment]
Closing due to non-response.
