### ISSUE TITLE
Resolution failed error

### ISSUE THREAD

**Issue by bthnosma** [googleads/googleads-mobile-unity#560]
I m following admob's rewarded ad tutorial.I downloaded that plugin and import it my project.But I'm getting this error when i try to click Andoid resolve > force resolve. Although I didn't able to resolve ,I can build my android game.It succesfully builded but i can't show the ad.

Resolution failed
Failed to fetch the following dependencies:
com.google.android.gms:play-services-ads:11.2.2

Gradle failed to fetch dependencies.

Failed to run 'C:\Users\batuhan osma\Documents\dart2d\Temp\PlayServicesResolverGradle\gradlew.bat -b "C:\Users\batuhan osma\Documents\dart2d\Temp\PlayServicesResolverGradle\PlayServicesResolver.scripts.download_artifacts.gradle" --no-daemon "-PANDROID_HOME=C:/Program Files (x86)/Android/android-sdk" "-PTARGET_DIR=C:\Users\batuhan osma\Documents\dart2d\Assets\Plugins\Android" "-PMAVEN_REPOS=https://maven.google.com" "-PPACKAGES_TO_COPY=com.google.android.gms:play-services-ads:11.2.2"'
stdout:

stderr:
Exception in thread "main" java.lang.RuntimeException: Timeout of 120000 reached waiting for exclusive access to file: C:\Users\batuhan osma\.gradle\wrapper\dists\gradle-4.2.1-bin\dajvke9o8kmaxbu0kc5gcgeju\gradle-4.2.1-bin.zip
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

**Comment by rampara** [comment]
@bthnosma this looks like a network connectivity issue to me. Can you ensure you have network connectivity when attempting to resolve dependencies?

**Comment by rampara** [comment]
Closing due to non-response.
