### ISSUE TITLE
Ads fail to load 'Fail to instantiate adapter com.google.DummyAdapter'

### ISSUE THREAD

**Issue by FaizanDurrani** [googleads/googleads-mobile-unity#568]
I have followed the tutorial correctly and have done "Assets > Play Services Resolver > Android Resolver > Resolve"

**adb logcat -s Unity:**
```
11-17 03:17:19.721  5358  5358 D Unity   : ReflectionHelper.Proxy.invoke(1092, [interface com.google.unity.ads.UnityRewardBasedVideoAdListener], onAdFailedToLoad, [No fill])
11-17 03:17:19.845  5358  5358 D Unity   : > AndroidJNI_CUSTOM_GetArrayLength()
11-17 03:17:19.845  5358  5358 D Unity   : > AndroidJNI_CUSTOM_INTERNAL_CALL_ExceptionOccurred()
11-17 03:17:19.845  5358  5358 D Unity   : > AndroidJNI_CUSTOM_INTERNAL_CALL_GetObjectArrayElement()
11-17 03:17:19.845  5358  5358 D Unity   : > AndroidJNI_CUSTOM_INTERNAL_CALL_ExceptionOccurred()
11-17 03:17:19.845  5358  5358 D Unity   : > AndroidJNI_CUSTOM_INTERNAL_CALL_GetObjectClass()
11-17 03:17:19.845  5358  5358 D Unity   : > AndroidJNI_CUSTOM_INTERNAL_CALL_ExceptionOccurred()
11-17 03:17:19.846  5358  5358 D Unity   : > AndroidJNI_CUSTOM_INTERNAL_CALL_NewGlobalRef()
11-17 03:17:19.846  5358  5358 D Unity   : > AndroidJNI_CUSTOM_INTERNAL_CALL_NewGlobalRef()
11-17 03:17:19.846  5358  5358 D Unity   : > AndroidJNI_CUSTOM_DeleteLocalRef()
11-17 03:17:19.846  5358  5358 D Unity   : > AndroidJNI_CUSTOM_GetStringUTFChars()
11-17 03:17:19.846  5358  5358 D Unity   : > AndroidJNI_CUSTOM_INTERNAL_CALL_NewStringUTF()
11-17 03:17:19.846  5358  5358 D Unity   : > AndroidJNI_CUSTOM_INTERNAL_CALL_ExceptionOccurred()
11-17 03:17:19.846  5358  5358 D Unity   : > AndroidJNI_CUSTOM_INTERNAL_CALL_NewStringUTF()
11-17 03:17:19.846  5358  5358 D Unity   : > AndroidJNI_CUSTOM_INTERNAL_CALL_ExceptionOccurred()
11-17 03:17:19.846  5358  5358 D Unity   : > AndroidJNI_CUSTOM_INTERNAL_CALL_CallStaticObjectMethod(0020094a, b6b8c4e4
11-17 03:17:19.846  5358  5358 D Unity   : >                    , 00200c16
11-17 03:17:19.846  5358  5358 D Unity   : >                    , 00000031
11-17 03:17:19.846  5358  5358 D Unity   : >                    , 00100035
11-17 03:17:19.846  5358  5358 D Unity   : >                    , 00000000
11-17 03:17:19.846  5358  5358 D Unity   : >                    )
11-17 03:17:19.846  5358  5358 D Unity   : ? getMethodID("java.lang.String", "getClass", "()Ljava/lang/Object;", non-static)
11-17 03:17:19.846  5358  5358 D Unity   : ! Class Object.getClass();
11-17 03:17:19.846  5358  5358 D Unity   : > AndroidJNI_CUSTOM_INTERNAL_CALL_ExceptionOccurred()
11-17 03:17:19.846  5358  5358 D Unity   : > AndroidJNI_CUSTOM_DeleteLocalRef()
11-17 03:17:19.846  5358  5358 D Unity   : > AndroidJNI_CUSTOM_DeleteLocalRef()
11-17 03:17:19.847  5358  5358 D Unity   : > AndroidJNI_CUSTOM_INTERNAL_CALL_FromReflectedMethod()
11-17 03:17:19.847  5358  5358 D Unity   : > AndroidJNI_CUSTOM_INTERNAL_CALL_ExceptionOccurred()
11-17 03:17:19.847  5358  5358 D Unity   : > AndroidJNI_CUSTOM_DeleteLocalRef()
11-17 03:17:19.847  5358  5358 D Unity   : > AndroidJNI_CUSTOM_INTERNAL_CALL_CallObjectMethod(00200c1a, 7146c4a4)
11-17 03:17:19.847  5358  5358 D Unity   : > AndroidJNI_CUSTOM_INTERNAL_CALL_ExceptionOccurred()
11-17 03:17:19.847  5358  5358 D Unity   : > AndroidJNI_CUSTOM_INTERNAL_CALL_GetObjectClass()
11-17 03:17:19.848  5358  5358 D Unity   : > AndroidJNI_CUSTOM_INTERNAL_CALL_ExceptionOccurred()
11-17 03:17:19.848  5358  5358 D Unity   : > AndroidJNI_CUSTOM_INTERNAL_CALL_NewGlobalRef()
11-17 03:17:19.848  5358  5358 D Unity   : > AndroidJNI_CUSTOM_INTERNAL_CALL_NewGlobalRef()
11-17 03:17:19.848  5358  5358 D Unity   : > AndroidJNI_CUSTOM_DeleteLocalRef()
11-17 03:17:19.848  5358  5358 D Unity   : > AndroidJNI_CUSTOM_DeleteLocalRef()
11-17 03:17:19.848  5358  5358 D Unity   : > AndroidJNI_CUSTOM_INTERNAL_CALL_NewStringUTF()
11-17 03:17:19.848  5358  5358 D Unity   : > AndroidJNI_CUSTOM_INTERNAL_CALL_ExceptionOccurred()
11-17 03:17:19.848  5358  5358 D Unity   : > AndroidJNI_CUSTOM_INTERNAL_CALL_NewStringUTF()
11-17 03:17:19.848  5358  5358 D Unity   : > AndroidJNI_CUSTOM_INTERNAL_CALL_ExceptionOccurred()
11-17 03:17:19.848  5358  5358 D Unity   : > AndroidJNI_CUSTOM_INTERNAL_CALL_CallStaticObjectMethod(0020094a, b6b8c4e4
11-17 03:17:19.848  5358  5358 D Unity   : >                    , 00100c26
11-17 03:17:19.848  5358  5358 D Unity   : >                    , 00200031
11-17 03:17:19.848  5358  5358 D Unity   : >                    , 00000035
11-17 03:17:19.848  5358  5358 D Unity   : >                    , 00000000
11-17 03:17:19.848  5358  5358 D Unity   : >                    )
11-17 03:17:19.848  5358  5358 D Unity   : ? getMethodID("java.lang.Class", "getName", "()Ljava/lang/String;", non-static)
11-17 03:17:19.848  5358  5358 D Unity   : ! String Class.getName();
11-17 03:17:19.848  5358  5358 D Unity   : > AndroidJNI_CUSTOM_INTERNAL_CALL_ExceptionOccurred()
11-17 03:17:19.848  5358  5358 D Unity   : > AndroidJNI_CUSTOM_DeleteLocalRef()
11-17 03:17:19.848  5358  5358 D Unity   : > AndroidJNI_CUSTOM_DeleteLocalRef()
11-17 03:17:19.848  5358  5358 D Unity   : > AndroidJNI_CUSTOM_INTERNAL_CALL_FromReflectedMethod()
11-17 03:17:19.848  5358  5358 D Unity   : > AndroidJNI_CUSTOM_INTERNAL_CALL_ExceptionOccurred()
11-17 03:17:19.848  5358  5358 D Unity   : > AndroidJNI_CUSTOM_DeleteLocalRef()
11-17 03:17:19.849  5358  5358 D Unity   : > AndroidJNI_CUSTOM_CallStringMethod(00100c22, 714ad748)
11-17 03:17:19.849  5358  5358 D Unity   : > AndroidJNI_CUSTOM_INTERNAL_CALL_ExceptionOccurred()
11-17 03:17:19.849  5358  5358 D Unity   : > AndroidJNI_CUSTOM_INTERNAL_CALL_NewStringUTF()
11-17 03:17:19.849  5358  5358 D Unity   : > AndroidJNI_CUSTOM_INTERNAL_CALL_ExceptionOccurred()
11-17 03:17:19.849  5358  5358 D Unity   : > AndroidJNI_CUSTOM_INTERNAL_CALL_NewStringUTF()
11-17 03:17:19.849  5358  5358 D Unity   : > AndroidJNI_CUSTOM_INTERNAL_CALL_ExceptionOccurred()
11-17 03:17:19.849  5358  5358 D Unity   : > AndroidJNI_CUSTOM_INTERNAL_CALL_CallStaticObjectMethod(0020094a, b6b8c4e4
11-17 03:17:19.849  5358  5358 D Unity   : >                    , 00200c16
11-17 03:17:19.849  5358  5358 D Unity   : >                    , 00100031
11-17 03:17:19.849  5358  5358 D Unity   : >                    , 00100035
11-17 03:17:19.849  5358  5358 D Unity   : >                    , 00000000
11-17 03:17:19.849  5358  5358 D Unity   : >                    )
11-17 03:17:19.849  5358  5358 D Unity   : ? getMethodID("java.lang.String", "toString", "()Ljava/lang/String;", non-static)
11-17 03:17:19.849  5358  5358 D Unity   : ! String String.toString();
11-17 03:17:19.849  5358  5358 D Unity   : > AndroidJNI_CUSTOM_INTERNAL_CALL_ExceptionOccurred()
11-17 03:17:19.849  5358  5358 D Unity   : > AndroidJNI_CUSTOM_DeleteLocalRef()
11-17 03:17:19.849  5358  5358 D Unity   : > AndroidJNI_CUSTOM_DeleteLocalRef()
11-17 03:17:19.849  5358  5358 D Unity   : > AndroidJNI_CUSTOM_INTERNAL_CALL_FromReflectedMethod()
11-17 03:17:19.849  5358  5358 D Unity   : > AndroidJNI_CUSTOM_INTERNAL_CALL_ExceptionOccurred()
11-17 03:17:19.849  5358  5358 D Unity   : > AndroidJNI_CUSTOM_DeleteLocalRef()
11-17 03:17:19.849  5358  5358 D Unity   : > AndroidJNI_CUSTOM_CallStringMethod(00200c1a, 7146e67c)
11-17 03:17:19.849  5358  5358 D Unity   : > AndroidJNI_CUSTOM_INTERNAL_CALL_ExceptionOccurred()
11-17 03:17:19.859  5358  5358 E Unity   : AD FAILED TO LOAD
11-17 03:17:19.859  5358  5358 E Unity   :  No fill
11-17 03:17:19.859  5358  5358 E Unity   : Stacktrace is not supported on this platform.
11-17 03:17:19.859  5358  5358 E Unity   : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
```
**adb logcat -s Ads:**
```
11-17 03:17:16.792  5358  5358 I Ads     : Starting ad request.
11-17 03:17:16.794  5358  5358 I Ads     : Use AdRequest.Builder.addTestDevice("83B6FA707C0EE113FC6F58C760856F09") to get test ads on this device.
11-17 03:17:18.119  6871  5908 W Ads     : App does not have the required permissions to get location
11-17 03:17:19.719  5358  5867 W Ads     : Fail to instantiate adapter com.google.DummyAdapter
11-17 03:17:19.719  5358  5867 W Ads     : android.os.RemoteException
11-17 03:17:19.719  5358  5867 W Ads     :      at com.google.android.gms.internal.azb.d(Unknown Source)
11-17 03:17:19.719  5358  5867 W Ads     :      at com.google.android.gms.internal.azb.c(Unknown Source)
11-17 03:17:19.719  5358  5867 W Ads     :      at com.google.android.gms.internal.azb.a(Unknown Source)
11-17 03:17:19.719  5358  5867 W Ads     :      at com.google.android.gms.internal.azd.onTransact(Unknown Source)
11-17 03:17:19.719  5358  5867 W Ads     :      at android.os.Binder.transact(Binder.java:499)
11-17 03:17:19.719  5358  5867 W Ads     :      at hg.a(:com.google.android.gms.DynamiteModulesA@11746438:10)
11-17 03:17:19.719  5358  5867 W Ads     :      at com.google.android.gms.ads.internal.mediation.client.d.a(:com.google.android.gms.DynamiteModulesA@11746438:5)
11-17 03:17:19.719  5358  5867 W Ads     :      at com.google.android.gms.ads.internal.reward.c.b(:com.google.android.gms.DynamiteModulesA@11746438:40)
11-17 03:17:19.719  5358  5867 W Ads     :      at com.google.android.gms.ads.internal.reward.mediation.j.a(:com.google.android.gms.DynamiteModulesA@11746438:29)
11-17 03:17:19.719  5358  5867 W Ads     :      at com.google.android.gms.ads.internal.util.b.run(:com.google.android.gms.DynamiteModulesA@11746438:4)
11-17 03:17:19.719  5358  5867 W Ads     :      at com.google.android.gms.ads.internal.util.af.call(:com.google.android.gms.DynamiteModulesA@11746438:3)
11-17 03:17:19.719  5358  5867 W Ads     :      at com.google.android.gms.ads.internal.util.ag.run(:com.google.android.gms.DynamiteModulesA@11746438:3)
11-17 03:17:19.719  5358  5867 W Ads     :      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
11-17 03:17:19.719  5358  5867 W Ads     :      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-17 03:17:19.719  5358  5867 W Ads     :      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
11-17 03:17:19.719  5358  5867 W Ads     :      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
11-17 03:17:19.719  5358  5867 W Ads     :      at java.lang.Thread.run(Thread.java:761)
11-17 03:17:19.721  5358  5358 W Ads     : Failed to load ad: 3
```

**AdLoader.cs:**
```cs
private RewardBasedVideoAd rewardBasedVideo;
private void Start (){
    // Get singleton reward based video ad reference.
    rewardBasedVideo = RewardBasedVideoAd.Instance;
    rewardBasedVideo.OnAdRewarded += (s, e) => {
        Revive();
        adsRevive.interactable = false;
    };
    rewardBasedVideo.OnAdClosed += (s, e) => Debug.LogError("AD CLOSED");
    rewardBasedVideo.OnAdLoaded += (s, e) => Debug.LogError("AD LOADED");
    rewardBasedVideo.OnAdOpening += (s, e) => Debug.LogError("AD OPENED");
    rewardBasedVideo.OnAdStarted += (s, e) => Debug.LogError("AD STARTED");

    // This is called printing out "AD FAILED TO LOAD\n no fill"
    rewardBasedVideo.OnAdFailedToLoad += (s, e) => Debug.LogError("AD FAILED TO LOAD\n " + e.Message);

    RequestRewardedVideo();
}

private void RequestRewardedVideo()
{
    #if UNITY_ANDROID
        // Both ids are test ids from the documentation
        string appId = "ca-app-pub-3940256099942544~3347511713";
        string adUnitId = "ca-app-pub-3940256099942544/5224354917";
    #endif
    MobileAds.Initialize(appId);
    AdRequest request = new AdRequest.Builder().Build();
    rewardBasedVideo.LoadAd(request, adUnitId);
}
```

**SDK Manager:**
https://i.imgur.com/43ICxX2.png

I am also using Firebase RTD and Firebase Auth if that helps.

**Comment by rampara** [comment]
@FaizanDurrani the error you're running into is the result of no ads being eligible to be served for your ad request. As this issue is not related to a bug in this plugin or a feature request, I would recommend you reach out on the [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) for further support.
