### ISSUE TITLE
Crash on Android(Unity) OnRewardedVideoCompleted() for Admob video ads

### ISSUE THREAD

**Issue by can-keskin** [googleads/googleads-mobile-unity#653]
Crash occur at the end of Admob rewarded video on Android. Mediation works fine, crash happens only for Admob videos. On iOS no crash either.

Here is the crash log:

`Caused by: java.lang.AbstractMethodError: abstract method "void com.google.android.gms.ads.reward.RewardedVideoAdListener.onRewardedVideoCompleted()"
        at com.google.android.gms.internal.zzafh.onRewardedVideoCompleted(Unknown Source)
        at com.google.android.gms.internal.zzafd.onTransact(Unknown Source)
        at android.os.Binder.transact(Binder.java:387)
        at hl.b(:com.google.android.gms.dynamite_dynamitemodulesa@12521020@12.5.21 (040308-189987672):20)
        at com.google.android.gms.ads.internal.reward.client.l.f(:com.google.android.gms.dynamite_dynamitemodulesa@12521020@12.5.21 (040308-189987672):27)
        at com.google.android.gms.ads.internal.a.u(:com.google.android.gms.dynamite_dynamitemodulesa@12521020@12.5.21 (040308-189987672):471)
        at com.google.android.gms.ads.internal.reward.d.f_(:com.google.android.gms.dynamite_dynamitemodulesa@12521020@12.5.21 (040308-189987672):87)
        at com.google.android.gms.ads.internal.reward.mediation.h.h(:com.google.android.gms.dynamite_dynamitemodulesa@12521020@12.5.21 (040308-189987672):37)
        at com.google.android.gms.ads.internal.reward.client.n.f(:com.google.android.gms.dynamite_dynamitemodulesa@12521020@12.5.21 (040308-189987672):96)
        at com.google.android.gms.ads.internal.a.u(:com.google.android.gms.dynamite_dynamitemodulesa@12521020@12.5.21 (040308-189987672):471)
        at com.google.android.gms.ads.internal.ak.Z(:com.google.android.gms.dynamite_dynamitemodulesa@12521020@12.5.21 (040308-189987672):277)
        at com.google.android.gms.ads.internal.gmsg.am.a(:com.google.android.gms.dynamite_dynamitemodulesa@12521020@12.5.21 (040308-189987672):28)
        at com.google.android.gms.ads.internal.webview.j.b(:com.google.android.gms.dynamite_dynamitemodulesa@12521020@12.5.21 (040308-189987672):356)
        at com.google.android.gms.ads.internal.webview.ab.run(Unknown Source)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.google.android.gms.ads.internal.util.f.dispatchMessage(:com.google.android.gms.dynamite_dynamitemodulesa@12521020@12.5.21 (040308-189987672):9)
        at android.os.Looper.loop(Looper.java:234)
        at android.app.ActivityThread.main(ActivityThread.java:5526)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

Play-services is automatically updated to the latest version 12.0.1 with play resolver.
Also using Firebase 4.5.0 and Audience Network 4.28.0.

I'm guessing there is a plugin conflict because of the OnRewardedVideoCompleted() abstract method change made in play services 12.0.0, I but can't seem to go back to 11.8.0. After a long research I couldn't force resolve to an earlier play-services version and I'm not sure event it is possible. Is there a way to get past this or should I wait for a 12.0.1 supported version of the plugin?

**Comment by web407b** [comment]
I have same problem.

**Comment by useless-id** [comment]
have the same problem  too!

![schermata 2018-04-11 alle 18 33 49](https://user-images.githubusercontent.com/16194538/38630347-f313a41c-3db6-11e8-8303-d6fb4421d72f.png)

**Comment by aurnut** [comment]
#453 Same for me sometimes.

**Comment by rampara** [comment]
@aurnut @useless-id @web407b @can-keskin can you confirm which version of Google Play services are included within your Unity project? You can determine this by checking the version of the Google Play services AARs located in the `Assets/Plugins/Android` directory of your Unity project?

**Comment by aurnut** [comment]
Now I have 11.8.0 but I don't have this issue anymore on my phone. I'm waiting for other friends' phones to test.
When I had the bug 100% on my phone I had 12.0.X (I don't remember exactly).

**Comment by rampara** [comment]
This issue should be resolved on the latest version of this plugin (v3.13.0).

**Comment by web407b** [comment]
I have checked new plugin(v3.13.0) It is well done. Thanks @rampara

**Comment by useless-id** [comment]
It works! Great job, thanks @rampara ♥︎
