### ISSUE TITLE
On ADMOB Initialization

### ISSUE THREAD

**Issue by Epiczzor** [googleads/googleads-mobile-unity#695]
Getting this error on initialisation of admob

```
06-13 18:55:53.191 11424 11458 E Unity   : AndroidJavaException: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/zzkj;
06-13 18:55:53.191 11424 11458 E Unity   : java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/zzkj;
06-13 18:55:53.191 11424 11458 E Unity   : 	at com.google.android.gms.internal.zzlc.<init>(Unknown Source:12)
06-13 18:55:53.191 11424 11458 E Unity   : 	at com.google.android.gms.internal.zzlc.<clinit>(Unknown Source:9)
06-13 18:55:53.191 11424 11458 E Unity   : 	at com.google.android.gms.internal.zzlc.zzik(Unknown Source:0)
06-13 18:55:53.191 11424 11458 E Unity   : 	at com.google.android.gms.internal.zzmz.zza(Unknown Source:22)
06-13 18:55:53.191 11424 11458 E Unity   : 	at com.google.android.gms.ads.MobileAds.initialize(Unknown Source:7)
06-13 18:55:53.191 11424 11458 E Unity   : 	at com.google.android.gms.ads.MobileAds.initialize(Unknown Source:1)
06-13 18:55:53.191 11424 11458 E Unity   : 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
06-13 18:55:53.191 11424 11458 E Unity   : 	at com.unity3d.player.UnityPlayer.c(Unknown Source:0)
06-13 18:55:53.191 11424 11458 E Unity   : 	at com.unity3d.player.UnityPlayer$e$2.queueIdle(Unknown Source:72)
06-13 18:55:53.191 11424 11458 E Unity   : 	at android.os.MessageQueue.next(MessageQueue.java:394)
06-13 18:55:53.191 11424 11458 E Unity   : 	at android.os.Looper.loop(Looper.java:142)
06-13 18:55:53.191 11424 11458 E Unity   : 	at com.unity3d.player.UnityPlayer$e.run(Unknown Source:32)
06-13 18:55:53.191 11424 11458 E Unity   : Caused by: java.lang.ClassNotFoundException: com.google.android.gm
```
Other Plugins Used:
- Google Sign in
- Facebook Sign in
- LitJSON
- Firebase Messaging

Things that I've already tried:

1) Resolve Jars
2) Reimport all my plugins

**Comment by kemalsen** [comment]
again same here

**Comment by obaidahmed234** [comment]
same here

**Comment by ardaegeunlu** [comment]
same here with v3.13.1

**Comment by Mitnainartinarian** [comment]
I had the same problem after upgrading to the newest Unity Firebase (FCM and Analytics). It looked like a conflict with different versions of Play Services components. I was able to fix it by changing Assets/GoogleMobileAds/Editor/GoogleMobileAdsDependencies.xml, to use v15.0.1 of play services ads (instead of 12.0.1):

```
...
<androidPackage spec="com.google.android.gms:play-services-ads:15.0.1">
...

```

I don't know if this is the proper way of fixing it, so I can't guarantee it won't cause other problems, but so far it has worked for me without problems.

**Comment by ardaegeunlu** [comment]
@Mitnainartinarian that worked like a charm, thanks! I will still be on my toes about this topic though.

**Comment by Epiczzor** [comment]
@Mitnainartinarian, that seemed to solve the problem for me, Thanks a lot

**Comment by rampara** [comment]
The upcoming release for this plugin will update the dependencies file to use the latest version of the Google Mobile Ads SDK, which will resolve this issue.

**Comment by casolorz** [comment]
Just want to be clear, I'm getting the exception below under 15.0.1, it is my understanding it will be fixed in a future version?

```
java.lang.AbstractMethodError: abstract method "void com.google.android.gms.ads.reward.RewardedVideoAdListener.onRewardedVideoCompleted()"
        at com.google.android.gms.internal.ads.zzahj.onRewardedVideoCompleted(Unknown Source:6)
        at com.google.android.gms.internal.ads.zzahf.dispatchTransaction(Unknown Source:5)
        at com.google.android.gms.internal.ads.zzek.onTransact(Unknown Source:22)
        at android.os.Binder.transact(Binder.java:667)
        at lz.b(:com.google.android.gms.dynamite_adsdynamite@12862063@12.8.62 (100408-199405334):19)
        at com.google.android.gms.ads.internal.reward.client.n.e(:com.google.android.gms.dynamite_adsdynamite@12862063@12.8.62 (100408-199405334):24)
        at com.google.android.gms.ads.internal.a.h(:com.google.android.gms.dynamite_adsdynamite@12862063@12.8.62 (100408-199405334):179)
        at com.google.android.gms.ads.internal.reward.e.m_(:com.google.android.gms.dynamite_adsdynamite@12862063@12.8.62 (100408-199405334):101)
        at com.google.android.gms.ads.internal.reward.mediation.h.g(:com.google.android.gms.dynamite_adsdynamite@12862063@12.8.62 (100408-199405334):37)
        at com.google.android.gms.ads.internal.reward.client.p.e(:com.google.android.gms.dynamite_adsdynamite@12862063@12.8.62 (100408-199405334):81)
        at com.google.android.gms.ads.internal.a.h(:com.google.android.gms.dynamite_adsdynamite@12862063@12.8.62 (100408-199405334):179)
        at com.google.android.gms.ads.internal.ak.X(:com.google.android.gms.dynamite_adsdynamite@12862063@12.8.62 (100408-199405334):180)
        at com.google.android.gms.ads.internal.gmsg.al.a(:com.google.android.gms.dynamite_adsdynamite@12862063@12.8.62 (100408-199405334):9)
        at com.google.android.gms.ads.internal.webview.j.b(:com.google.android.gms.dynamite_adsdynamite@12862063@12.8.62 (100408-199405334):94)
        at com.google.android.gms.ads.internal.webview.ac.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.google.android.gms.ads.internal.util.f.dispatchMessage(:com.google.android.gms.dynamite_adsdynamite@12862063@12.8.62 (100408-199405334):3)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by rampara** [comment]
Closing as this has been resolved in the latest version of this plugin.
