### ISSUE TITLE
AdsManager.loadInterstitial  UnityEngine.AndroidJavaException: java.lang.NoSuchFieldError: no ""Ljava/lang/Object;"" field ""currentActivity"

### ISSUE THREAD

**Issue by yinghuizhou** [googleads/googleads-mobile-unity#732]
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> UnityEngine.AndroidJavaException: java.lang.NoSuchFieldError: no ""Ljava/lang/Object;"" field ""currentActivity"" in class ""Lcom/unity3d/player/UnityPlayer;"" or its superclasses
java.lang.NoSuchFieldError: no ""Ljava/lang/Object;"" field ""currentActivity"" in class ""Lcom/unity3d/player/UnityPlayer;"" or its superclasses
	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
	at com.unity3d.player.UnityPlayer.c(Unknown Source)
	at com.unity3d.player.UnityPlayer$c$1.handleMessage(Unknown Source)
	at android.os.Handler.dispatchMessage(Handler.java)
	at android.os.Looper.loop(Looper.java)
	at com.unity3d.player.UnityPlayer$c.run(Unknown Source)
  at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <filename unknown>:0 
  at UnityEngine.AndroidJNISafe.GetStaticFieldID (IntPtr clazz, System.String name, System.String sig) [0x00000] in <filename unknown>:0 
  at UnityEngine._AndroidJNIHelper.GetFieldID (IntPtr jclass, System.String fieldName, System.String signature, Boolean isStatic) [0x00000] in <filename unknown>:0 
  at UnityEngine.AndroidJNIHelper.GetFieldID (IntPtr javaClass, System.String fieldName, System.String signature, Boolean isStatic) [0x00000] in <filename unknown>:0 
  at UnityEngine._AndroidJNIHelper.GetFieldID[AndroidJavaObject] (IntPtr jclass, System.String fieldName, Boolean isStatic) [0x00000] in <filename unknown>:0 
  at UnityEngine.AndroidJNIHelper.GetFieldID[AndroidJavaObject] (IntPtr jclass, System.String fieldName, Boolean isStatic) [0x00000] in <filename unknown>:0 
  at UnityEngine.AndroidJavaObject._GetStatic[AndroidJavaObject] (System.String fieldName) [0x00000] in <filename unknown>:0 
  at UnityEngine.AndroidJavaObject.GetStatic[AndroidJavaObject] (System.String fieldName) [0x00000] in <filename unknown>:0 
  at GoogleMobileAds.Android.InterstitialClient..ctor () [0x00000] in <filename unknown>:0 
  at GoogleMobileAds.GoogleMobileAdsClientFactory.BuildInterstitialClient () [0x00000] in <filename unknown>:0 
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <filename unknown>:0 
  at GoogleMobileAds.Api.InterstitialAd..ctor (System.String adUnitId) [0x00000] in <filename unknown>:0 
  at AdMobController.loadInterstitial () [0x00000] in <filename unknown>:0 
  at AdsManager.loadInterstitial () [0x00000] in <filename unknown>:0

**Comment by rampara** [comment]
@yinghuizhou for technical support I would recommend you reach out on the [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk).
