### ISSUE TITLE
ClassNotFoundException without proguard

### ISSUE THREAD

**Issue by devingDev** [googleads/googleads-mobile-unity#750]
Hi after adding the lib to Unity via doubleclicking the .unitypackage ( got it from the main admob unity page ) and importing I coded a little and added the some basic smart banner and interstitial but I am getting a ClassNotFoundException.

And yes I did press Resolve at least once in the Assets -> Play Resolver -> android menus

UNity version : 2018.2.4f1 (64bit)
Player settings : 
Release ,
Proguard : None ,
Building : Gradle , 
Min API : 16 , Jelly Bean 4.1
Target API , automatic (highest installed) which is api 27 in android studio

I dont know what else to state.

`E/Unity: AndroidJavaException: java.lang.ClassNotFoundException: com.google.android.gms.ads.MobileAds
    java.lang.ClassNotFoundException: com.google.android.gms.ads.MobileAds
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:453)
        at java.lang.Class.forName(Class.java:378)
        at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
        at com.unity3d.player.UnityPlayer.c(Unknown Source:0)
        at com.unity3d.player.UnityPlayer$e$2.queueIdle(Unknown Source:72)
        at android.os.MessageQueue.next(MessageQueue.java:394)
        at android.os.Looper.loop(Looper.java:142)
        at com.unity3d.player.UnityPlayer$e.run(Unknown Source:32)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.ads.MobileAds" on path: DexPathList[[zip file "/data/app/com.OemerDogan.KryptoKing-lqYwHt40UI2TAL9nAi1l5A==/base.apk"],nativeLibraryDirectories=[/data/app/com.OemerDogan.KryptoKing-lqYwHt40UI2TAL9nAi1l5A==/lib/x86, /data/app/com.OemerDogan.KryptoKing-lqYwHt40UI2TAL9nAi1l5A==/base.apk!/lib/

`

I tried some solutions with enabling proguard in unity and adding some data and proguard rules into the corresponding files but that had the same effect in the end.

**Comment by rampara** [comment]
@devingDev can you post the contents of the `Plugins/Android` directory of your Unity project?

**Comment by rampara** [comment]
@devingDev glad to hear the issue has been resolved for you.
