### ISSUE TITLE
[There was a problem getting an ad response. ErrorCode: 0]  error occurs some android device (tested at Galaxy S9)

### ISSUE THREAD

**Issue by Minuzzzz2** [googleads/googleads-mobile-unity#766]
The following error occurs in the test app:
Nexus5(6.0.1), Pixel(8.0.0) does not have any problems,
Galaxy9 (8.0.0)has problems.

[log]
09-27 12:34:29.379 5290-12580/? E/Ads: Error waiting for future.
                                       java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException
                                           at com.google.android.gms.ads.internal.util.future.ae.get(:com.google.android.gms@13280019@13.2.80 (040400-211705629):11)
                                           at com.google.android.gms.ads.internal.util.future.g.a(:com.google.android.gms@13280019@13.2.80 (040400-211705629):13)
                                           at com.google.android.gms.ads.internal.request.service.c.a(:com.google.android.gms@13280019@13.2.80 (040400-211705629):65)
                                           at com.google.android.gms.ads.internal.request.service.c.a(:com.google.android.gms@13280019@13.2.80 (040400-211705629):198)
                                           at com.google.android.gms.ads.internal.request.service.f.run(:com.google.android.gms@13280019@13.2.80 (040400-211705629):1)
                                           at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
                                           at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                           at java.lang.Thread.run(Thread.java:764)
                                        Caused by: java.util.concurrent.TimeoutException
                                           at com.google.android.gms.ads.internal.util.future.m.run(Unknown Source:2)
                                           at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
                                           at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                           at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
                                           at java.lang.Thread.run(Thread.java:764) 
09-27 12:34:29.380 27069-28040/? D/Ads: Received ad response.
09-27 12:34:29.381 27069-28040/? W/Ads: There was a problem getting an ad response. ErrorCode: 0
09-27 12:34:29.381 27069-27069/? W/Ads: Failed to load ad: 0
09-27 12:34:29.384 27069-27069/? D/Ads: Enable the debug gesture detector on the admob ad frame.
09-27 12:34:29.387 27069-32393/? I/Unity: HandleRewardBasedVideoFailedToLoad event received with message: Internal error

**Comment by programmermattsrum** [comment]
I'm getting the same error using the test reward ad "ca-app-pub-3940256099942544/5224354917" on my s8+ .  It was working a few days ago and just stopped working at all.  My appId is approved as well that I am using.
