### ISSUE TITLE
ClassNotFound crash on Android 9: org.apache.http.ProtocolVersion

### ISSUE THREAD

**Issue by rotter** [googleads/googleads-mobile-unity#783]
I'm getting several complains of crashes on Android 9 on my game when the players reach where the banner should be shown.

For some reason I haven't received a single report on Google Play about this crash, I would expect dozens of reports if it's affecting all Android 9 players.

I don't have an Android 9 device, but tried on an emulator and it is indeed crashing with the stack trace below. The first time I tried showing a banner it did work, then I exited the match, started a new match and it crashed, and after this point I couldnt show a banner again, it always crashes (maybe related to cache?).

> 2018-10-12 21:15:06.423 4369-4633/com.mycompany.myapp E/AndroidRuntime: FATAL EXCEPTION: Thread-26
    Process: com.mycompany.myapp, PID: 4369
    java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/ProtocolVersion;
        at jp.a(:com.google.android.gms.dynamite_adsdynamite@12862026@12.8.62 (040700-199405334):6)
        at jq.a(:com.google.android.gms.dynamite_adsdynamite@12862026@12.8.62 (040700-199405334):57)
        at com.google.android.gms.ads.internal.util.ap.a(:com.google.android.gms.dynamite_adsdynamite@12862026@12.8.62 (040700-199405334):23)
        at jb.a(:com.google.android.gms.dynamite_adsdynamite@12862026@12.8.62 (040700-199405334):14)
        at jb.run(:com.google.android.gms.dynamite_adsdynamite@12862026@12.8.62 (040700-199405334):60)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.ProtocolVersion" on path: DexPathList[[zip file "/system/priv-app/PrebuiltGmsCore/app_chimera/m/AdsDynamite.apk"],nativeLibraryDirectories=[/data/user_de/0/com.google.android.gms/app_chimera/m/00000000/AdsDynamite.apk!/lib/x86, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at dhd.loadClass(:com.google.android.gms@12862026@12.8.62 (040700-199405334):3)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at jp.a(:com.google.android.gms.dynamite_adsdynamite@12862026@12.8.62 (040700-199405334):6) 
        at jq.a(:com.google.android.gms.dynamite_adsdynamite@12862026@12.8.62 (040700-199405334):57) 
        at com.google.android.gms.ads.internal.util.ap.a(:com.google.android.gms.dynamite_adsdynamite@12862026@12.8.62 (040700-199405334):23) 
        at jb.a(:com.google.android.gms.dynamite_adsdynamite@12862026@12.8.62 (040700-199405334):14) 
        at jb.run(:com.google.android.gms.dynamite_adsdynamite@12862026@12.8.62 (040700-199405334):60)

**Comment by rotter** [comment]
Ok, so I searched a bit and quickly found a fix or workaround for this problem on the Google Maps SDK forum and docs: https://developers.google.com/maps/documentation/android-sdk/config#specify_requirement_for_apache_http_legacy_library

`If your app is targeting API level 28 (Android 9.0) or above, you must include the following declaration within the <application> element of AndroidManifest.xml.

  \<uses-library
      android:name="org.apache.http.legacy"
      android:required="false" /\>`

**Comment by rotter** [comment]
Just as an extra comment, this is a bit odd as I just realized Unity doesnt support targeting API 27 yet (only up to 26) as far as I know, so I'm targeting API 27. So how am I being affected by this problem if I'm targeting API 27? Anyway, the fix above seems to have worked for me...
