### ISSUE TITLE
FATAL EXCEPTION when Interstitial is shown (interstitial.MediationAdapterClassName() == "AdMobAdapter")

### ISSUE THREAD

**Issue by rchallenger** [googleads/googleads-mobile-unity#840]
Using only demo buttons to show ads in application I was testing it, as there appeared a lot crashes. And second device I took showed to me the things I wanted to find: displaying Interstitial, that I received from Admob (not mediation adapter), caused crash on the device. Viewing ads from other adapters didn't cause any crashes or ANRs. But when some certain content, received by AdMob, was shown it immidiately caused crash.
[Project ](https://play.google.com/store/apps/details?id=com.PSVStudio.LuntikMinigames) was built using Gradle (multidex enabled).

Device summary:
- Xiaomi Mi6 6/64Gb
- Android 8.0.0
- MIUI Global 10.0.1.0 (OCAMIFH)

Software summary:
- Unity 2018.2.20
- GAD 3.15.1
- Resolver 1.2.99
- FirebaseAnalytics 5.4.4
- play-services-ads 17.1.3
<details>
    <summary>Assets/Plugins/Android folder contents</summary>

![plugins](https://user-images.githubusercontent.com/20810488/52350166-9f3eca80-2a30-11e9-8c96-ed669286398d.JPG)
</details>
<br />
<details>
    <summary>Log message</summary>
            <pre>
<code>
02-06 16:10:19.886: E/AndroidRuntime(12929): FATAL EXCEPTION: main
02-06 16:10:19.886: E/AndroidRuntime(12929): Process: com.PSVStudio.LuntikMinigames, PID: 12929
02-06 16:10:19.886: E/AndroidRuntime(12929): java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.gms.ads.internal.video.l.b(int)' on a null object reference
02-06 16:10:19.886: E/AndroidRuntime(12929): 	at com.google.android.gms.ads.internal.video.gmsg.e.a(:com.google.android.gms.dynamite_adsdynamite@15090051@15.0.90 (040408-231259764):15)
02-06 16:10:19.886: E/AndroidRuntime(12929): 	at com.google.android.gms.ads.internal.video.gmsg.e.a(:com.google.android.gms.dynamite_adsdynamite@15090051@15.0.90 (040408-231259764):85)
02-06 16:10:19.886: E/AndroidRuntime(12929): 	at com.google.android.gms.ads.internal.webview.j.a(:com.google.android.gms.dynamite_adsdynamite@15090051@15.0.90 (040408-231259764):312)
02-06 16:10:19.886: E/AndroidRuntime(12929): 	at com.google.android.gms.ads.internal.webview.ac.a(Unknown Source:4)
02-06 16:10:19.886: E/AndroidRuntime(12929): 	at com.google.android.gms.ads.internal.webview.ad.run(Unknown Source:2)
02-06 16:10:19.886: E/AndroidRuntime(12929): 	at android.os.Handler.handleCallback(Handler.java:789)
02-06 16:10:19.886: E/AndroidRuntime(12929): 	at android.os.Handler.dispatchMessage(Handler.java:98)
02-06 16:10:19.886: E/AndroidRuntime(12929): 	at ze.a(:com.google.android.gms.dynamite_adsdynamite@15090051@15.0.90 (040408-231259764):5)
02-06 16:10:19.886: E/AndroidRuntime(12929): 	at com.google.android.gms.ads.internal.util.e.a(:com.google.android.gms.dynamite_adsdynamite@15090051@15.0.90 (040408-231259764):11)
02-06 16:10:19.886: E/AndroidRuntime(12929): 	at ze.dispatchMessage(:com.google.android.gms.dynamite_adsdynamite@15090051@15.0.90 (040408-231259764):4)
02-06 16:10:19.886: E/AndroidRuntime(12929): 	at android.os.Looper.loop(Looper.java:171)
02-06 16:10:19.886: E/AndroidRuntime(12929): 	at android.app.ActivityThread.main(ActivityThread.java:6699)
02-06 16:10:19.886: E/AndroidRuntime(12929): 	at java.lang.reflect.Method.invoke(Native Method)
02-06 16:10:19.886: E/AndroidRuntime(12929): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
02-06 16:10:19.886: E/AndroidRuntime(12929): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
        </code>
    </pre>
</details>
<br />

[Complete log](https://github.com/googleads/googleads-mobile-unity/files/2836651/LuntikMiniGamesLog.txt)

 <details>
    <summary>Screenshots</summary>

![Demo buttons to show ads](https://user-images.githubusercontent.com/20810488/52347747-63553680-2a2b-11e9-9aec-3c7d2f10b18f.png)

</details>
<br />

Here are some crash reports from Android Vitals (Google Play Developer console)
<details>
    <summary>Screenshot from Android Vitals report</summary>

![vitals](https://user-images.githubusercontent.com/20810488/52349495-5df9eb00-2a2f-11e9-9f87-eec8935a95e1.JPG)

</details>
<details><summary>Huawei Y541-U02 (HWY541-U), Android 4.4</summary><pre><code>java.lang.Error: FATAL EXCEPTION [main]
Unity version     : 2018.2.20f1
Device model      : HUAWEI HUAWEI Y541-U02
Device fingerprint: HUAWEI/Y541-U02/HWY541-U:4.4.2/HUAWEIY541-U02/C479B111:user/ota-rel-keys,release-keys
Caused by
  at com.google.android.gms.ads.internal.video.gmsg.e.a (com.google.android.gms.dynamite_adsdynamite@15090007@15.0.90 (000304-231259764):15)
  at com.google.android.gms.ads.internal.video.gmsg.e.a (com.google.android.gms.dynamite_adsdynamite@15090007@15.0.90 (000304-231259764):85)
  at com.google.android.gms.ads.internal.webview.j.a (com.google.android.gms.dynamite_adsdynamite@15090007@15.0.90 (000304-231259764):312)
  at com.google.android.gms.ads.internal.webview.ac.a (Unknown Source)
  at com.google.android.gms.ads.internal.webview.ad.run (Unknown Source)
  at android.os.Handler.handleCallback (Handler.java:733)
  at android.os.Handler.dispatchMessage (Handler.java:95)
  at aaa.a (com.google.android.gms.dynamite_adsdynamite@15090007@15.0.90 (000304-231259764):5)
  at com.google.android.gms.ads.internal.util.e.a (com.google.android.gms.dynamite_adsdynamite@15090007@15.0.90 (000304-231259764):11)
  at aaa.dispatchMessage (com.google.android.gms.dynamite_adsdynamite@15090007@15.0.90 (000304-231259764):4)
  at android.os.Looper.loop (Looper.java:136)
  at android.app.ActivityThread.main (ActivityThread.java:5421)
  at java.lang.reflect.Method.invokeNative (Native Method)
  at java.lang.reflect.Method.invoke (Method.java:515)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:979)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:795)
  at dalvik.system.NativeStart.main (Native Method)</code></pre></details>

<details><summary>Samsung Galaxy Tab3 VE 7.0 (goyave3g), Android 4.4</summary><pre><code>java.lang.Error: FATAL EXCEPTION [main]
Unity version     : 2018.2.20f1
Device model      : samsung SM-T116
Device fingerprint: samsung/goyave3gxx/goyave3g:4.4.4/KTU84P/T116XXS0AQC2:user/release-keys
Caused by
  at com.google.android.gms.ads.internal.video.gmsg.e.a (com.google.android.gms.dynamite_adsdynamite@15090006@15.0.90 (000302-231259764):15)
  at com.google.android.gms.ads.internal.video.gmsg.e.a (com.google.android.gms.dynamite_adsdynamite@15090006@15.0.90 (000302-231259764):85)
  at com.google.android.gms.ads.internal.webview.j.a (com.google.android.gms.dynamite_adsdynamite@15090006@15.0.90 (000302-231259764):312)
  at com.google.android.gms.ads.internal.webview.ac.a (Unknown Source)
  at com.google.android.gms.ads.internal.webview.ad.run (Unknown Source)
  at android.os.Handler.handleCallback (Handler.java:733)
  at android.os.Handler.dispatchMessage (Handler.java:95)
  at aaa.a (com.google.android.gms.dynamite_adsdynamite@15090006@15.0.90 (000302-231259764):5)
  at com.google.android.gms.ads.internal.util.e.a (com.google.android.gms.dynamite_adsdynamite@15090006@15.0.90 (000302-231259764):11)
  at aaa.dispatchMessage (com.google.android.gms.dynamite_adsdynamite@15090006@15.0.90 (000302-231259764):4)
  at android.os.Looper.loop (Looper.java:136)
  at android.app.ActivityThread.main (ActivityThread.java:5584)
  at java.lang.reflect.Method.invokeNative (Native Method)
  at java.lang.reflect.Method.invoke (Method.java:515)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1268)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1084)
  at dalvik.system.NativeStart.main (Native Method)</code></pre></details>
<details><summary>Huawei Honor 6A (HWDLI-Q), Android 7.0</summary><pre><code>java.lang.Error: FATAL EXCEPTION [main]
Unity version     : 2018.2.20f1
Device model      : HUAWEI DLI-TL20
Device fingerprint: HONOR/DLI-TL20/HWDLI-Q:7.0/HONORDLI-TL20/C10B126:user/release-keys
Caused by
  at com.google.android.gms.ads.internal.video.gmsg.e.a (com.google.android.gms.dynamite_adsdynamite@15090046@15.0.90 (040306-231259764):15)
  at com.google.android.gms.ads.internal.video.gmsg.e.a (com.google.android.gms.dynamite_adsdynamite@15090046@15.0.90 (040306-231259764):85)
  at com.google.android.gms.ads.internal.webview.j.a (com.google.android.gms.dynamite_adsdynamite@15090046@15.0.90 (040306-231259764):312)
  at com.google.android.gms.ads.internal.webview.ac.a (Unknown Source)
  at com.google.android.gms.ads.internal.webview.ad.run (Unknown Source)
  at android.os.Handler.handleCallback (Handler.java:761)
  at android.os.Handler.dispatchMessage (Handler.java:98)
  at ze.a (com.google.android.gms.dynamite_adsdynamite@15090046@15.0.90 (040306-231259764):5)
  at com.google.android.gms.ads.internal.util.e.a (com.google.android.gms.dynamite_adsdynamite@15090046@15.0.90 (040306-231259764):11)
  at ze.dispatchMessage (com.google.android.gms.dynamite_adsdynamite@15090046@15.0.90 (040306-231259764):4)
  at android.os.Looper.loop (Looper.java:156)
  at android.app.ActivityThread.main (ActivityThread.java:6623)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:942)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:832)</code></pre></details>
<details><summary>Samsung Galaxy A7 (2018) (a7y18lte), Android 8.0</summary><pre><code>java.lang.Error: FATAL EXCEPTION [main]
Unity version     : 2018.2.20f1
Device model      : samsung SM-A750FN
Device fingerprint: samsung/a7y18ltexx/a7y18lte:8.0.0/R16NW/A750FNXXU1ARL3:user/release-keys
Caused by
  at com.google.android.gms.ads.internal.video.gmsg.e.a (com.google.android.gms.dynamite_adsdynamite@15090048@15.0.90 (040400-231259764):15)
  at com.google.android.gms.ads.internal.video.gmsg.e.a (com.google.android.gms.dynamite_adsdynamite@15090048@15.0.90 (040400-231259764):85)
  at com.google.android.gms.ads.internal.webview.j.a (com.google.android.gms.dynamite_adsdynamite@15090048@15.0.90 (040400-231259764):312)
  at com.google.android.gms.ads.internal.webview.ac.a (Unknown Source:4)
  at com.google.android.gms.ads.internal.webview.ad.run (Unknown Source:2)
  at android.os.Handler.handleCallback (Handler.java:789)
  at android.os.Handler.dispatchMessage (Handler.java:98)
  at ze.a (com.google.android.gms.dynamite_adsdynamite@15090048@15.0.90 (040400-231259764):5)
  at com.google.android.gms.ads.internal.util.e.a (com.google.android.gms.dynamite_adsdynamite@15090048@15.0.90 (040400-231259764):11)
  at ze.dispatchMessage (com.google.android.gms.dynamite_adsdynamite@15090048@15.0.90 (040400-231259764):4)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6942)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:327)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1374)</code></pre></details>
<details><summary>Samsung Galaxy J2 (j2y18lte), Android 7.1</summary><pre><code>java.lang.Error: FATAL EXCEPTION [main]
Unity version     : 2018.2.20f1
Device model      : samsung SM-J250F
Device fingerprint: samsung/j2y18lteser/j2y18lte:7.1.1/NMF26X/J250FXWU2ARK1:user/release-keys
Caused by
  at com.google.android.gms.ads.internal.video.gmsg.e.a (com.google.android.gms.dynamite_adsdynamite@15090045@15.0.90 (040304-231259764):15)
  at com.google.android.gms.ads.internal.video.gmsg.e.a (com.google.android.gms.dynamite_adsdynamite@15090045@15.0.90 (040304-231259764):85)
  at com.google.android.gms.ads.internal.webview.j.a (com.google.android.gms.dynamite_adsdynamite@15090045@15.0.90 (040304-231259764):312)
  at com.google.android.gms.ads.internal.webview.ac.a (Unknown Source)
  at com.google.android.gms.ads.internal.webview.ad.run (Unknown Source)
  at android.os.Handler.handleCallback (Handler.java:751)
  at android.os.Handler.dispatchMessage (Handler.java:95)
  at ze.a (com.google.android.gms.dynamite_adsdynamite@15090045@15.0.90 (040304-231259764):5)
  at com.google.android.gms.ads.internal.util.e.a (com.google.android.gms.dynamite_adsdynamite@15090045@15.0.90 (040304-231259764):11)
  at ze.dispatchMessage (com.google.android.gms.dynamite_adsdynamite@15090045@15.0.90 (040304-231259764):4)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6816)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1565)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1453)</code></pre></details>
<details><summary>Lenovo TB3-710I (TB3-710I), Android 5.1</summary><pre><code>java.lang.Error: FATAL EXCEPTION [main]
Unity version     : 2018.2.20f1
Device model      : Lenovo Lenovo TB3-710I
Device fingerprint: Lenovo/LenovoTB3-710I/TB3-710I:5.1/LMY47I/TB3-710I_S000032_160921_ROW:user/release-keys
Caused by
  at com.google.android.gms.ads.internal.video.gmsg.e.a (com.google.android.gms.dynamite_adsdynamite@15090027@15.0.90 (020300-231259764):15)
  at com.google.android.gms.ads.internal.video.gmsg.e.a (com.google.android.gms.dynamite_adsdynamite@15090027@15.0.90 (020300-231259764):85)
  at com.google.android.gms.ads.internal.webview.j.a (com.google.android.gms.dynamite_adsdynamite@15090027@15.0.90 (020300-231259764):312)
  at com.google.android.gms.ads.internal.webview.ac.a (Unknown Source)
  at com.google.android.gms.ads.internal.webview.ad.run (Unknown Source)
  at android.os.Handler.handleCallback (Handler.java:815)
  at android.os.Handler.dispatchMessage (Handler.java:104)
  at zk.a (com.google.android.gms.dynamite_adsdynamite@15090027@15.0.90 (020300-231259764):5)
  at com.google.android.gms.ads.internal.util.e.a (com.google.android.gms.dynamite_adsdynamite@15090027@15.0.90 (020300-231259764):11)
  at zk.dispatchMessage (com.google.android.gms.dynamite_adsdynamite@15090027@15.0.90 (020300-231259764):4)
  at android.os.Looper.loop (Looper.java:194)
  at android.app.ActivityThread.main (ActivityThread.java:5637)
  at java.lang.reflect.Method.invoke (Native Method)
  at java.lang.reflect.Method.invoke (Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:960)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:755)</code></pre></details>
<details><summary>Lenovo K5 Plus (A6020a46), Android 5.1</summary><pre><code>java.lang.Error: FATAL EXCEPTION [main]
Unity version     : 2018.2.20f1
Device model      : LENOVO Lenovo A6020a46
Device fingerprint: Lenovo/A6020a46/A6020a46:5.1.1/LMY47V/A6020a46_S056_161019_ROW:user/release-keys
Caused by
  at com.google.android.gms.ads.internal.video.gmsg.f.a (com.google.android.gms.dynamite_adsdynamite@14799034@14.7.99 (020408-223214910):13)
  at com.google.android.gms.ads.internal.video.gmsg.f.a (com.google.android.gms.dynamite_adsdynamite@14799034@14.7.99 (020408-223214910):83)
  at com.google.android.gms.ads.internal.webview.j.a (com.google.android.gms.dynamite_adsdynamite@14799034@14.7.99 (020408-223214910):305)
  at com.google.android.gms.ads.internal.webview.ac.run (Unknown Source)
  at android.os.Handler.handleCallback (Handler.java:739)
  at android.os.Handler.dispatchMessage (Handler.java:95)
  at zk.a (com.google.android.gms.dynamite_adsdynamite@14799034@14.7.99 (020408-223214910):5)
  at com.google.android.gms.ads.internal.util.e.a (com.google.android.gms.dynamite_adsdynamite@14799034@14.7.99 (020408-223214910):5)
  at zk.dispatchMessage (com.google.android.gms.dynamite_adsdynamite@14799034@14.7.99 (020408-223214910):4)
  at android.os.Looper.loop (Looper.java:135)
  at android.app.ActivityThread.main (ActivityThread.java:5268)
  at java.lang.reflect.Method.invoke (Native Method)
  at java.lang.reflect.Method.invoke (Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:902)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:697)</code></pre></details>

**Comment by UragayalaDeepika** [comment]
@rchallenger Are you still seeing this issue? Can you please check with our latest version and let us know? Closing this for now. Feel free to comment here so that we can reinvestigate this issue if it is still reproducible with the latest version.
