### ISSUE TITLE
TimeoutException

### ISSUE THREAD

**Issue by UnityKR** [googleads/googleads-mobile-unity#851]
Device summary:

* samsung SHV-E300L
* Android 5.0.1

Software summary:

* Unity 2018.3.6f1
* Resolver play-services-resolver_v1.2.100.0
* GooglePlayGamesPlugin_v0.9.61
* Google Mobile Ads Unity Plugin v3.15.1

Error Log
02-18 13:54:28.718 31483-31732/? E/Ads: Error waiting for future.
    java.util.concurrent.TimeoutException
        at java.util.concurrent.FutureTask.get(FutureTask.java:176)
        at com.google.android.gms.ads.internal.util.future.g.a(:com.google.android.gms@15090009@15.0.90 (020308-231259764):12)
        at com.google.android.gms.ads.cache.l.a(:com.google.android.gms@15090009@15.0.90 (020308-231259764):5)
        at com.google.android.gms.ads.nonagon.signals.gmscore.q.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
02-18 13:54:28.743 31483-31741/? E/Ads: Error waiting for future.
    java.util.concurrent.TimeoutException
        at java.util.concurrent.FutureTask.get(FutureTask.java:176)
        at com.google.android.gms.ads.internal.util.future.g.a(:com.google.android.gms@15090009@15.0.90 (020308-231259764):12)
        at com.google.android.gms.ads.cache.l.a(:com.google.android.gms@15090009@15.0.90 (020308-231259764):5)
        at com.google.android.gms.ads.nonagon.signals.gmscore.q.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)

**Comment by UragayalaDeepika** [comment]
Closing this for now. Feel free to comment here so that we can reopen and investigate this issue if it is still reproducible with the latest version.
