### ISSUE TITLE
App crash with latest (2.2.1) InMobi mediation adapter

### ISSUE THREAD

**Issue by adlercoder** [googleads/googleads-mobile-unity#860]
It still crashes even after I removed all of lib dependencies but "com.google.android.gms:play-services-location:16.0.0"

Works after removing "com.google.android.gms:play-services-location:16.0.0" dependency.

**Comment by matie** [comment]
Hi,

Even after removing the suggested location service, it crashes. On at least android 5.1, 6.0, 8.0 and 8.1.

Could someone have a look at it and resolve the issue? Thanks!



 java.lang.NullPointerException: println needs a message 	
at android.util.Log.println_native(Native Method) 	
at android.util.Log.d(Log.java:139) 	
at com.google.ads.mediation.inmobi.InMobiAdapter.requestBannerAd(InMobiAdapter.java:145) 	
at com.google.android.gms.internal.ads.zzanm.zza(Unknown Source) 	
at com.google.android.gms.internal.ads.zzamu.dispatchTransaction(Unknown Source) 	
at com.google.android.gms.internal.ads.zzfn.onTransact(Unknown Source) 	
at android.os.Binder.transact(Binder.java:387) 	
....

**Comment by UragayalaDeepika** [comment]
For mediation/SDK related issues, please use Google Mobile Ads SDK Technical Forum and our team will be able to assist you on these issues.

**Comment by Ruco** [comment]
Same issue using the latest adapter. Although it doesn't crash it does report the Exception:
``
java.lang.NullPointerException: println needs a message
at android.util.Log.println_native(Native Method)
at android.util.Log.d(Log.java:145)
at com.google.ads.mediation.inmobi.InMobiAdapter.requestBannerAd(InMobiAdapter.java:129)
``
