### ISSUE TITLE
Getting "Not a MediationBannerAdapter <class name>" when requesting banner ad from banner AdUnit

### ISSUE THREAD

**Issue by rchallenger** [googleads/googleads-mobile-unity#869]
Hello,
Some of my builds produce errors of this kind and no ad is loaded. Though AdUnit is set up correctly and there is no mistake. For debug I left only banner requests in test build. And even when my waterfall does not contain any Chartboost and Unity AdSource configurations I still get errors related to them. Moreover it is ridiculous as banner AdUnits does not contain in Mediation networks list Chatboost, Vungle, UnityAds networks.

Can you help me figuring out what is the source of the issue?

<details> 
  <summary>LogCat messages</summary>

```
03-05 14:43:58.441: D/AdsUnity(11438): Calling loadAd() on Android
03-05 14:43:58.447: D/StatusBar(2124): No peeking: unimportant notification: 0|free.vpn.unblock.proxy.turbovpn|1000|null|10206
03-05 14:43:58.465: D/DynamitePackage(11438): Instantiating com.google.android.gms.ads.ChimeraAdManagerCreatorImpl
03-05 14:43:58.474: I/Ads(11438): Use AdRequest.Builder.addTestDevice("C6AF6F783FF29DC7E84B08DF869D595D") to get test ads on this device.
03-05 14:43:58.506: D/AudioManager(11438): getStreamVolume isRestricted mode = 0
03-05 14:43:58.508: D/audio_hw_extn(740): audio_extn_get_parameters: returns 
03-05 14:43:58.508: V/msm8974_platform(740): platform_get_parameters: exit: returns - 
03-05 14:43:58.508: I/hash_map_utils(936): key: 'hifi_mode' value: ''
03-05 14:43:58.509: D/AdsUnity(11438): Calling hide() on Android
03-05 14:43:58.513: D/AudioManager(11438): getStreamVolume isRestricted mode = 0
03-05 14:43:58.544: W/Ads(3121): App does not have the required permissions to get location
03-05 14:43:58.615: I/Ads(3121): SDK version: afma-sdk-a-v15090021.14300000.1
03-05 14:43:58.861: W/Ads(11438): Server parameters: {"slotId":"1027611039"}
03-05 14:43:58.862: D/MyTargetAdapter(11438): Requesting myTarget banner mediation, slotId: 1027611039
03-05 14:43:58.862: W/MyTargetAdapter(11438): AdSize 320x50_as is not currently supported
03-05 14:43:58.865: D/FA(11438): Logging event (FE): ad_query(_aq), Bundle[{firebase_event_origin(_o)=am, firebase_screen_class(_sc)=game.scene, firebase_screen_id(_si)=4807390730495669785, firebase_screen(_sn)=HiddenInfo, ad_event_id(_aeid)=4807390730495669791}]
03-05 14:43:58.866: W/Ads(11438): Not a MediationBannerAdapter: com.vungle.mediation.VungleInterstitialAdapter
03-05 14:43:58.869: W/Ads(11438): Not a MediationBannerAdapter: com.google.ads.mediation.chartboost.ChartboostAdapter
03-05 14:43:58.872: W/Ads(11438): Not a MediationBannerAdapter: com.google.ads.mediation.unity.UnityAdapter
03-05 14:43:58.874: D/MobFoxBanner(11438): MobFox AdMob Adapter >> constructor
03-05 14:43:58.876: W/Ads(11438): Server parameters: {"pubid":"ccc4df89b6d7bc51c40954a372dd72a4"}
03-05 14:43:58.876: D/MobFoxBanner(11438): MobFox AdMob Adapter >> requestBannerAd 
03-05 14:43:58.876: D/MobFoxBanner(11438): MobFox AdMob Adapter >> init banner w:320 h:50
03-05 14:43:58.886: D/EgretLoader(11438): EgretLoader(Context context)
03-05 14:43:58.887: D/EgretLoader(11438): The context is not activity
03-05 14:43:58.893: V/FA(11438): Connecting to remote service
03-05 14:43:58.895: D/MobFoxUtils(11438): read setting
03-05 14:43:58.895: D/MobFoxBanner(11438): dmp post completed
03-05 14:43:58.896: D/MobFoxBanner(11438): Loading url http://sdk.starbolt.io/dist/tagBanner.html?o_andadvid=843f45c0-d86d-40e6-8975-bce7a738d13f&adspace_width=320&sub_bundle_id=com.PSVStudio.HippoDentist&c_mraid=1&rt=android_app&s=ccc4df89b6d7bc51c40954a372dd72a4&dev_dnt=0&v=3.2.7b_admob&dev_js=1&adspace_height=50
03-05 14:43:58.913: D/FA(11438): Connected to remote service
03-05 14:43:58.913: V/FA(11438): Processing queued up service tasks: 1
03-05 14:43:58.980: E/SQLiteDatabase(2649): Error inserting period=2000 target_class=com.google.android.gms.measurement.PackageMeasurementTaskService required_network_type=0 runtime=1551789838968 source=4 target_package=com.google.android.gms source_version=15090000 last_runtime=0 user_id=0 job_id=-1 requires_charging=0 tag=Measurement.PackageMeasurementTaskService.UPLOAD_TASK_TAG flex_time=0 task_type=0 retry_strategy={"maximum_backoff_seconds":{"3600":0},"initial_backoff_seconds":{"30":0},"retry_policy":{"0":0}}
03-05 14:43:58.980: E/SQLiteDatabase(2649): android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: pending_ops.tag, pending_ops.target_class, pending_ops.target_package, pending_ops.user_id (code 2067)
03-05 14:43:58.980: E/SQLiteDatabase(2649): 	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
03-05 14:43:58.980: E/SQLiteDatabase(2649): 	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
03-05 14:43:58.980: E/SQLiteDatabase(2649): 	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
03-05 14:43:58.980: E/SQLiteDatabase(2649): 	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
03-05 14:43:58.980: E/SQLiteDatabase(2649): 	at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1474)
03-05 14:43:58.980: E/SQLiteDatabase(2649): 	at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1343)
03-05 14:43:58.980: E/SQLiteDatabase(2649): 	at zrt.a(:com.google.android.gms@15090021@15.0.90 (040408-231259764):148)
03-05 14:43:58.980: E/SQLiteDatabase(2649): 	at zum.a(:com.google.android.gms@15090021@15.0.90 (040408-231259764):137)
03-05 14:43:58.980: E/SQLiteDatabase(2649): 	at zum.a(:com.google.android.gms@15090021@15.0.90 (040408-231259764):6)
03-05 14:43:58.980: E/SQLiteDatabase(2649): 	at zum.a(:com.google.android.gms@15090021@15.0.90 (040408-231259764):128)
03-05 14:43:58.980: E/SQLiteDatabase(2649): 	at zrr.run(:com.google.android.gms@15090021@15.0.90 (040408-231259764):4)
03-05 14:43:58.980: E/SQLiteDatabase(2649): 	at rrm.run(:com.google.android.gms@15090021@15.0.90 (040408-231259764):21)
03-05 14:43:58.980: E/SQLiteDatabase(2649): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
03-05 14:43:58.980: E/SQLiteDatabase(2649): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
03-05 14:43:58.980: E/SQLiteDatabase(2649): 	at rxo.run(Unknown Source:7)
03-05 14:43:58.980: E/SQLiteDatabase(2649): 	at java.lang.Thread.run(Thread.java:764)
03-05 14:43:59.283: E/MobFoxBanner(11438): MobFox AdMob Adapter >> Banner error {"e3":"No Ad Available"}
03-05 14:43:59.286: W/Ads(11438): Server parameters: {"accountid":"3827b83fea2a45f68676baecd1cec7a1","placementid":"1485606054514"}
03-05 14:43:59.327: D/AudioManager(11438): getStreamVolume isRestricted mode = 0
03-05 14:43:59.329: D/audio_hw_extn(740): audio_extn_get_parameters: returns 
03-05 14:43:59.329: V/msm8974_platform(740): platform_get_parameters: exit: returns - 
03-05 14:43:59.329: I/hash_map_utils(936): key: 'hifi_mode' value: ''
03-05 14:43:59.332: D/audio_hw_extn(740): audio_extn_get_parameters: returns 
03-05 14:43:59.332: V/msm8974_platform(740): platform_get_parameters: exit: returns - 
03-05 14:43:59.333: I/hash_map_utils(936): key: 'hifi_mode' value: ''
03-05 14:43:59.667: E/SQLiteDatabase(2649): Error inserting period=7200000 target_class=com.google.android.gms.measurement.PackageMeasurementTaskService required_network_type=0 runtime=1551789839655 source=4 target_package=com.google.android.gms source_version=15090000 last_runtime=0 user_id=0 job_id=-1 requires_charging=0 tag=Measurement.PackageMeasurementTaskService.UPLOAD_TASK_TAG flex_time=3599000 task_type=0 retry_strategy={"maximum_backoff_seconds":{"3600":0},"initial_backoff_seconds":{"30":0},"retry_policy":{"0":0}}
03-05 14:43:59.667: E/SQLiteDatabase(2649): android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: pending_ops.tag, pending_ops.target_class, pending_ops.target_package, pending_ops.user_id (code 2067)
03-05 14:43:59.667: E/SQLiteDatabase(2649): 	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
03-05 14:43:59.667: E/SQLiteDatabase(2649): 	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
03-05 14:43:59.667: E/SQLiteDatabase(2649): 	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
03-05 14:43:59.667: E/SQLiteDatabase(2649): 	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
03-05 14:43:59.667: E/SQLiteDatabase(2649): 	at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1474)
03-05 14:43:59.667: E/SQLiteDatabase(2649): 	at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1343)
03-05 14:43:59.667: E/SQLiteDatabase(2649): 	at zrt.a(:com.google.android.gms@15090021@15.0.90 (040408-231259764):148)
03-05 14:43:59.667: E/SQLiteDatabase(2649): 	at zum.a(:com.google.android.gms@15090021@15.0.90 (040408-231259764):137)
03-05 14:43:59.667: E/SQLiteDatabase(2649): 	at zum.a(:com.google.android.gms@15090021@15.0.90 (040408-231259764):6)
03-05 14:43:59.667: E/SQLiteDatabase(2649): 	at zum.a(:com.google.android.gms@15090021@15.0.90 (040408-231259764):128)
03-05 14:43:59.667: E/SQLiteDatabase(2649): 	at zrr.run(:com.google.android.gms@15090021@15.0.90 (040408-231259764):4)
03-05 14:43:59.667: E/SQLiteDatabase(2649): 	at rrm.run(:com.google.android.gms@15090021@15.0.90 (040408-231259764):21)
03-05 14:43:59.667: E/SQLiteDatabase(2649): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
03-05 14:43:59.667: E/SQLiteDatabase(2649): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
03-05 14:43:59.667: E/SQLiteDatabase(2649): 	at rxo.run(Unknown Source:7)
03-05 14:43:59.667: E/SQLiteDatabase(2649): 	at java.lang.Thread.run(Thread.java:764)
03-05 14:44:00.004: D/KeyguardUpdateMonitor(2124): handleTimeUpdate
03-05 14:44:00.114: W/Notification(10839): Use of stream types is deprecated for operations other than volume control
03-05 14:44:00.114: W/Notification(10839): See the documentation of setSound() for what to use instead with android.media.AudioAttributes to qualify your playback use case
03-05 14:44:00.142: D/StatusBar(2124): updateNotification(StatusBarNotification(pkg=free.vpn.unblock.proxy.turbovpn user=UserHandle{0} id=1000 tag=null key=0|free.vpn.unblock.proxy.turbovpn|1000|null|10206: Notification(channel=VPN Service pri=-1 contentView=null vibrate=null sound=null defaults=0x0 flags=0x16a color=0xff3f51b5 category=service vis=PRIVATE)))
03-05 14:44:00.149: D/StatusBar(2124): updateNotification(StatusBarNotification(pkg=free.vpn.unblock.proxy.turbovpn user=UserHandle{0} id=1000 tag=null key=0|free.vpn.unblock.proxy.turbovpn|1000|null|10206: Notification(channel=VPN Service pri=-1 contentView=null vibrate=null sound=null defaults=0x0 flags=0x16a color=0xff3f51b5 category=service vis=PRIVATE)))
03-05 14:44:00.180: D/StatusBar(2124): No peeking: unimportant notification: 0|free.vpn.unblock.proxy.turbovpn|1000|null|10206
03-05 14:44:00.380: D/InMobiAdapter(11438): onAdLoadFailed: The Ad Request timed out waiting for a response from the network. This can be caused due to a bad network connection. Please try again after a few minutes.
03-05 14:44:00.390: W/Ads(11438): Server parameters: {"class_name":"com.kidoz.mediation.admob.adapters.KidozAdMobMediationBannerAdapter","label":"KidozBanner","parameter":"{\"AppID\":\"11645\", \"Token\":\"8mvGy08EWJtoUH6CtGjPFUlM2ELDCc1X\" }"}
03-05 14:44:00.391: D/KidozAdMobMediationBannerAdapter(11438): KidozBannerAdapter | requestBannerAd called
03-05 14:44:00.391: D/KidozAdMobMediationBannerAdapter(11438): KidozBannerAdapter | kidoz already init
03-05 14:44:00.391: D/KidozAdMobMediationBannerAdapter(11438): KidozBannerAdapter | kidoz continueRequestBannerAd
03-05 14:44:00.392: D/KidozAdMobMediationBannerAdapter(11438): kidozBannerAdapter | banner not set up, calling view load.
03-05 14:44:00.392: D/KidozAdMobMediationBannerAdapter(11438): kidozBannerAdapter | kidozBannerView == null, calling view creation. START
03-05 14:44:00.419: D/EgretLoader(11438): EgretLoader(Context context)
03-05 14:44:00.420: D/EgretLoader(11438): The context is not activity
03-05 14:44:00.445: D/[KIDOZ SDK](11438): KidozBannerPresenter | banner init()
03-05 14:44:00.445: D/KidozBannerPresenter(11438): validateAndLoadAssets() | start
03-05 14:44:00.446: D/KidozAdMobMediationBannerAdapter(11438): kidozBannerAdapter | kidozBannerView == null, calling view creation. END
03-05 14:44:00.447: D/KidozAdMobMediationBannerAdapter(11438): KidozBannerAdapter | continueRequestBannerAd | calling load()
03-05 14:44:00.447: D/[KIDOZ SDK](11438): KidozBannerPresenter | Load 3
03-05 14:44:00.447: D/[KIDOZ SDK](11438): KidozBannerPresenter | Load 4
03-05 14:44:00.447: D/[KIDOZ SDK](11438): KidozBannerPresenter | Load 5
03-05 14:44:00.447: D/[KIDOZ SDK](11438): KidozBannerPresenter | Load 6
03-05 14:44:00.447: D/[KIDOZ SDK](11438): KidozBannerPresenter | Load 0
03-05 14:44:00.447: D/[KIDOZ SDK](11438): KidozBannerPresenter | Load 7
03-05 14:44:00.447: D/KidozBannerPresenter(11438): internalLoad() | calling html.loadBanner, mProperties = null
03-05 14:44:00.457: I/Kidoz DataBase Print Log(11438): KD (loadAppProperties) :  Loaded [0] items from PropertiesTableDB Table
03-05 14:44:00.463: I/Kidoz DataBase Print Log(11438): KD (loadProperties) :  Loaded [0] items from PropertiesTableDB Table
03-05 14:44:00.465: I/chromium(11438): [INFO:CONSOLE(1)] "Uncaught ReferenceError: loadBanner is not defined", source:  (1)
03-05 14:44:00.466: D/[KIDOZ SDK](11438): KidozBannerPresenter invokeJSfunction (javascript:loadBanner(null);) | evaluateJS return value = null
03-05 14:44:00.479: I/Kidoz DataBase Print Log(11438): KD (insertProperties)  : Inserted [0] items into PropertiesTableDB Table
03-05 14:44:00.483: I/Kidoz DataBase Print Log(11438): KD (loadProperties) :  Loaded [0] items from PropertiesTableDB Table
03-05 14:44:00.483: D/[KIDOZ SDK](11438): KidozBannerPresenter | mProperties = {"style_id":5,"html_url":"https:\/\/cdn.kidoz.net\/video_player\/v\/v5.0\/banner\/index.html","ht1ml_url":"https:\/\/s3.amazonaws.com\/kidoz.test.bucket\/Fiodor\/core\/banner\/index.html"}
03-05 14:44:00.483: D/KidozBannerPresenter(11438): validateAndLoadAssets() | parse success
03-05 14:44:00.483: D/KidozBannerPresenter(11438): view.load(https://cdn.kidoz.net/video_player/v/v5.0/banner/index.html)
03-05 14:44:00.485: D/[KIDOZ SDK](11438): KidozBannerPresenter | onProgressChanged | newProgress = 10 url = https://cdn.kidoz.net/video_player/v/v5.0/banner/index.html
03-05 14:44:00.846: D/[KIDOZ SDK](11438): KidozBannerPresenter | onProgressChanged | newProgress = 22 url = https://cdn.kidoz.net/video_player/v/v5.0/banner/index.html
03-05 14:44:00.959: D/[KIDOZ SDK](11438): KidozBannerPresenter | onProgressChanged | newProgress = 70 url = https://cdn.kidoz.net/video_player/v/v5.0/banner/index.html
03-05 14:44:01.072: D/SdkDeviceUtils(11438): >>>>Google advertising ID = 843f45c0-d86d-40e6-8975-bce7a738d13f
03-05 14:44:01.082: D/[KIDOZ SDK](11438): KidozBannerPresenter | onProgressChanged | newProgress = 80 url = https://cdn.kidoz.net/video_player/v/v5.0/banner/index.html
03-05 14:44:01.085: D/[KIDOZ SDK](11438): KidozBanner | IOnHtmlWebViewInterface | onViewReady()
03-05 14:44:01.085: D/[KIDOZ SDK](11438): KidozBannerPresenter | checkConditionsForBannerReady..
03-05 14:44:01.087: D/[KIDOZ SDK](11438): KidozBannerPresenter | onProgressChanged | newProgress = 100 url = https://cdn.kidoz.net/video_player/v/v5.0/banner/index.html
03-05 14:44:01.088: D/[KIDOZ SDK](11438): KidozBannerPresenter | onProgressChanged | newProgress = 100 url = https://cdn.kidoz.net/video_player/v/v5.0/banner/index.html
03-05 14:44:01.088: D/[KIDOZ SDK](11438): KidozBanner | IOnHtmlWebViewInterface | onHtmlFinishedLoading()
03-05 14:44:02.486: D/[KIDOZ SDK](11438): KidozBannerPresenter | calling check, try no. 0
03-05 14:44:02.493: D/[KIDOZ SDK](11438): KidozBannerPresenter | mDidGetCallbackAliveSignal = true
03-05 14:44:02.493: D/[KIDOZ SDK](11438): KidozBannerPresenter | checkConditionsForBannerReady..
03-05 14:44:02.493: D/[KIDOZ SDK](11438): KidozBannerPresenter | checkConditionsForBannerReady 1
03-05 14:44:02.494: D/[KIDOZ SDK](11438): KidozBannerPresenter | checkConditionsForBannerReady 2
03-05 14:44:02.494: D/[KIDOZ SDK](11438): KidozBannerPresenter | Load 1
03-05 14:44:02.494: D/KidozBannerPresenter(11438): internalLoad() | calling html.loadBanner, mProperties = {"style_id":5,"html_url":"https:\/\/cdn.kidoz.net\/video_player\/v\/v5.0\/banner\/index.html","ht1ml_url":"https:\/\/s3.amazonaws.com\/kidoz.test.bucket\/Fiodor\/core\/banner\/index.html"}
03-05 14:44:02.497: D/[KIDOZ SDK](11438): KidozBannerPresenter invokeJSfunction (javascript:check()) | evaluateJS return value = null
03-05 14:44:02.506: D/[KIDOZ SDK](11438): KidozBannerPresenter invokeJSfunction (javascript:loadBanner({"style_id":5,"html_url":"https:\/\/cdn.kidoz.net\/video_player\/v\/v5.0\/banner\/index.html","ht1ml_url":"https:\/\/s3.amazonaws.com\/kidoz.test.bucket\/Fiodor\/core\/banner\/index.html"});) | evaluateJS return value = null
03-05 14:44:02.514: W/Notification(10839): Use of stream types is deprecated for operations other than volume control
03-05 14:44:02.514: W/Notification(10839): See the documentation of setSound() for what to use instead with android.media.AudioAttributes to qualify your playback use case
03-05 14:44:02.529: D/StatusBar(2124): updateNotification(StatusBarNotification(pkg=free.vpn.unblock.proxy.turbovpn user=UserHandle{0} id=1000 tag=null key=0|free.vpn.unblock.proxy.turbovpn|1000|null|10206: Notification(channel=VPN Service pri=-1 contentView=null vibrate=null sound=null defaults=0x0 flags=0x16a color=0xff3f51b5 category=service vis=PRIVATE)))
03-05 14:44:02.547: D/StatusBar(2124): updateNotification(StatusBarNotification(pkg=free.vpn.unblock.proxy.turbovpn user=UserHandle{0} id=1000 tag=null key=0|free.vpn.unblock.proxy.turbovpn|1000|null|10206: Notification(channel=VPN Service pri=-1 contentView=null vibrate=null sound=null defaults=0x0 flags=0x16a color=0xff3f51b5 category=service vis=PRIVATE)))
03-05 14:44:02.596: D/StatusBar(2124): No peeking: unimportant notification: 0|free.vpn.unblock.proxy.turbovpn|1000|null|10206
03-05 14:44:02.828: D/kidozbanner(11438): onJSBannerLoad called from JS. success = false
03-05 14:44:02.829: E/KidozBannerPresenter(11438): internalLoad() | error: = Server response: Banners not found
03-05 14:44:02.829: E/KidozAdMobMediationBannerAdapter(11438): kidozBannerAdapter | onBannerError: Server response: Banners not found
03-05 14:44:02.830: E/KidozBannerPresenter(11438): internalLoad() | error: = onNoOffers
03-05 14:44:02.830: D/KidozAdMobMediationBannerAdapter(11438): kidozBannerAdapter | onBannerNoOffers
03-05 14:44:02.833: I/Ads(11438): Ad failed to load : 3
```
</details>

**Comment by rchallenger** [comment]
It appears admob dashboard allow creating configuration for Networks without small banners (Unity, Vungle, Chartboost) and they are actually present in the netwroks list.
So there was no issue at all.
But it is a quesion what was the purpose of leaving Vungle, Chartboost among banner AdSources
