### ISSUE TITLE
When use test ad unit every works but when i use my own ad unit id it stop working

### ISSUE THREAD

**Issue by Ikxyz** [googleads/googleads-mobile-unity#877]
I have uploaded my flutter app to playstore i have linked it up with my admob and my firebase account..
All my account is in sync. But my adunit does not work

This is my log 
```
 [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(no_ad_for_id, isAdLoaded failed, no add exists for id=114709726, null)
E/flutter ( 9631): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
E/flutter ( 9631): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302:33)
E/flutter ( 9631): <asynchronous suspension>
E/flutter ( 9631): #2      _invokeBooleanMethod (package:firebase_admob/firebase_admob.dart:518:61)
E/flutter ( 9631): <asynchronous suspension>
E/flutter ( 9631): #3      MobileAd.isLoaded (package:firebase_admob/firebase_admob.dart:242:12)
E/flutter ( 9631): #4      _HomeState.build.<anonymous closure>.<anonymous closure> (package:cac/route/home.dart:126:24)
E/flutter ( 9631): #5      _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter ( 9631): #6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter ( 9631): #7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter ( 9631): #8      _CustomZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:968:26)
E/flutter ( 9631): #9      _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter ( 9631): #10     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter ( 9631): #11     _CustomZone.bindUnaryCallback.<anonymous closure> (dart:async/zone.dart:952:26)
E/flutter ( 9631): #12     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
E/flutter ( 9631): #13     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
E/flutter ( 9631): #14     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
E/flutter ( 9631): 
```

**Comment by yosun** [comment]
i have the same problem using the unity implementation hello world

**Comment by UragayalaDeepika** [comment]
@Ikxyz @yosun This issue tracker is only for the issues related to Unity Plugin. Please reachout to [Google Mobile Ads SDK Technical Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) and our team will be able to assist you with this issue.

**Comment by Ikxyz** [comment]
Building a release apk solved the issues for me.. and also a new ad unit takes time to start working so if you're using a new ad unit you might want to give it a little more time..

**Comment by Ikxyz** [comment]
Building a release apk solved the issues for me.. and also a new ad unit takes time to start working so if you're using a new ad unit you might want to give it a little more time..
