### ISSUE TITLE
HelloWorld Sample Crash on Unity 2018.3.11/12

### ISSUE THREAD

**Issue by wardetta** [googleads/googleads-mobile-unity#885]
Hello,
I have run into crashing problems when i upgraded to the 3.16 version so i tried the sample 
and still no luck.
Here is the logcat, hope it helps fix these issues asap :)
Thanks!

04-09 21:54:21.865  2022  9224 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.TestCompany.AdmobTest/com.unity3d.player.UnityPlayerActivity bnds=[41,751][241,1016]} from uid 10024
04-09 21:54:21.867   595   633 E ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
04-09 21:54:21.869  2022  9224 E ANDR-PERF-JNI: com_qualcomm_qtiperformance_native_perf_io_prefetch_start
04-09 21:54:21.878  2022  9224 D ActivityTrigger: activityStartTrigger: Activity is Triggerred in full screen ApplicationInfo{4fcd514 com.TestCompany.AdmobTest}
04-09 21:54:21.878  2022  9224 E ActivityTrigger: activityStartTrigger: not whiteListedcom.TestCompany.AdmobTest/com.unity3d.player.UnityPlayerActivity/1
04-09 21:54:21.878  2022  9224 D CompatibilityInfo: mCompatibilityFlags - 0
04-09 21:54:21.878  2022  9224 D CompatibilityInfo: applicationDensity - 480
04-09 21:54:21.878  2022  9224 D CompatibilityInfo: applicationScale - 1.0
04-09 21:54:21.878  2022  9224 D ActivityTrigger: activityResumeTrigger: The activity in ApplicationInfo{4fcd514 com.TestCompany.AdmobTest} is now in focus and seems to be in full-screen mode
04-09 21:54:21.878  2022  9224 E ActivityTrigger: activityResumeTrigger: not whiteListedcom.TestCompany.AdmobTest/com.unity3d.player.UnityPlayerActivity/1
04-09 21:54:21.879  2022  9224 D ActivityTrigger: ActivityTrigger activityPauseTrigger
04-09 21:54:21.885  2022  2387 D ActivityTrigger: activityResumeTrigger: The activity in ApplicationInfo{4fcd514 com.TestCompany.AdmobTest} is now in focus and seems to be in full-screen mode
04-09 21:54:21.885  2022  2387 E ActivityTrigger: activityResumeTrigger: not whiteListedcom.TestCompany.AdmobTest/com.unity3d.player.UnityPlayerActivity/1
04-09 21:54:21.891  2022  2078 I ActivityManager: Killing 26823:com.android.providers.calendar/u0a2 (adj 906): empty #17
04-09 21:54:21.892  2022  2081 W libprocessgroup: kill(-26823, 9) failed: No such process
04-09 21:54:21.901  2022  2080 I ActivityManager: Start proc 28549:com.TestCompany.AdmobTest/u0a321 for activity com.TestCompany.AdmobTest/com.unity3d.player.UnityPlayerActivity
04-09 21:54:21.907 28549 28549 W mpany.AdmobTes: Using default instruction set features for ARM CPU variant (cortex-a9) using conservative defaults
04-09 21:54:21.909   933   933 I Zygote  : Process 26823 exited due to signal (9)
04-09 21:54:21.909 28549 28549 E mpany.AdmobTes: Not starting debugger since process cannot load the jdwp agent.
04-09 21:54:21.922  2022  2387 D CompatibilityInfo: mCompatibilityFlags - 0
04-09 21:54:21.922  2022  2387 D CompatibilityInfo: applicationDensity - 480
04-09 21:54:21.922  2022  2387 D CompatibilityInfo: applicationScale - 1.0
04-09 21:54:21.928  2022  2387 D CompatibilityInfo: mCompatibilityFlags - 0
04-09 21:54:21.928  2022  2387 D CompatibilityInfo: applicationDensity - 480
04-09 21:54:21.928  2022  2387 D CompatibilityInfo: applicationScale - 1.0
04-09 21:54:21.935  2022  2410 I InputReader: Reconfiguring input devices.  changes=0x00000004
04-09 21:54:21.938  2022  2081 W libprocessgroup: kill(-26823, 9) failed: No such process
04-09 21:54:21.939  2022  2081 I libprocessgroup: Successfully killed process cgroup uid 10002 pid 26823 in 47ms
04-09 21:54:21.961 28549 28549 I Perf    : Connecting to perf service.
04-09 21:54:21.968 28549 28549 D AndroidRuntime: Shutting down VM
04-09 21:54:21.969 28549 28549 E AndroidRuntime: FATAL EXCEPTION: main
04-09 21:54:21.969 28549 28549 E AndroidRuntime: Process: com.TestCompany.AdmobTest, PID: 28549
04-09 21:54:21.969 28549 28549 E AndroidRuntime: java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException:
04-09 21:54:21.969 28549 28549 E AndroidRuntime:
04-09 21:54:21.969 28549 28549 E AndroidRuntime: ******************************************************************************
04-09 21:54:21.969 28549 28549 E AndroidRuntime: * Invalid application ID. Follow instructions here: https://goo.gl/fQ2neu to *
04-09 21:54:21.969 28549 28549 E AndroidRuntime: * find your app ID.                                                          *
04-09 21:54:21.969 28549 28549 E AndroidRuntime: ******************************************************************************
04-09 21:54:21.969 28549 28549 E AndroidRuntime:
04-09 21:54:21.969 28549 28549 E AndroidRuntime:
04-09 21:54:21.969 28549 28549 E AndroidRuntime:        at android.app.ActivityThread.installProvider(ActivityThread.java:6489)
04-09 21:54:21.969 28549 28549 E AndroidRuntime:        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5982)
04-09 21:54:21.969 28549 28549 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5888)
04-09 21:54:21.969 28549 28549 E AndroidRuntime:        at android.app.ActivityThread.access$1100(ActivityThread.java:200)
04-09 21:54:21.969 28549 28549 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1660)
04-09 21:54:21.969 28549 28549 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
04-09 21:54:21.969 28549 28549 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
04-09 21:54:21.969 28549 28549 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6762)
04-09 21:54:21.969 28549 28549 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-09 21:54:21.969 28549 28549 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
04-09 21:54:21.969 28549 28549 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
04-09 21:54:21.969 28549 28549 E AndroidRuntime: Caused by: java.lang.IllegalStateException:
04-09 21:54:21.969 28549 28549 E AndroidRuntime:
04-09 21:54:21.969 28549 28549 E AndroidRuntime: ******************************************************************************
04-09 21:54:21.969 28549 28549 E AndroidRuntime: * Invalid application ID. Follow instructions here: https://goo.gl/fQ2neu to *
04-09 21:54:21.969 28549 28549 E AndroidRuntime: * find your app ID.                                                          *
04-09 21:54:21.969 28549 28549 E AndroidRuntime: ******************************************************************************
04-09 21:54:21.969 28549 28549 E AndroidRuntime:
04-09 21:54:21.969 28549 28549 E AndroidRuntime:
04-09 21:54:21.969 28549 28549 E AndroidRuntime:        at com.google.android.gms.internal.ads.zzabg.attachInfo(Unknown Source:19)
04-09 21:54:21.969 28549 28549 E AndroidRuntime:        at com.google.android.gms.ads.MobileAdsInitProvider.attachInfo(Unknown Source:3)
04-09 21:54:21.969 28549 28549 E AndroidRuntime:        at android.app.ActivityThread.installProvider(ActivityThread.java:6484)
04-09 21:54:21.969 28549 28549 E AndroidRuntime:        ... 10 more
04-09 21:54:21.972  2022  7538 W ActivityManager:   Force finishing activity com.TestCompany.AdmobTest/com.unity3d.player.UnityPlayerActivity
04-09 21:54:21.973  2022  7538 D ActivityTrigger: ActivityTrigger activityPauseTrigger
04-09 21:54:21.977 28549 28549 I Process : Sending signal. PID: 28549 SIG: 9
04-09 21:54:21.978  2022  2078 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
04-09 21:54:21.978  2022  2078 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
04-09 21:54:21.981   611   611 E lowmemorykiller: Error writing /proc/28549/oom_score_adj; errno=22
04-09 21:54:21.984  2022  7538 D CompatibilityInfo: mCompatibilityFlags - 0
04-09 21:54:21.984  2022  7538 D CompatibilityInfo: applicationDensity - 480
04-09 21:54:21.984  2022  7538 D CompatibilityInfo: applicationScale - 1.0
04-09 21:54:21.988  2022  4452 D CompatibilityInfo: mCompatibilityFlags - 0
04-09 21:54:21.988  2022  4452 D CompatibilityInfo: applicationDensity - 480
04-09 21:54:21.988  2022  4452 D CompatibilityInfo: applicationScale - 1.0
04-09 21:54:21.994  2022  2387 D CompatibilityInfo: mCompatibilityFlags - 0
04-09 21:54:21.994  2022  2387 D CompatibilityInfo: applicationDensity - 480
04-09 21:54:21.994  2022  2387 D CompatibilityInfo: applicationScale - 1.0
04-09 21:54:21.996  2022  4452 I ActivityManager: Process com.TestCompany.AdmobTest (pid 28549) has died: vis  +99TOP
04-09 21:54:21.998  2022  2081 W libprocessgroup: kill(-28549, 9) failed: No such process
04-09 21:54:21.999  2022  2081 I libprocessgroup: Successfully killed process cgroup uid 10321 pid 28549 in 2ms
04-09 21:54:21.999   934   934 I Zygote  : Process 28549 exited due to signal (9)
04-09 21:54:22.009  2022  4452 D ActivityTrigger: activityResumeTrigger: The activity in ApplicationInfo{4cf38d4 com.android.launcher3} is now in focus and seems to be in full-screen mode
04-09 21:54:22.010  2022  4452 E ActivityTrigger: activityResumeTrigger: not whiteListedcom.android.launcher3/com.android.a1launcher.AndroidOneLauncher/28
04-09 21:54:22.018   595   633 E ANDR-PERF-OPTSHANDLER: Perflock resource /sys/class/devfreq/soc:qcom,llccbw/min_freq not supported
04-09 21:54:22.018   595   633 E ANDR-PERF-RESOURCEQS: Failed to apply optimization [12, 0]
04-09 21:54:22.019   805   805 D SurfaceFlinger: duplicate layer name: changing Surface(name=fcf9499 StatusBar)/@0x39c2a2e - animation-leash to Surface(name=fcf9499 StatusBar)/@0x39c2a2e - animation-leash#1
04-09 21:54:22.019   595   633 E ANDR-PERF-OPTSHANDLER: Failed to read /sys/class/kgsl/kgsl-3d0/force_no_nap
04-09 21:54:22.019   595   633 E ANDR-PERF-RESOURCEQS: Failed to apply optimization [10, 7]
04-09 21:54:22.034  8698  8812 I MicroDetectionWorker: #startMicroDetector [speakerMode: 0]
04-09 21:54:22.036  8698  8812 W ErrorReporter: reportError [type: 211, code: 393244]: errorCode: 393244, engine: 0
04-09 21:54:22.037  8698  8812 I MicroDetector: Keeping mic open: false
04-09 21:54:22.037  8698  8812 I MicroDetectionWorker: #onError(false)
04-09 21:54:22.037  8698 26821 W DeviceStateChecker: stopped because hotword detection is stopped but cancel is not called.
04-09 21:54:22.083  2022  9153 I OpenGLRenderer: Initialized EGL, version 1.4
04-09 21:54:22.083  2022  9153 D OpenGLRenderer: Swap behavior 2
04-09 21:54:22.116  4291  4302 W System  : A resource failed to call release.

**Comment by wardetta** [comment]
Apparently there is an extra step with the new version if anyone came to this post here is the solution:-
https://developers.google.com/admob/android/quick-start#update_your_androidmanifestxml

Goodluck!
