### ISSUE TITLE
Trying to display Unity Interstitial causes crash

### ISSUE THREAD

**Issue by dannykay1** [googleads/googleads-mobile-unity#910]
When trying to show an interstitial ad on player death, the unity ad causes the game to freeze.  I'm using version 3.16.  This issue has only popped up recently as the ads have been working fine since the first implementation months ago.  Google interstitial show fine, but unity ads cause the game to crash.

I'm getting this error:

E/Ads: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference
                                          at com.google.ads.mediation.unity.UnityAdapter.showInterstitial(UnityAdapter.java:286)
                                          at com.google.android.gms.internal.ads.zzanm.showInterstitial(Unknown Source)
                                          at com.google.android.gms.internal.ads.zzamu.dispatchTransaction(Unknown Source)
                                          at com.google.android.gms.internal.ads.zzfn.onTransact(Unknown Source)
                                          at android.os.Binder.transact(Binder.java:380)
                                          at jt.b(:com.google.android.gms.dynamite_adsdynamite@17122030@17.1.22 (020308-245988633):14)
                                          at com.google.android.gms.ads.internal.mediation.client.f.b(:com.google.android.gms.dynamite_adsdynamite@17122030@17.1.22 (020308-245988633):27)
                                          at com.google.android.gms.ads.nonagon.render.av.a(Unknown Source)
                                          at com.google.android.gms.ads.nonagon.shim.v.R(:com.google.android.gms.dynamite_adsdynamite@17122030@17.1.22 (020308-245988633):69)
                                          at com.google.android.gms.ads.nonagon.shim.k.R(:com.google.android.gms.dynamite_adsdynamite@17122030@17.1.22 (020308-245988633):13)
                                          at com.google.android.gms.ads.internal.client.an.a(:com.google.android.gms.dynamite_adsdynamite@17122030@17.1.22 (020308-245988633):129)
                                          at jv.onTransact(:com.google.android.gms.dynamite_adsdynamite@17122030@17.1.22 (020308-245988633):4)
                                          at android.os.Binder.transact(Binder.java:380)
                                          at com.google.android.gms.internal.ads.zzfm.zza(Unknown Source)
                                          at com.google.android.gms.internal.ads.zzzk.showInterstitial(Unknown Source)
                                          at com.google.android.gms.internal.ads.zzabb.show(Unknown Source)
                                          at com.google.android.gms.ads.InterstitialAd.show(Unknown Source)
                                          at com.google.unity.ads.Interstitial$3.run(Interstitial.java:182)
                                          at android.os.Handler.handleCallback(Handler.java:739)
                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                          at android.os.Looper.loop(Looper.java:135)
                                          at android.app.ActivityThread.main(ActivityThread.java:5349)
                                          at java.lang.reflect.Method.invoke(Native Method)
                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)

**Comment by sjvc** [comment]
I'm having exactly the same issue. Any news?

**Comment by sjvc** [comment]
I fixed it by replacing `<androidPackage spec="com.google.ads.mediation:unity:3.0.0.2">` with `<androidPackage spec="com.google.ads.mediation:unity:3.0.1.0">` in the file `GoogleMobileAds/Editor/UnityMediationDependencies.xml`

**Comment by mtahiriqbaluet** [comment]
Hi @dannykay1, does the solution provided by @sjvc solved your problem? Just asking as I'm facing the same crash problem in my app! Looking forward to your help @stowy!

**Comment by stowy** [comment]
We're looking into this and will provide an update here when resolved.

**Comment by dannykay1** [comment]
Thanks for the response.  I have not tried the fix yet, as I am adding new mediation

**Comment by stowy** [comment]
Confirming this was fixed in version 3.0.1.0 as per @sjvc comment. We will update the dependencies in the Unity package.
