### ISSUE TITLE
Incompatibility with Android - 

### ISSUE THREAD

**Issue by Duobix** [googleads/googleads-mobile-unity#937]
Hi, my recent game build got identified as using nonsupported version of some APIs. 
Below are the stack traces I got from google play console's report, how can I solve those issues?
Thanks in advance.

stack trace 1:
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Ljava/nio/Buffer;->address:J
	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredField(Native Method)
	at akj.a(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):78)
	at akj.d(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):76)
	at akj.<clinit>(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):116)
	at akj.a(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):26)
	at ajd.<clinit>(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):2502)
	at ajd.a(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):20)
	at aio.a(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):26)
	at ajl.a(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):3)
	at ajl.a(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):8)
	at ahr.a(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):88)
	at ww.h_(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):23)
	at tl.a(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):18)
	at td.a(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):12)
	at tg.handleMessage(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):56)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at xs.a(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):5)
	at xs.dispatchMessage(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):4)
	at android.os.Looper.loop(Looper.java:193)
	at android.os.HandlerThread.run(HandlerThread.java:65)

stack trace 2:
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Ljava/nio/Buffer;->address:J
	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredField(Native Method)
	at akj.a(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):78)
	at akj.d(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):76)
	at akj.c(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):53)
	at akj.<clinit>(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):101)
	at akj.a(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):26)
	at ajd.<clinit>(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):2502)
	at ajd.a(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):20)
	at aio.a(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):26)
	at ajl.a(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):3)
	at ajl.a(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):8)
	at ahr.a(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):88)
	at ww.h_(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):23)
	at tl.a(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):18)
	at td.a(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):12)
	at tg.handleMessage(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):56)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at xs.a(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):5)
	at xs.dispatchMessage(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):4)
	at android.os.Looper.loop(Looper.java:193)
	at android.os.HandlerThread.run(HandlerThread.java:65)

stack trace 3:
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/media/AudioTrack;->getLatency()I
	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredMethodInternal(Native Method)
	at java.lang.Class.getPublicMethodRecursive(Class.java:2075)
	at java.lang.Class.getMethod(Class.java:2063)
	at java.lang.Class.getMethod(Class.java:1690)
	at com.google.android.gms.ads.exoplayer3.audio.m.<init>(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):6)
	at com.google.android.gms.ads.exoplayer3.audio.w.<init>(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):7)
	at com.google.android.gms.ads.exoplayer3.audio.w.<init>(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):3)
	at com.google.android.gms.ads.exoplayer3.audio.w.<init>(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):2)
	at com.google.android.gms.ads.exoplayer3.audio.w.<init>(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):1)
	at com.google.android.gms.ads.internal.video.exoplayer3.q.<init>(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):8)
	at com.google.android.gms.ads.internal.video.gmsg.exoplayer3.c.<init>(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):3)
	at com.google.android.gms.ads.internal.video.gmsg.c.a(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):6)
	at com.google.android.gms.ads.internal.video.gmsg.s.a(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):32)
	at com.google.android.gms.ads.internal.webview.j.a(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):312)
	at com.google.android.gms.ads.internal.webview.ac.a(Unknown Source:4)
	at com.google.android.gms.ads.internal.webview.ad.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at xs.a(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):5)
	at com.google.android.gms.ads.internal.util.e.a(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):11)
	at xs.dispatchMessage(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):4)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

stack trace 4:
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionAction(III)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;
	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredMethodInternal(Native Method)
	at java.lang.Class.getPublicMethodRecursive(Class.java:2075)
	at java.lang.Class.getMethod(Class.java:2063)
	at java.lang.Class.getMethod(Class.java:1690)
	at cyw.a(PG:9)
	at cyE.a(PG:12)
	at org.chromium.content.browser.selection.SmartSelectionClient.<init>(PG:5)
	at czl.a(Unknown Source:7)
	at org.chromium.android_webview.AwContents.e(PG:243)
	at org.chromium.android_webview.AwContents.d(PG:210)
	at org.chromium.android_webview.AwContents.<init>(PG:81)
	at vE.run(PG:15)
	at aKc.a(PG:13)
	at aKd.run(Unknown Source:2)
	at org.chromium.base.task.PostTask.b(PG:13)
	at aKc.a(PG:7)
	at com.android.webview.chromium.WebViewChromiumFactoryProvider.b(PG:6)
	at com.android.webview.chromium.WebViewChromium.init(PG:107)
	at android.webkit.WebView.<init>(WebView.java:422)
	at android.webkit.WebView.<init>(WebView.java:348)
	at android.webkit.WebView.<init>(WebView.java:331)
	at android.webkit.WebView.<init>(WebView.java:318)
	at android.webkit.WebView.<init>(WebView.java:308)
	at com.google.android.gms.ads.internal.webview.v.<init>(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):1)
	at com.google.android.gms.ads.internal.webview.q.call(Unknown Source:4)
	at com.google.android.gms.ads.internal.util.br.a(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):19)
	at com.google.android.gms.ads.internal.webview.o.a(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):7)
	at com.google.android.gms.ads.internal.an.a(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):45)
	at com.google.android.gms.ads.internal.k.run(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):12)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at xs.a(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):5)
	at com.google.android.gms.ads.internal.util.e.a(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):11)
	at xs.dispatchMessage(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):4)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

stack trace 5:
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionAction(IIILandroid/view/textclassifier/TextClassification;)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;
	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredMethodInternal(Native Method)
	at java.lang.Class.getPublicMethodRecursive(Class.java:2075)
	at java.lang.Class.getMethod(Class.java:2063)
	at java.lang.Class.getMethod(Class.java:1690)
	at cyw.a(PG:11)
	at cyE.a(PG:12)
	at org.chromium.content.browser.selection.SmartSelectionClient.<init>(PG:5)
	at czl.a(Unknown Source:7)
	at org.chromium.android_webview.AwContents.e(PG:243)
	at org.chromium.android_webview.AwContents.d(PG:210)
	at org.chromium.android_webview.AwContents.<init>(PG:81)
	at vE.run(PG:15)
	at aKc.a(PG:13)
	at aKd.run(Unknown Source:2)
	at org.chromium.base.task.PostTask.b(PG:13)
	at aKc.a(PG:7)
	at com.android.webview.chromium.WebViewChromiumFactoryProvider.b(PG:6)
	at com.android.webview.chromium.WebViewChromium.init(PG:107)
	at android.webkit.WebView.<init>(WebView.java:422)
	at android.webkit.WebView.<init>(WebView.java:348)
	at android.webkit.WebView.<init>(WebView.java:331)
	at android.webkit.WebView.<init>(WebView.java:318)
	at android.webkit.WebView.<init>(WebView.java:308)
	at com.google.android.gms.ads.internal.webview.v.<init>(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):1)
	at com.google.android.gms.ads.internal.webview.q.call(Unknown Source:4)
	at com.google.android.gms.ads.internal.util.br.a(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):19)
	at com.google.android.gms.ads.internal.webview.o.a(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):7)
	at com.google.android.gms.ads.internal.an.a(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):45)
	at com.google.android.gms.ads.internal.k.run(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):12)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at xs.a(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):5)
	at com.google.android.gms.ads.internal.util.e.a(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):11)
	at xs.dispatchMessage(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):4)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

stack trace 6:
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionModified(II)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;
	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredMethodInternal(Native Method)
	at java.lang.Class.getPublicMethodRecursive(Class.java:2075)
	at java.lang.Class.getMethod(Class.java:2063)
	at java.lang.Class.getMethod(Class.java:1690)
	at cyw.a(PG:6)
	at cyE.a(PG:12)
	at org.chromium.content.browser.selection.SmartSelectionClient.<init>(PG:5)
	at czl.a(Unknown Source:7)
	at org.chromium.android_webview.AwContents.e(PG:243)
	at org.chromium.android_webview.AwContents.d(PG:210)
	at org.chromium.android_webview.AwContents.<init>(PG:81)
	at vE.run(PG:15)
	at aKc.a(PG:13)
	at aKd.run(Unknown Source:2)
	at org.chromium.base.task.PostTask.b(PG:13)
	at aKc.a(PG:7)
	at com.android.webview.chromium.WebViewChromiumFactoryProvider.b(PG:6)
	at com.android.webview.chromium.WebViewChromium.init(PG:107)
	at android.webkit.WebView.<init>(WebView.java:422)
	at android.webkit.WebView.<init>(WebView.java:348)
	at android.webkit.WebView.<init>(WebView.java:331)
	at android.webkit.WebView.<init>(WebView.java:318)
	at android.webkit.WebView.<init>(WebView.java:308)
	at com.google.android.gms.ads.internal.webview.v.<init>(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):1)
	at com.google.android.gms.ads.internal.webview.q.call(Unknown Source:4)
	at com.google.android.gms.ads.internal.util.br.a(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):19)
	at com.google.android.gms.ads.internal.webview.o.a(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):7)
	at com.google.android.gms.ads.internal.an.a(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):45)
	at com.google.android.gms.ads.internal.k.run(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):12)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at xs.a(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):5)
	at com.google.android.gms.ads.internal.util.e.a(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):11)
	at xs.dispatchMessage(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):4)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

stack trace 7:
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionModified(IILandroid/view/textclassifier/TextClassification;)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;
	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredMethodInternal(Native Method)
	at java.lang.Class.getPublicMethodRecursive(Class.java:2075)
	at java.lang.Class.getMethod(Class.java:2063)
	at java.lang.Class.getMethod(Class.java:1690)
	at cyw.a(PG:7)
	at cyE.a(PG:12)
	at org.chromium.content.browser.selection.SmartSelectionClient.<init>(PG:5)
	at czl.a(Unknown Source:7)
	at org.chromium.android_webview.AwContents.e(PG:243)
	at org.chromium.android_webview.AwContents.d(PG:210)
	at org.chromium.android_webview.AwContents.<init>(PG:81)
	at vE.run(PG:15)
	at aKc.a(PG:13)
	at aKd.run(Unknown Source:2)
	at org.chromium.base.task.PostTask.b(PG:13)
	at aKc.a(PG:7)
	at com.android.webview.chromium.WebViewChromiumFactoryProvider.b(PG:6)
	at com.android.webview.chromium.WebViewChromium.init(PG:107)
	at android.webkit.WebView.<init>(WebView.java:422)
	at android.webkit.WebView.<init>(WebView.java:348)
	at android.webkit.WebView.<init>(WebView.java:331)
	at android.webkit.WebView.<init>(WebView.java:318)
	at android.webkit.WebView.<init>(WebView.java:308)
	at com.google.android.gms.ads.internal.webview.v.<init>(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):1)
	at com.google.android.gms.ads.internal.webview.q.call(Unknown Source:4)
	at com.google.android.gms.ads.internal.util.br.a(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):19)
	at com.google.android.gms.ads.internal.webview.o.a(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):7)
	at com.google.android.gms.ads.internal.an.a(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):45)
	at com.google.android.gms.ads.internal.k.run(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):12)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at xs.a(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):5)
	at com.google.android.gms.ads.internal.util.e.a(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):11)
	at xs.dispatchMessage(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):4)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by UragayalaDeepika** [comment]
@Duobix This is a known issue and our team is investigating the root cause for these ANRs. Can you please open a new thread on our [Mobile Ads SDK Forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk) so that we can keep you posted about the latest updates that we receive from our team and assist you further?
