### ISSUE TITLE
A WebView method was called on thread 'FinalizerDaemon'.

### ISSUE THREAD

**Issue by ivk1800** [googleads/googleads-mobile-unity#986]
unity version: 2019.1.8f
plugin version: 3.18.0
ads version: com.google.android.gms:play-services-ads:17.2.1
JarResolver: v1.2.119
reproduced on pixel 2 android 9 and poco f1

rewarded video not corrected work with test unitid `ca-app-pub-3940256099942544/5224354917`

AdsActivity not auto closed, if close manual,
`OnAdRewarded` and `OnAdClosed `called together

first `OnAdRewarded  `then `OnAdClosed `

if Beckend Mono, will be exception
if Beckend IL2CPP will be crash

```
E/System: java.lang.RuntimeException: java.lang.Throwable: A WebView method was called on thread 'FinalizerDaemon'. All WebView methods must be called on the same thread. (Expected Looper Looper (main, tid 2) {41c978b} called on null, FYI main Looper is Looper (main, tid 2) {41c978b})
        at android.webkit.WebView.checkThread(WebView.java:2443)
        at android.webkit.WebView.evaluateJavascript(WebView.java:856)
        at com.google.android.gms.ads.internal.webview.v.evaluateJavascript(:com.google.android.gms.policy_ads_fdr_dynamite@20300000@20300000.251657827.251657827:4)
        at com.google.android.gms.ads.internal.webview.v.f(:com.google.android.gms.policy_ads_fdr_dynamite@20300000@20300000.251657827.251657827:3)
        at com.google.android.gms.ads.internal.webview.v.g(:com.google.android.gms.policy_ads_fdr_dynamite@20300000@20300000.251657827.251657827:4)
        at com.google.android.gms.ads.internal.webview.v.a(:com.google.android.gms.policy_ads_fdr_dynamite@20300000@20300000.251657827.251657827:46)
        at com.google.android.gms.ads.internal.webview.v.a(:com.google.android.gms.policy_ads_fdr_dynamite@20300000@20300000.251657827.251657827:42)
        at com.google.android.gms.ads.internal.webview.t.a(:com.google.android.gms.policy_ads_fdr_dynamite@20300000@20300000.251657827.251657827:15)
        at com.google.android.gms.ads.internal.video.n.a(:com.google.android.gms.policy_ads_fdr_dynamite@20300000@20300000.251657827.251657827:12)
        at com.google.android.gms.ads.internal.video.n.j(:com.google.android.gms.policy_ads_fdr_dynamite@20300000@20300000.251657827.251657827:4)
        at com.google.android.gms.ads.internal.video.ad.a(Unknown Source:5)
        at com.google.android.gms.ads.internal.video.n.onWindowVisibilityChanged(:com.google.android.gms.policy_ads_fdr_dynamite@20300000@20300000.251657827.251657827:4)
        at android.view.View.dispatchDetachedFromWindow(View.java:18391)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3777)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3769)
        at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5359)
        at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5330)
        at android.view.ViewGroup.removeView(ViewGroup.java:5261)
        at com.google.android.gms.ads.internal.overlay.d.i(:com.google.android.gms.policy_ads_fdr_dynamite@20300000@20300000.251657827.251657827:1)
        at com.google.android.gms.ads.internal.webview.v.destroy(:com.google.android.gms.policy_ads_fdr_dynamite@20300000@20300000.251657827.251657827:2)
        at com.google.android.gms.ads.internal.webview.t.destroy(:com.google.android.gms.policy_ads_fdr_dynamite@20300000@20300000.251657827.251657827:10)
        at com.google.android.gms.ads.nonagon.ad.rewardedvideo.c.finalize(:com.google.android.gms.policy_ads_fdr_dynamite@20300000@20300000.251657827.251657827:5)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:250)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237)
        at java.lang.Daemons$Daemon.run(Daemons.java:103)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by AliahmadDev** [comment]
I am also getting this issue and its causing crashes reports in google play console. As much as i have analyzed, this is to be fixed by admob or from unity team, means there is no faulty code causing this issue.

**Comment by stowy** [comment]
What number of crashes are you seeing for this issue? We believe it is
fixed in production for devices running an up to date version of Google
Play services.
